### PR TITLE
marketplace api for stored credit cards

### PR DESCRIPTION
**Pull request by stasdrvn**
Added functionality to purchase from admin marketplace by saved credir card. PIN was removed.

### CODE REVIEW

**Comment by straightlight** [comment]
While the rests of the lines might look ok, idealistically speaking, I am not sure this one should be in as such:

```$_['text_no_cards']		 = 'No payment methods have been added to your account on www.opencart.com!';```

**Comment by stasdrvn** [comment]
Updated. Issue appeared due to tabulation

**Comment by straightlight** [comment]
While the tabulation itself may be the case, I was rather referring to the sentence itself.

**Comment by stasdrvn** [comment]
Get it from opencart.com. If Daniel decides to change it, so will change it with no problem.

**Comment by straightlight** [comment]
$_['text_no_cards'] does not exist in OC v3.0.3.6 nor the master branch nor should it.

**Pull request closed without merging**
