### PR TITLE
Replaced hash with sha1_file function - system/library/template/template.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**
https://www.php.net/manual/en/function.sha1-file.php

### CODE REVIEW

**Comment by ADDCreative** [comment]
You are trying to calculate the sha1 hash of a file that doesn't exist! ($filename . $code) is only part off a filename.

**Comment by cgcmart** [comment]
`hash_file('sha1', $filename . $code)`

**Comment by TheCartpenter** [comment]
> `hash_file('sha1', $filename . $code)`

Yes, I had this one in mind as well. Will make the change.

**Comment by ADDCreative** [comment]
`$filename . $code` is not a file that will exist. Trying to hash it is pointless weather useing hash_file or sha1_file. The original code is making a unique filename from the name and the template contents.

**Comment by TheCartpenter** [comment]
md5 is more likely where it should be improved for that.

**Comment by ADDCreative** [comment]
> md5 is more likely where it should be improved for that.

What does that even mean?

**Comment by TheCartpenter** [comment]
It means that md5 is no longer in use.

**Comment by ADDCreative** [comment]
The hash algorithm is irrelevant. You can't hash something that doesn't exist.

**Comment by TheCartpenter** [comment]
There are other ways to do this. MD5 algorithm is simply history these days. It's good to say that it works but it's not as efficient as it used to be nowadays.

**Comment by TheCartpenter** [comment]
More information about this would be to use the sha256 with buffering as opposed to MD5: https://stackoverflow.com/a/52183613 .

**Comment by ADDCreative** [comment]
You are completely missing the point. The original code was using a hash to make a filename for the cache file. You change is trying to hash the contents of a file that doesn't exist.

**Comment by TheCartpenter** [comment]
I didn't missed the point. I was also addressing one in the meantime. However, I will replace the hash function but that MD5 parameter should no longer be there.

**Comment by danielkerr** [comment]
its fine as is. and no reason to use sha instead of md5. its not a security issue. its just hashing for unique name,

**Pull request closed without merging**
