### PR TITLE
Avoid to fill up log with notices about unlink is not possible

### PR DESCRIPTION
**Pull request by osworx**
Added clearstatcache() to avoid notices in log file

### CODE REVIEW

**Comment by ADDCreative** [comment]
clearstatcache won't help as it only clears the file status cache for the current process and unlink() clears the file status cache automatically anyway. The unlink messages will likely be cause by a race condition between 2 processes.

Also passing a file is pointless if clear_realpath_cache is set to false.

The following would be enough to suppress the messages.
```php
@unlink($file);
```
If you still wanted to display genuine errors but not those generated by race conditions you you could use.
```php
if (!@unlink($file)) {
	if (is_file($file)) {
		unlink($file);
	}
}
```

**Comment by osworx** [comment]
The problem is, is_file is cached, see: https://www.php.net/manual/en/function.is-file.php
Therefore the function calls a - possible - cached file and is therefore not able to delete (unlink) the file.

Using the @ will suppress only a possible output - should be not the final solution!

Had such issue also with some OC 2.x installations, adding clearstatcache() solved always the problem.
If i run the script without that, the error.log is full is warnings ..

The problem is, that I assume this will happen also at many other users. And the error.log is filling and filling up with stupid entries as long as not new entries are possible (because of the size).
And some clients had then the problem, that the shop began to oprate in "crazy mode" - means not every funcion could be fullfilled and customers had troubles to order!

**Comment by ADDCreative** [comment]
Have a good read of the documentation you posted a link to. https://www.php.net/manual/en/function.clearstatcache.php#:~:text=However%20unlink()%20clears%20the%20cache%20automatically.

It states.
> However [unlink()](https://www.php.net/manual/en/function.unlink.php) clears the cache automatically.

You can also see this in the PHP source code.
https://github.com/php/php-src/blob/450740cbb600fb1b26f2a048d312bbf7fb5a9a24/main/streams/plain_wrapper.c#L1243-L1267

So calling ```clearstatcache(false, $file);``` after ```unlink($file);``` is pointless as the file has already has it's status cache cleared.

Also ```clearstatcache(false, $file);``` is actually an invalid combination of parameters and is the equivalent of ```clearstatcache()```.
https://github.com/php/php-src/blob/e5a30274d8d62f5c392ba7c20e8a21e52ee72a2b/ext/standard/filestat.c#L685-L705

Even if clearstatcache had an effect, you can still get the race condition if another process deletes the file between file_exists and unlink.

**Comment by mhcwebdesign** [comment]
What exact issues are you guys trying to resolve here? What exact error messages?

**Comment by ADDCreative** [comment]
@mhcwebdesign Probably the ```Warning: unlink(/???/storage/cache/cache.???): No such file or directory in /???/www/system/library/cache/file.php``` messages, which are usually changed caused by race conditions (often caused by bots), configuration issues or bugs in extensions. Probably best described at https://forum.opencart.com/viewtopic.php?t=223656#p820470.

As stated in my comment https://github.com/opencart/opencart/pull/14096#issuecomment-2304407187 this change should have no effect (other than a very small change in timings).

**Comment by mhcwebdesign** [comment]
Hmm, in OpenCart 4 it uses something like this:

```
if (!@unlink($file)) {
    clearstatcache(false, $file);
}
```

**Comment by ADDCreative** [comment]
Adding the @ in front of unlink suppresses the warnings. Adding the clearstatcache was originally my idea (See https://github.com/opencart/opencart/issues/6321). However, on testing and looking at the PHP source code it does nothing, so can be remove.

**Comment by mhcwebdesign** [comment]
All right, let's just use this one then:

`@unlink($file);`

See https://github.com/opencart/opencart/commit/23dcc645d783b93a1de03e0d2d0d0f0e349c2dde

**Comment by hayden-t** [comment]
Hi guys. Im on 4.0.1.1 and still getting cache unlink errors.   
[https://github.com/opencart/opencart/blob/8a8f42e5992fc9dfaa25d259f80ebd62837201b7/upload/system/framework.php#L36](https://github.com/opencart/opencart/blob/8a8f42e5992fc9dfaa25d259f80ebd62837201b7/upload/system/framework.php#L36)  
It has this inside the error handler which i guess is meant to stop the errors being reported but they still are for me

```
set_error_handler(function(string $code, string $message, string $file, string $line) use ($log, $config) {
// error suppressed with @
if (@error_reporting() === 0) {
 return false;
}
```

I noticed in master this is not even used at all: so how does it stop them, or doesnt it ?  
https://github.com/opencart/opencart/blob/f0d42f933a3b816e8b862e6ac8892f93d87c7843/upload/system/framework.php#L36

**Comment by hayden-t** [comment]
Turns out when checking error level with error\_reporting() it does not (for me) return 0 when @ is used to suppress, it returns 4437 which can be decoded here [https://maximivanov.github.io/php-error-reporting-calculator/](https://maximivanov.github.io/php-error-reporting-calculator/)  
It should instead be:  
 `if (!(error_reporting() & E_WARNING)) {`  
 `return false;`  
 `}`

**Comment by hayden-t** [comment]
some other related posts:

#12483

#12660

**Comment by ADDCreative** [comment]
@hayden-t OpenCart doesn't support the @ error suppressor any more. Which is a bit of an issue as Twig requires it https://github.com/opencart/opencart/issues/11596#issuecomment-1904250142.

I made a pull request #12660 that adds the following to the error handlers. You would need to make that change to add it back.

``` php
if (!(error_reporting() & $code)) {
	return false;
}
```

**Comment by hayden-t** [comment]
i might just make a pull request to put the cache delete in a try catch as yours got rejected, but pretty sure it will get rejected too,

**Comment by hayden-t** [comment]
#14778

**Pull request closed without merging**
