### PR TITLE
Search in categories feature

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
This pull request adds the following features:
1) Ability to list all subcategories of a certain parent category.
2) Ability to search among categories by a certain word.
3) The category name filter can now also match words in the statement, not only the beginning of an statement.

image

### CODE REVIEW

**Comment by DRSDavidSoft** [comment]
@jamesallsup and @danielkerr:
Hi, can you review my pull request, please? I realized I had misplaced committed files, but everything's fine now for this pull request.

The edits will allow users to filter categories based on their names and/or the name of their parents.

**Comment by arnisjuraga** [comment]
@DRSDavidSoft 
please, fix in .tpl .js code:

~~~js
var url = 'catalog/category&';
...
url: 'catalog/category/autocomplete&&filter_name=' +  
encodeURIComponent(request),
~~~


should be
~~~js
var url = '?route=catalog/category&token=<?= $token; ?>&';
...
url: '?route=catalog/category/autocomplete&token=<?= $token ?>&filter_name=' +
encodeURIComponent(request),
~~~

Also, you could add  'Clear' button for filter.

**Comment by DRSDavidSoft** [comment]
@arnisjuraga I fixed the problems regarding the URL style.
Sorry about that, in my own fork of Opencart, I have used `REQUEST_URI` instead if `?route=` query and also moved the `token` inside a cookie instead of the URL, and I forgot to revert them back before submitting the template file.

Opencart Micro

Is everything ok for a pull-request now?

**Comment by straightlight** [comment]
Multiple corrections to be made. For instance:

```class ControllerCatalogCategory extends Controller {```

is being used inside the model catalog category instead of the controller. Therefore, this commit will now be closed.

**Pull request closed without merging**
