### PR TITLE
Update seo_url.php

### PR DESCRIPTION
**Pull request by danijelGombac**

### CODE REVIEW

**Comment by chulcha** [comment]
What for?
Hope the commit won't be accepted

**Comment by mhcwebdesign** [comment]
What are your changes for? What issue or problem are you trying to solve?

**Comment by stalker780** [comment]
This is an attempt to fix seo_url in OC4.

I have discribed this earlier in https://github.com/opencart/opencart/issues/8923#issuecomment-739525181

But in my opinion it is not a good idea to move Action construction to seo_url controller.
We need to wait for a fix from Daniel.

**Comment by danijelGombac** [comment]
@stalker780 

catalog/controller/startup/maintenance.php has also Action construction in controller and in admin login and permission. Why seo_url should different?

I fixed seo_url in my store, but this changes should be done by Daniel, because is too important feature. This is why i closed all.

**Pull request closed without merging**
