### PR TITLE
rename user_permission controller

### PR DESCRIPTION
**Pull request by pine3ree**
to `user_group` for "module" naming consistency.

maybe we should also add an upgrade utility to rename u'ser/user_permission' in the u`ser_group `db table , `permission` json_encoded column. 

Hello @danielkerr ,
does thes changes make sense to you?

### CODE REVIEW

**Comment by danielkerr** [comment]
can not use user group as some web hosts block this word in the url

**Comment by pine3ree** [comment]
@danielkerr ,

oh, ok, sorry. I just thought it was an old partial renaming leftover....
kind regards

**Comment by pine3ree** [comment]
@danielkerr 
..or we could rename it to `user_role`...

**Comment by danielkerr** [comment]
its fine!

**Pull request closed without merging**
