### PR TITLE
Update column_left.php

### PR DESCRIPTION
**Pull request by eka7a**

### CODE REVIEW

**Comment by straightlight** [comment]
Don't see the goal of this replacement. Therefore, this commit will now be closed.

**Comment by eka7a** [comment]
install

**Comment by straightlight** [comment]
You're probably talking about the master branch version. In the pre-release version, not much related language keys that can be found. I will re-open the commit for further investigation.

**Comment by eka7a** [comment]
Yes, master branch.

@danielkerr  Instead of adding code for each language, it would be more useful to check language directories and list languages automatically. In this way, it is necessary to add code in every new language.

**Pull request merged**
