### PR TITLE
Added url_encode on filter_customer - admin/controller/sale/recurring.php file.

### PR DESCRIPTION
**Pull request by straightlight**

### CODE REVIEW

**Comment by ADDCreative** [comment]
Have you tested this? As the customer name would of been encoded before storing in the database, decoding before the query will not return the correct results if the filter contains special characters.

**Comment by straightlight** [comment]
Already answered here: https://github.com/opencart/opencart/pull/8738#issuecomment-709997188 .

**Comment by ADDCreative** [comment]
That is a completely different problem.

**Comment by straightlight** [comment]
Let's not forget that the model also contains (string) in front of their variables when validating string types on database queries. I have already addressed this issue to Daniel before but those (string) types seem to remain there unfortunately.

**Comment by ADDCreative** [comment]
Typecasting to (string) will not make any difference and is nothing to do with the problem.

**Pull request closed without merging**
