### PR TITLE
Update customer_group.twig - add footer/header after sort and update user_list

### PR DESCRIPTION
**Pull request by pemaier**
solution for issue #13155

### CODE REVIEW

**Comment by TheCartpenter** [comment]
It simply takes an event from an extension to pull that list. It is not a bug.

**Comment by pemaier** [comment]
@TheCartpenter If only an event is required I'm very interested in your solution :)

**Comment by pemaier** [comment]
Added Firstname/Lastname and new status style to user list.
image

**Comment by pemaier** [comment]
Added User Group to user list
image

**Comment by cgcmart** [comment]
Great work.
Happy Holiday!

**Comment by TheCartpenter** [comment]
> Added User Group to user list image

There are no validation set in the save() method that checks for active groups. Therefore, your integration can affect many customers at once. Especially from those who are using subscription cycles, and that their cycle period have not yet ended, it could become chaotic.

**Comment by pemaier** [comment]
@TheCartpenter - Interesting to listen what you tell. But I can't see any point where my changes are saving something. I don't see where I'm using the save() method ... there is only reading of data. And on the other side there is also no way to deactivate a user group. Also it is something new for me that a user or user_id is related to subscription cycles. May I don't understand the relation now. I don't see the problem but you are welcome to explain where the problem is with this changes and where the chaos can be?

**Comment by TheCartpenter** [comment]
> @TheCartpenter - Interesting to listen what you tell. But I can't see any point where my changes are saving something. I don't see where I'm using the save() method ... there is only reading of data. And on the other side there is also no way to deactivate a user group. Also it is something new for me that a user or user_id is related to subscription cycles. May I don't understand the relation now. I don't see the problem but you are welcome to explain where the problem is with this changes and where the chaos can be?

A bit misleading since your PR subject is about the ```customer_group``` - not the ```user_group```. My mistake., I guess; I thought your screenshot was still referring to the ```customer_group```.

**Comment by cgcmart** [comment]
@TheCartpenter You probably confused back end user with store front customer / subscriber.

**Comment by TheCartpenter** [comment]
> @TheCartpenter You probably confused back end user with store front customer / subscriber.

I was rather confused by the PR title vs. the screenshot that was posted since it's about two separate things.

**Comment by danielkerr** [comment]
lets not mix up the commits.

**Pull request closed without merging**
