### PR TITLE
Create common class: urls, breadcrumbs and settings

### PR DESCRIPTION
**Pull request by diegospm**
the header urls can be loaded through a class in the common folder.

The code snippets below can be overridden by the urls controller class.

for example this:

$url = '';

			if (isset($this->request->get['filter_name'])) {
				$url .= '&filter_name=' . urlencode(html_entity_decode($this->request->get['filter_name'], ENT_QUOTES, 'UTF-8'));
			}
			if (isset($this->request->get['filter_model'])) {
				$url .= '&filter_model=' . urlencode(html_entity_decode($this->request->get['filter_model'], ENT_QUOTES, 'UTF-8'));
			}
			if (isset($this->request->get['filter_price'])) {
				$url .= '&filter_price=' . $this->request->get['filter_price'];
			}

for this:

$urls = $this->load->controller('common/urls');

$urls->get();

### CODE REVIEW

**Comment by diegoldm** [comment]
to access the urls as a string, just call:

$urls->getLink() 

or 

$urls->getLink([
  'route' => 'specific route',
  'url' => 'specific url'
]);

**Comment by diegospm** [comment]
the breadcrumbs also can be loaded through a class in the common folder.

usage:

$breadcrumbs = $this->load->controller('common/breadcrumbs');

$breadcrumbs->setDefaults();
or
$breadcrumbs->set([
  'text' => 'define text'
  'href' => 'define href'
]);

$breadcrumbs->render();

**Comment by diegospm** [comment]
it is not necessary to check each data key in extension or modules.

for example, we could replace this code:

if (isset($this->request->post['payment_bank_transfer_total'])) {
			$data['payment_bank_transfer_total'] = $this->request->post['payment_bank_transfer_total'];
		} else {
			$data['payment_bank_transfer_total'] = $this->config->get('payment_bank_transfer_total');
		}
		if (isset($this->request->post['payment_bank_transfer_order_status_id'])) {
			$data['payment_bank_transfer_order_status_id'] = $this->request->post['payment_bank_transfer_order_status_id'];
		} else {
			$data['payment_bank_transfer_order_status_id'] = $this->config->get('payment_bank_transfer_order_status_id');
		}

if (isset($this->request->post['payment_bank_transfer_status'])) {
			$data['payment_bank_transfer_status'] = $this->request->post['payment_bank_transfer_status'];
		} else {
			$data['payment_bank_transfer_status'] = $this->config->get('payment_bank_transfer_status');
		}
		if (isset($this->request->post['payment_bank_transfer_sort_order'])) {
			$data['payment_bank_transfer_sort_order'] = $this->request->post['payment_bank_transfer_sort_order'];
		} else {
			$data['payment_bank_transfer_sort_order'] = $this->config->get('payment_bank_transfer_sort_order');
		}

by this code:

$data = $this->load->controller ('common/settings', ['code' => 'payment_bank_transfer']);

and if we want to define a value default for the key, just use:

if (empty($data['payment_bank_transfer_order_status_id'])) {
    $data['payment_bank_transfer_order_status_id'] = array();
}

**Comment by diegospm** [comment]
I am suggesting these changes in order to decrease the repetitions in the codes, but I do not want to seem rude, because I learned to program with the OC and would like to share in order to contribute with this excellent platform and community :)

I hope you like my suggestions ;)

**Pull request closed without merging**
