### PR TITLE
Update redis.php

### PR DESCRIPTION
**Pull request by TheCartpenter**
https://github.com/opencart/opencart/pull/13325
https://github.com/opencart/opencart/pull/13318
https://github.com/opencart/opencart/pull/13327

### CODE REVIEW

**Comment by AJenbo** [comment]
Stop spamming, adjust the formatting rules so that the test pass if you think they should be changed.

**Comment by TheCartpenter** [comment]
> Stop spamming, adjust the formatting rules so that the test pass if you think they should be changed.

That's a lot of closing from other users as well just during now that seem to fail your expectations. I'm not sure there's gonna be people appreciating; the fact that they have to close countless posts as opposed to previous times while they felt they could submit their proposals without restrictions. We'll see over time how this goes, I guess.

**Comment by TheCartpenter** [comment]
@danielkerr: Can you please investigate this issue? Over 9 commits were closed this morning also included on behalf from other users whereas this user is expecting such severity levels to submit proposals on your repository.

Thank you.

**Comment by mhcwebdesign** [comment]
@TheCartpenter: Will you please stop spamming here with your daily countless useless cosmetic changes please? It's time to focus on some real development and bugfixes here.

**Comment by TheCartpenter** [comment]
> @TheCartpenter: Will you please stop spamming here with your daily countless useless cosmetic changes please? It's time to focus on some real development and bugfixes here.

The fact that 7 commits were closed all at once by other users have nothing to do with SPAMs since, before two weeks ago, there were no such regulations with indents in order to submit our proposals. Therefore, you want real developments to occur? Then, start reflecting on this for one!

**Comment by danielkerr** [comment]
Yep. Needs to be written rules. I also did not close his commits down.

**Comment by danielkerr** [comment]
Just leave them there I will dealw the ith them so are fixes and not just extra spaces

**Comment by AJenbo** [comment]
I have written sections on how to install and use the tools to make it easy for anyone:
https://github.com/opencart/opencart/wiki/Coding-Standards#cs-fixer

**Comment by TheCartpenter** [comment]
> Just leave them there I will dealw the ith them so are fixes and not just extra spaces

I hope you are aware that ```php-cs-fixer``` relies on the ```php interpreter``` as a ```dependency``` and may need to be used with caution from our ```console``` regardless of the OS after 1 day and the effects it can cause afterwards on the repository by realigning the... indents...

**Comment by AJenbo** [comment]
> I hope you are aware that `php-cs-fixer` relies on the `php interpreter` as a `dependency` and may need to be used with caution from our `console` regardless of the OS after 1 day and the effects it can cause afterwards on the repository by realigning the... indents...

None of that follows, by the same logic OC might stop being an e-commerce platform from one day to the other because it also relies on the PHP interpreter. It honestly sounds like you don't know what you are talking about.

**Comment by TheCartpenter** [comment]
> > I hope you are aware that `php-cs-fixer` relies on the `php interpreter` as a `dependency` and may need to be used with caution from our `console` regardless of the OS after 1 day and the effects it can cause afterwards on the repository by realigning the... indents...
> 
> None of that follows, by the same logic OC might stop being an e-commerce platform from one day to the other because it also relies on the PHP interpreter. I don't mean any disrespect, but it honestly sounds like you don't know what you are talking about.

That simply means that you weren't able to reproduce the issue. However, you will notice by using a realtime protection anti-malware that the case is indeed present. Even though it could be a false / positive, these scenarios also needs to be dealt with when it occurs.

**Pull request closed without merging**
