### PR TITLE
update cache delete for redis

### PR DESCRIPTION
**Pull request by haxcop**
updated delete() for del() to work correctly with latest redis version

### CODE REVIEW

**Comment by straightlight** [comment]
It has never been reported where the delete() method in the library cache handler creates problematic issues by keeping the same conventional name or none that has been linked from from this namespace. 

Therefore, this commit will now be closed.

**Comment by haxcop** [comment]
@straightlight when one person reports and error bug or improvement, the right way to understand the report is to test it yourself accordingly to the report, there's no need for someone else to report the same issue to be sure this is happening. Otherwise, the purpose of Testing and reporting here for all of us is broken as you just rely on others to face the same issue, but you have to also know and understand the fact that other may not be using the same version of Redis as I used to face the problem, your duty before closing this is to understand the issue and replicate it before saying is wrong.

**Comment by ADDCreative** [comment]
@haxcop You have changed the wrong delete. You need to change this one.
https://github.com/opencart/opencart/blob/0fdfc437c9be81a712e8cd6358612c3bb7f0c356/upload/system/library/cache/redis.php#L31

@straightlight This will need changing, although this pull request is wrong. PhpRedis delete method is deprecated. See: https://github.com/phpredis/phpredis/#del-delete-unlink

> Note: delete is an alias for del and will be removed in future versions of phpredis.

**Comment by straightlight** [comment]
I re-opened the case: #7825 . While the #7826 may have a wrong pull request, there's no need to re-address the issue.

**Pull request closed without merging**
