### PR TITLE
SEO optimization and automatization of OpenCart 4

### PR DESCRIPTION
**Pull request by ppalashturov**
Hello,
We from OpenCart Bulgaria have an idea to do some extra SEO optimization and automatization of OpenCart 4. We want to apply and make a pull request with the following functions:

Adding a PHP library for the SEO tags and adding the Documents library to add the tags (meta, schema, etc.) to each page. We are planning to use: https://github.com/melbahja/seo

Add functionality to generate sitemap.xml.

Add functionality for Image optimization like selecting image formats jpg or WebP from the admin panel when caching images. Add LazyLoad library.

Editable title or H1 tags in the pages of the default template.

Adding functionality for automatic generation of URL addresses.

As well as several other things for the better SEO.

Best regards!

### CODE REVIEW

**Comment by AJenbo** [comment]
Could you update the PR, the dependencies have changed since you made it.

**Comment by ppalashturov** [comment]
@AJenbo Done!

**Comment by AJenbo** [comment]
Looks like there are a few minor issues with the code style, you can fix them by running the following command from the project folder:
```bash
mkdir -p tools/php-cs-fixer
composer require --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer
```
```bash
tools/php-cs-fixer/vendor/bin/php-cs-fixer fix
```

**Comment by TheCartpenter** [comment]
By considering this cache with a ```vendor```, it also means that the ```startup/seo_url``` no longer takes the lead.

**Comment by ppalashturov** [comment]
@AJenbo Done. @TheCartpenter I don't understand!

**Comment by TheCartpenter** [comment]
> @AJenbo Done. @TheCartpenter I don't understand!

I know, you don't and you're not the only one who has suggested this from the same ```vendor```. Which is exactly you are proposing these commits to be merged. As you can see from that ```vendor```, they're falling behind of 1.5 years already compared to this repository. Meaning, ```lint.yml``` will provide the facts on anyhow in regard to the maintenance of this package, for one. Furthermore, by reading their ```README.md``` file, it is clearly that, to what you're suggesting, you are only providing the minimal integration idea whereas this ```vendor``` can do much more - including the SEO URLs as well as use with APIs with ```$indexing```, therefore, suggests the use with third-parties to handle SEOs that the core can already handle.

**Comment by AJenbo** [comment]
@ppalashturov nice work looks like the proposed changes are passing all the tests now 👍

Hopefully Daniel will have time to evaluate the feature soon.

**Comment by TheCartpenter** [comment]
Except it won't succeed all the tests when it comes to third-party features merged into the core.

**Comment by ppalashturov** [comment]
> @ppalashturov nice work looks like the proposed changes are passing all the tests now 👍
> 
> Hopefully Daniel will have time to evaluate the feature soon.

Thanks!

**Comment by AJenbo** [comment]
> Except it won't succeed all the tests when it comes to third-party features merged into the core.

You are wrong, that's not how it works.

**Comment by TheCartpenter** [comment]
> > Except it won't succeed all the tests when it comes to third-party features merged into the core.
> 
> You are wrong, that's not how it works.

Then, in this case, you simply haven't looked at the unmaintained package as you are encouraging third-party ```vendors``` to be merged into the core whereas no service agreement has been mitigated with OC.

**Comment by AJenbo** [comment]
> Then, in this case, you simply haven't looked at the unmaintained package as you are encouraging third-party `vendors` to be merged into the core

None of that is true either.

> whereas no service agreement has been mitigated with OC.

This is just non nonsensical, try looking up what a [service agreement](https://ironcladapp.com/journal/contracts/standard-service-agreement/) is and what the word [mitigated](https://dictionary.cambridge.org/dictionary/english/mitigated) means.

**Comment by TheCartpenter** [comment]
> > Then, in this case, you simply haven't looked at the unmaintained package as you are encouraging third-party `vendors` to be merged into the core
> 
> None of that is true either.
> 
> > whereas no service agreement has been mitigated with OC.
> 
> This is just non nonsensical, try looking up what a [service agreement](https://ironcladapp.com/journal/contracts/standard-service-agreement/) is and what the word [mitigated](https://dictionary.cambridge.org/dictionary/english/mitigated) means.

https://github.com/melbahja/seo/blob/master/src/Indexing.php#L13-L37

If that gets merged, it's on you.

**Comment by AJenbo** [comment]
@TheCartpenter in case you haven't noticed this isn't my PR, I have nothing to do with the code you are linking to. You failing to clearly communicate is on you not anyone else.

**Comment by TheCartpenter** [comment]
> @TheCartpenter in case you haven't noticed this isn't my PR, I have nothing to do with the code you are linking to. You failing to clearly communicate is on you not anyone else.

Regardless. As per this response on your behalf: https://github.com/opencart/opencart/pull/12945#issuecomment-1872195368 , you are the one encouraging this.

**Comment by AJenbo** [comment]
I guess you don't know what "encouraging" means either, or maybe you don't understand what is being said in the message. Regardless I'm not going to waist my time trying to explain it to your.

**Comment by TheCartpenter** [comment]
> I guess you don't know what "encouraging" means either, or maybe you don't understand what is being said in the message. Regardless I'm not going to waist my time trying to explain it to your.

No further explanation is needed. It has been provided well enough already.

**Comment by ppalashturov** [comment]
@TheCartpenter please stop spam me. I close PR. 
Best regards.

**Pull request closed without merging**
