### PR TITLE
Fix missing language load in function send

### PR DESCRIPTION
**Pull request by DiV666**
When sending a voucher from the administration, the translation key appears:

image

### CODE REVIEW

**Comment by danielkerr** [comment]
i think the issue is with your translation not being complete!

**Comment by DiV666** [comment]
This happens with version 3.0.2.0 just installed, without languages, extensions or themes:
image

**Comment by danielkerr** [comment]
try it from  the masterbanch

**Comment by DiV666** [comment]
Sorry, in masterbranch (3.1.0.0b) is fixed:

image

**Pull request closed without merging**
