### PR TITLE
Store model proxy in registry

### PR DESCRIPTION
**Pull request by stalker780**
Issue is described here
https://github.com/opencart/opencart/issues/13028

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
This change is unneeded. It already uses this logic:

```
if (!$this->registry->has($key)) {
    ....
    $this->registry->set($key, $proxy);
} else {
    throw new \Exception('Error: Could not load model ' . $class . '!');
}

```

**Comment by stalker780** [comment]
@mhcwebdesign I see it. But you can run your own tests
`__construct` method in `model_catalog_product` is executed multiple times on each page. Thus the model is reconstructed on every call from controllers.
Just add echo to `__construct` function and check yourself.

I just propose a fix. Perhaps Daniel can fix this another way. 
As far as I understand he is still implementing ocmod, so there may be more modifications to loaders.

**Comment by stalker780** [comment]
`$this->registry->set($key, $proxy);` stores proxy not a model. Model is still reconstructed on each call from proxy.

**Comment by mhcwebdesign** [comment]
> `$this->registry->set($key, $proxy);` stores proxy not a model. Model is still reconstructed on each call from proxy.

May be the issue could be cause by line 140:

`    $model = new $class($this->registry);
`

?

**Comment by stalker780** [comment]
@danielkerr not fixed.
Here is an example with latest master.

model_catalog_product is still reconstructed on every call of it's methods

`$this->model_catalog_product->getTotalProducts()`
`$this->model_catalog_product->getProducts()`

image

**Comment by stalker780** [comment]
Just add this method to any model or controller and you will see how many times it is reconstructed

```
public function __construct(\Opencart\System\Engine\Registry $registry) {
	echo '<pre>'.__METHOD__.' ['.__LINE__.']: '; print_r('constructed'); echo '</pre>';
	echo '<pre>'.__METHOD__.' ['.__LINE__.']: '; print_r(debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS)); echo '</pre>';
	$this->registry = $registry;
}
```

**Comment by stalker780** [comment]
https://github.com/opencart/opencart/blob/95810405c98f77cec9530fd0c600bad7e4f42b48/upload/system/engine/loader.php#L150

If I change `static` with `global` it works fine and model is constructed only once:

`global $model;`

**Comment by danielkerr** [comment]
but ur right it needs fixing.

**Pull request closed without merging**
