### PR TITLE
[3.0.x.x] Updated pgsql.php

### PR DESCRIPTION
**Pull request by condor2**
https://github.com/opencart/opencart/pull/13449/files

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
Is anyone actually using PostgreSQL? Certainly for master branch and the opencart-3 repository it won't work and should be removed, especially after the many unneeded cosmetic changes to the various model classes.

**Comment by condor2** [comment]
@mhcwebdesign Hmm..I don't know. Never used or tested :)
MySQLi is ok for me :)

**Comment by AJenbo** [comment]
@mhcwebdesign by cosmetic changes are you referring the addition of backticks to the sql statements?

https://wiki.postgresql.org/wiki/Things_to_find_out_about_when_moving_from_MySQL_to_PostgreSQL

I do agree that this has probably broken the queries on most databases that are not MySQL variants, and should probably be revered.

**Comment by mhcwebdesign** [comment]
> @mhcwebdesign by cosmetic changes are you referring the addition of backticks to the sql statements?
> 
> https://wiki.postgresql.org/wiki/Things_to_find_out_about_when_moving_from_MySQL_to_PostgreSQL
> 
> I do agree that this has probably broken the queries on most databases that are not MySQL variants, and should probably be revered.
> 
> Or are there other things you think would also cause issues?

Yes, it's mostly about the backticks. As far as I know, no  intensive testing for PostgreSQL was ever done .

**Comment by AJenbo** [comment]
> As far as I know, no intensive testing for PostgreSQL was ever done 

Looks more like zero testing was done, the queries are completely broken for PostgreSQL. Most appears to have been done here: https://github.com/opencart/opencart/commit/3f717942eee0e373145e53b1bbbe851fc05acd5d

This means that since OC 4.0 PostgreSQL has been completely broken. The same is also true for [opencart-3](https://github.com/opencart/opencart-3/commit/885f4897eaca453cc91c8b9c521aca8a958c337f). But so is 3.0.x.x: https://github.com/opencart/opencart/commit/623980369db371f61918bf45871faee7965a1e31. It looks like the only working option for someone on PostgreSQL would be [Opencart_23xx](https://github.com/condor2/Opencart_23xx)

**Comment by condor2** [comment]
@AJenbo If you refer to backward escaped. I have added also on my repo....on admin side

**Comment by AJenbo** [comment]
Ok, then I guess that OC on PostgreSQL is just dead.

**Comment by mhcwebdesign** [comment]
That's why I suggested a while ago to remove the system/library/db/pgsql.php altogether, see https://github.com/opencart/opencart/issues/12869

**Pull request merged**
