### PR TITLE
[3.0.x.x_Maintenance] Typo 'affliate' customer

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
I don't see that line on the master branch in admin/model/customer/customer.php file.

**Comment by condor2** [comment]
This is for 3.0.x.x (3.0.3.8) not Master Branch

**Comment by condor2** [comment]
@WebkulOpencart  merge this commit.

**Comment by WebkulOpencart** [comment]
@condor2  you have to change the same in the controller function as well so I am closing this PR and created a new PR for the same. [https://github.com/opencart/opencart/pull/9750](https://github.com/opencart/opencart/pull/9750)

**Pull request closed without merging**
