### PR TITLE
Update file.php

### PR DESCRIPTION
**Pull request by PhamToan**
sometime it is deleted by another process. We need to check file exist before deleting

### CODE REVIEW

**Comment by ADDCreative** [comment]
If the file is deleted by another process then using is_file will probably not help as it take its information from the [file status cache](https://www.php.net/manual/en/function.clearstatcache.php). There is also the chance that the other process deletes the file after the is_file.

**Comment by PhamToan** [comment]
> If the file is deleted by another process then using is_file will probably not help as it take its information from the [file status cache](https://www.php.net/manual/en/function.clearstatcache.php). There is also the chance that the other process deletes the file after the is_file.

I have used this way for fixing on my site. it is really help ... the time shows on error less (5 days without error since from fixed)

**Review by PhamToan — COMMENTED** [review]
better function

**Comment by ADDCreative** [comment]
I would of thought the original is_file would be better. It will be slightly faster and will not match if a directory. It would also match the checks in the read and destroy methods.

**Comment by TheCartpenter** [comment]
is_file lookups are more persistent in the core than file_exists . I am not sure how more relevant it would be to track a file with file_exists as opposed with is_file function in this case.

**Comment by danielkerr** [comment]
already added

**Pull request closed without merging**
