### PR TITLE
Update order_info.twig

### PR DESCRIPTION
**Pull request by Samdz19**
hide disabled currencies

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Not sure if this is ideal, since we'd still need to know whenever they are disabled rather than hiding that information.

**Comment by Samdz19** [comment]
@TheCartpenter , I mean hide the disabled currencies from the order form in admin, so when you try to add an order or edit it via admin side you will see all the currencies with disable and enable status, so the modification will show only the enable currencies in the dropdown field.

**Comment by TheCartpenter** [comment]
> @TheCartpenter , I mean hide the disabled currencies from the order form in admin, so when you try to add an order or edit it via admin side you will see all the currencies with disable and enable status, so the modification will show only the enable currencies in the dropdown field.

In this case, yes, I did read it right on what you meant.

**Comment by danielkerr** [comment]
stop trying to change how the system works and start on the listed issues.

**Pull request closed without merging**
