### PR TITLE
Replace MyIsam database with InnoDB

### PR DESCRIPTION
**Pull request by tmccaff**
Last one was wrong. This is the new fix. InnoDB is better for
transactions. Therefore, makes sense to change to InnoDB

### CODE REVIEW

**Comment by veksen** [comment]
Won't InnoDB screw up with up with full text search (searching in product description)?

**Comment by Martynas-P** [comment]
Where does OpenCart use Full Text search? As far as I am aware, OpenCart uses LIKE %...% to search in descriptions and titles.

**Comment by tmccaff** [comment]
Yes need to check for this. I have to look more deeply into this. However, this needs to be done asap. It's absolutely critical to move from MyIsam

**Comment by mariosangiorgio** [comment]
I see this patch has not been merged into master and I totally agree with @tmccaff when he says that it's critical to move from MyIsam.

I am currently choosing an what e-commerce software I should use and I would really like to have InnoDB support. What is the current state of InnoDB support in OpenCart?

**Pull request closed without merging**
