### PR TITLE
Added PayPal Checkout extension

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by danielkerr** [comment]
why are u trying to add all this tro the master branch. i dont want 3rd party extension in the master. i have a system that connect to opencart.com

**Comment by TheCartpenter** [comment]
> why are u trying to add all this tro the master branch. i dont want 3rd party extension in the master. i have a system that connect to opencart.com

You did asked before if SagePay Opayo could be fixed but you didn't mentioned for what purpose. As for third-party, since you don't want it integrated, why is it integrated in this branch: https://github.com/opencart/opencart/pull/13491 ? That will simply convince more people to use a previous version rather than an up-to-date branch.

**Comment by mhcwebdesign** [comment]
> You did asked before if SagePay Opayo could be fixed but you didn't mentioned for what purpose. As for third-party, since you don't want it integrated, why is it integrated in this branch: #13491 ? That will simply convince more people to use a previous version rather than an up-to-date branch.

@TheCartpenter : You are referring to the 3.0.x.x branch which always had some common payment methods included. But starting from OpenCart 4, most payment methods are now located in the OpenCart marketplace.

**Comment by TheCartpenter** [comment]
> > You did asked before if SagePay Opayo could be fixed but you didn't mentioned for what purpose. As for third-party, since you don't want it integrated, why is it integrated in this branch: #13491 ? That will simply convince more people to use a previous version rather than an up-to-date branch.
> 
> @TheCartpenter : You are referring to the 3.0.x.x branch which always had some common payment methods included. But starting from OpenCart 4, most payment methods are now located in the OpenCart marketplace.

It still won't prevent the fact that people will be more convinced to use an integrated and maintained third-party extension in the core rather than, not only using the OC Marketplace, but also to use an older version of OC because of that.

**Comment by TheCartpenter** [comment]
> > It still won't prevent the fact that people will be more convinced to use an integrated and maintained third-party extension in the core rather than, not only using the OC Marketplace, but also to use an older version of OC because of that.
> 
> For OC 3.0.x.x I have upgraded the PayPal Integration extension to its latest version 2.2.0 and also did some further bugfixes to it, see #13491. I have it running on a live website, no more issues.

There's still one issue where PayPal Checkout has been merged to an older OC version whereas people are looking to use the latest version. By keeping those integrations on-going, whether extensions are published by the name: 'Opencart' on the OC marketplace and also to distribute third-party extensions on this repository on an older version does not provide a great example in order to use an up-to-date version whether a live site is bug-free based on an older version in this scenario.

**Comment by AJenbo** [comment]
3 of the files are not php 7.4 compatible

**Comment by TheCartpenter** [comment]
> 3 of the files are not php 7.4 compatible

Which commit are you referring to?

**Comment by AJenbo** [comment]
image

https://github.com/opencart/opencart/actions/runs/7464605991/job/20311944346

```
unexpected '|' in upload/extension/opencart/system/library/paypal.php on line 42
unexpected '|' in upload/extension/opencart/admin/controller/payment/paypal.php on line 2130
unexpected '|' in upload/extension/opencart/admin/model/payment/paypal.php on line 199
```

**Comment by TheCartpenter** [comment]
Done with PHPStan. The so many years on how long users may have struggled with these bugs, not only because OC 4 has reverted back to PHP 7.4, but also the fact that it can now be resolved within the hour instead of years.

@danielkerr: It would really be beneficial on this tree to have a repository to test the extensions especially when it comes on behalf of: 'Opencart' as a free extension prior to add it on the Marketplace. This way, users won't have to wait this long in order to use such published extensions in the future.

**Comment by danielkerr** [comment]
can not add to master

**Comment by danielkerr** [comment]
can they be in there own extension?

**Comment by TheCartpenter** [comment]
> can they be in there own extension?

In order to do that, we can redistribute this one on the Marketplace bug-free but, as suggested on the above, starting with a new point of taking initiative to be able to test those extensions to ensure the flexibility of what's being published to the users since it is a worldwide distribution after all which is more than fair to propose as to increase the quality and value of the packages on a lease matter of time.

**Comment by TheCartpenter** [comment]
In other words; to establish a new remediation planning strategy for extensions.

**Comment by mhcwebdesign** [comment]
Who is the author of the PayPal Integration extension?

**Comment by TheCartpenter** [comment]
What we only know is that it's been published under the name of 'Opencart' username from the Marketplace and that ```install.json``` claims it's under: Dreamvention.

**Comment by danielkerr** [comment]
yes dreamvention did paypal

**Comment by danielkerr** [comment]
i think theres a repository

**Comment by TheCartpenter** [comment]
> i think theres a repository

It's his own but it doesn't dignify the fact that it's still published under the name of Opencart on the Marketplace. Should it publish the extension as a third-party, then his own username needs to be used. Otherwise, since this package has been published under the name of Opencart, it only makes sense that this package belongs in the extension/opencart folder of the core.

**Comment by mhcwebdesign** [comment]
Maybe it's this github repository: https://github.com/Dreamvention/paypal ?

**Comment by TheCartpenter** [comment]
> Maybe it's this github repository: https://github.com/Dreamvention/paypal ?

Would be the same for the 3.0.x.x version but it has also been merged for further support.

**Comment by danielkerr** [comment]
we need to link the repositories

**Comment by TheCartpenter** [comment]
> we need to link the repositories

Then, let's do that. OC3 separated with OC4 under their sub-repositories so that lint and PHPStan can scan both repositories separately under the extensions repository altogether.

**Comment by TheCartpenter** [comment]
As for the core repositories, if those can be linked as well, let's do that as well.

**Comment by TheCartpenter** [comment]
Either linked or maintained for the extensions, since all it really takes is for the extension to be uploaded for either versions in order to do the last lookups before the official distributions on the Marketplace. This solution is still cost-effective and can be solved within matter of hours rather than years whether it has to be looked up manually or by automation with Lint and PHPStan.

**Comment by TheCartpenter** [comment]
@danielkerr: Closing this. Aside from the extension branches, we don't need all of this. I will submit a new PR with the new idea that will even save all OC 3 users using the old recurring payments toward the new subscriptions, soon.

**Pull request closed without merging**
