### PR TITLE
Used $order_id instead of $this->request->get - catalog/controller/account/order.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by ADDCreative** [comment]
Parts of this are wrong. You cant replace $order_product_info['order_id'] with $order_product_id.

**Comment by TheCartpenter** [comment]
Ok, the 2nd commit has been deleted now.

**Comment by ADDCreative** [comment]
You are now just proposing deleting the whole file!

**Comment by TheCartpenter** [comment]
Not exactly since the first commit is still there and has not been requested to be deleted on my behalf.

**Comment by ADDCreative** [comment]
All three of your commits are still there and your last commit just deletes upload/catalog/controller/account/order.php.

**Comment by TheCartpenter** [comment]
This one is still working: https://github.com/opencart/opencart/pull/9734/commits/abb7a4f70746346a030744bc24c0865bd1ed4f6d . That's what counts.

**Comment by ADDCreative** [comment]
No it's not, you need to check again and stop wasting everyone's time.

**Pull request closed without merging**
