### PR TITLE
Typo returns_form.twig

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Also found and commit on:

- https://github.com/opencart/opencart/pull/11070/commits/af71d1e016fc28f9fef1c0f31602f9ec2cb065bc
- https://github.com/opencart/opencart/pull/11068/commits/f39eff4aa85ec320db2f07d85be6170c921be279
- https://github.com/opencart/opencart/pull/11067/commits/697c04b94e18ae0e3d0a94dfe1c0b10cae4308ed

**Comment by condor2** [comment]
Looks 2 different things to me

**Comment by condor2** [comment]
First input is added on 
**$this->db->query("INSERT INTO `" . DB_PREFIX . "return`**

And history comment in
**$this->db->query("INSERT INTO `" . DB_PREFIX . "return_history`**

**Comment by TheCartpenter** [comment]
In order to ensure all input-history IDs are used, then this commit would also need to be rectified: https://github.com/opencart/opencart/commit/73b2d963116b57bc5778da77b3e42148465af7c5 .

**Pull request merged**
