### PR TITLE
Many improvements in the template engine and twig

### PR DESCRIPTION
**Pull request by prhost**
Hello,

I made enough improvements and modifications to the engine and twig template, I believe that was pretty cool. When I saw that you put twig I was very happy. I made for the safety of Opencart cloud and extensive maximum possible.

The right would make an interface and implement the engines, to force a default, since both are used in the same way, not because I think it should be in a folder in so `system/instancies` and not within the`library`, and autoload only load the `system/library` folder.

I hope they accept, or at least discuss the pull request.

also solves the problem of issue: https://github.com/opencart/opencart/issues/4652

I'm doing a twig extension especially for Opencart, it will help a lot in the templates.

### CODE REVIEW

**Comment by danielkerr** [comment]
im not going to accept this because coding like this.

public function render($template, $registry) {

**Comment by danielkerr** [comment]
i will finish the twig integration today then we can come up with some solutions to access twigs extension system.

**Comment by prhost** [comment]
Need the registry in the engine to gain access to opencart if you need, in this case I am using the event to modify the twig if necessary, but can be other future needs such as access to settings for example.

**Comment by danielkerr** [comment]
What about adding a DI container?

**Comment by prhost** [comment]
You want to use a design patterns?
https://github.com/domnikl/DesignPatternsPHP/tree/master/Structural/DependencyInjection

**Comment by danielkerr** [comment]
maybe not specifically this implementation.

**Comment by prhost** [comment]
I'll think of something better, needed to change the autoload to support all system folder and not just the library.

**Comment by prhost** [comment]
I changed the issue of registry and created an interface to standardize engines. From a look.

A doubt you intend to launch this modification of the twig and complete convert themes to version 2.3?

**Comment by danielkerr** [comment]
its not worht it

**Comment by prhost** [comment]
because? should not be using events for anything, will eventually become another problem. have to provide events for developers only, and do not use, you have the possibility of leaving the core. as a developer will modify something template engine without modifying the theme event? show me what's wrong in my pull request so that I can improve

**Pull request closed without merging**
