### PR TITLE
Customer account store entry

### PR DESCRIPTION
**Pull request by pemaier**
In multi-store systems it's required to relate the customer account to the right store.

### CODE REVIEW

**Comment by straightlight** [comment]
Idealistically speaking, this commit: https://github.com/opencart/opencart/pull/7562/commits/1459cca7d844cf2910ebf9fcf6b4d11dd8e375cc should contain ```{{ text_default }}``` rather than ```*``` .

**Comment by pemaier** [comment]
That makes sence Yes

-----Original Message-----

**Comment by straightlight** [comment]
This might be considered for the features-pre release.

**Comment by straightlight** [comment]
The third modification for setting: https://github.com/opencart/opencart/pull/7562/commits/d6a7ad26d116a8cb70f366f8a8cd3ddaf5f92ed1 cannot be considered since the master branch already has new modifications on that location where the common/pagination is also being used with $page . You'll have to make updates on this one to consider the idea. 

Please ensure your commits are up-to-date with the changes!

**Pull request merged**
