### PR TITLE
fixed opencart installation bug by console "PHP Notice:  Use of undef…

### PR DESCRIPTION
**Pull request by prabhatkumaroc082**
…ined constant DIR_STORAGE"

### CODE REVIEW

**Comment by straightlight** [comment]
This could only happen if users are using an old version of OC and wants to upgrade to a more recent release. However, line comparison in config.php files should be integrated to see if the some defined constants are missing before applying the upgrade. When so, the required lines should be automatically added  by the install models prior to complete the upgrade.

**Comment by prabhatkumaroc082** [comment]
Hello @straightlight 
Thanks for the response. I am considering this issue in case of fresh OC installation by using the command line so that "DIR_STORAGE" constant is not found. Also, I have listed all steps in this issue #7512

**Comment by straightlight** [comment]
For fresh installs, according to install/cli_install.php file, the DIR_STORAGE is already defined in the string before the config.php and admin/config.php files are being created.

**Comment by straightlight** [comment]
For the upgrade, install/model/upgrade/1009.php file already validates this constant to be added in both config files.

**Comment by prabhatkumaroc082** [comment]
@straightlight 
After considering all of your comments, I want to say that please have a look again at install/cli_install.php file so first, some constants are defined like DIR_APPLICATION, DIR_SYSTEM, etc except DIR_STORAGE and after that startup file is included using require_once() method. Now just go to line 70 of system/startup.php then you will see DIR_STORAGE is being used in if condition which is not defined yet so that it is generating an error.

**Comment by straightlight** [comment]
Correct. Confirmed. system/startup.php file is being loaded in cli_install.php prior to either a fresh installation or upgrade process is being initiated. The DIR_STORAGE may not yet exists for most of the users who are using old OC versions and wants to upgrade to a higher version. Good catch!

**Comment by prabhatkumaroc082** [comment]
Thanks @straightlight

**Comment by prabhatkumaroc082** [comment]
@jeffreyeng-opencart Please look into this.

**Pull request merged**
