### PR TITLE
Datepicker layout

### PR DESCRIPTION
**Pull request by dilipkumardev**
Now We have fixed the issue please check screenshot.
http://i.prntscr.com/cFutUqC9SjSKoeJyR7qOJg.png

### CODE REVIEW

**Comment by dilipkumardev** [comment]
@jeffreyeng-opencart Please look into this.

**Comment by jeffreyeng-opencart** [comment]
You have made CSS update, but what about the min.css?

**Comment by jeffreyeng-opencart** [comment]
The other two PHP files. Anyway to split these as another commitment away from the CSS? I will not merge and commit these together.

**Comment by jeffreyeng-opencart** [comment]
Ignore what I said about split commitment. I just saw your other commitment. Just need a way to remove the PHP files from here or create another commit for the CSS alone.

**Comment by jeffreyeng-opencart** [comment]
@dilipkumardev: Hopefully you have saw my previous message. Could you either do this:

1. Remove the PHP files from here (I have already merged the two PHP files from another committed branch you have created) and keep the CSS file for me to merge.

or 

2. Create a new branch or new commit for the CSS file.

Please let me know.

**Comment by dilipkumardev** [comment]
@jeffreyeng-opencart I have created new PR for the same. Please check here:- [https://github.com/opencart/opencart/pull/7668](https://github.com/opencart/opencart/pull/7668)

**Pull request closed without merging**
