### PR TITLE
Update dashboard.php

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by batumibiz** [comment]
In order to add one space, did you create a separate PR?

**Comment by TheCartpenter** [comment]
> In order to add one space, did you create a separate PR?

Not required to add a separate PR. Once the code changed has been merged to the project, all we really need is the sync button from our forked repositories to ensure the changes are up-to-date.

**Comment by mhcwebdesign** [comment]
> In order to add one space, did you create a separate PR?

He refuses to use a proper Git client, making life miserable for all the other developers/contributors.

**Comment by TheCartpenter** [comment]
> > In order to add one space, did you create a separate PR?
> 
> He refuses to use a proper Git client, making life miserable for all the other developers/contributors.

https://github.com/opencart/opencart/pull/12843#issuecomment-1784198338

**Comment by batumibiz** [comment]
> He refuses to use a proper Git client, making life miserable for all the other developers/contributors.

It seems to me that he does not use any GIT client at all and edits the code through the WEB interface from the browser.  
GitHub WEB interface has exactly this behavior: for each individual file when saved, it creates a separate PR.  
We need to create a collective complaint to Daniel, otherwise this disgrace will not stop.

**Pull request merged**
