### PR TITLE
[3.0.x.x_Maintenance] ISO-codes updated

### PR DESCRIPTION
**Pull request by condor2**
https://github.com/opencart/opencart/commits/master/upload

### CODE REVIEW

**Comment by osworx** [comment]
Quite funny that you make this PR (ISO-Codes).
I would suggest that you check next time if I am ready with the work and don't steal the code without any comment.

**Comment by condor2** [comment]
In the comment I added master branch history link, where people can see who made the pull requests..

**Comment by osworx** [comment]
> 
> 
> In the comment I added master branch history link, where people can see who made the pull requests..

Maybe I am blind, but what shall this mean?
The PR is made by you, but from WHOM you have the new code??
Man you're so poor.

As written, the new ISO-Codes and changes are from my repo.
And I am still not ready with that!
Better you close the whole PR because it's only a small part of the whole thing.

**Comment by condor2** [comment]
The PR was closed 2 hours ago....

In the comment I posted this link
https://github.com/opencart/opencart/commits/master/upload
and not every commit.

**Pull request closed without merging**
