### PR TITLE
Completed the TD alignments in admin

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
What exactly are your trying to accomplish here? These are no bugfixes from what I can see!

**Comment by mhcwebdesign** [comment]
This was perfectly fine, what exactly are you trying to accomplish? Can't we focus on genuine bugfixes?

**Comment by mhcwebdesign** [comment]
Your daily weird changes are a good reason for extensions developers to avoid OCmod-based changes and to stay away from the master branch for the time being.

**Comment by TheCartpenter** [comment]
> Your daily weird changes are a good reason for extensions developers to avoid OCmod-based changes and to stay away from the master branch for the time being.

OCMod is not out, yet. It is rather the best time to match those codes as much as we can so that extension developers can dig up the codes with ease.

**Pull request merged**
