### PR TITLE
Update attribute_group.php

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by chulcha** [comment]
It is correct to write with escaping, because names can come from anywhere and anything can be there.

```
	$sort_data = [
			'`agd`.`name`', 
			'`ag`.`sort_order`'
		];
```
Is not it?

Or have a function for such escaping.

**Comment by TheCartpenter** [comment]
> It is correct to write with escaping, because names can come from anywhere and anything can be there.
> 
> ```
> 	$sort_data = [
> 			'`agd`.`name`', 
> 			'`ag`.`sort_order`'
> 		];
> ```
> 
> Is not it?
> 
> Or have a function for such escaping.

No need of a function. It will only make things worst.

**Comment by danielkerr** [comment]
wWTF! NO!

**Comment by chulcha** [comment]
> > It is correct to write with escaping, because names can come from anywhere and anything can be there.
> > ```
> > 	$sort_data = [
> > 			'`agd`.`name`', 
> > 			'`ag`.`sort_order`'
> > 		];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is not it?
> > Or have a function for such escaping.
> 
> No need of a function. It will only make things worst.

Why?
Are you escaping everything?

**Comment by TheCartpenter** [comment]
> > > It is correct to write with escaping, because names can come from anywhere and anything can be there.
> > > ```
> > > 	$sort_data = [
> > > 			'`agd`.`name`', 
> > > 			'`ag`.`sort_order`'
> > > 		];
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Is not it?
> > > Or have a function for such escaping.
> > 
> > 
> > No need of a function. It will only make things worst.
> 
> Why? Are you escaping everything?

Just what's needed.

**Comment by chulcha** [comment]
> > > > It is correct to write with escaping, because names can come from anywhere and anything can be there.
> > > > ```
> > > > 	$sort_data = [
> > > > 			'`agd`.`name`', 
> > > > 			'`ag`.`sort_order`'
> > > > 		];
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Is not it?
> > > > Or have a function for such escaping.
> > > 
> > > 
> > > No need of a function. It will only make things worst.
> > 
> > 
> > Why? Are you escaping everything?
> 
> Just what's needed.

No problem, with your attitude you'll need it tomorrow.

**Comment by TheCartpenter** [comment]
> > > > > It is correct to write with escaping, because names can come from anywhere and anything can be there.
> > > > > ```
> > > > > 	$sort_data = [
> > > > > 			'`agd`.`name`', 
> > > > > 			'`ag`.`sort_order`'
> > > > > 		];
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Is not it?
> > > > > Or have a function for such escaping.
> > > > 
> > > > 
> > > > No need of a function. It will only make things worst.
> > > 
> > > 
> > > Why? Are you escaping everything?
> > 
> > 
> > Just what's needed.
> 
> No problem, with your attitude you'll need it tomorrow.

It used to work yesterday, it's still working today and those arrays without escaping will still work tomorrow.

**Pull request merged**
