### PR TITLE
Disable Default Language in SEO url

### PR DESCRIPTION
**Pull request by ppalashturov**
[Disable Default Language in SEO url](https://github.com/opencart/opencart/commit/86effa4aaa2376288dc24604b2476cbe97d19870)

### CODE REVIEW

**Comment by ppalashturov** [comment]
@danielkerr why?

**Comment by ppalashturov** [comment]
@danielkerr @AJenbo Why? How hide default language in SEO URL?

**Comment by AJenbo** [comment]
I don't know

**Comment by danielkerr** [comment]
i think will be better not forcing seo urls or making them auto generate from the titles.

**Pull request closed without merging**
