### PR TITLE
Spaced model calls - extension/opencart/catalog/controller/module/special.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by eka7a** [comment]
Please submit with a single commit for the same changes. Sending new requests for each file complicates merge. You are making it harder for us to take the time for this as requests require more time to check. And after then your requests timeout.

**Comment by TheCartpenter** [comment]
You don't have to merge them all at the same time. Besides, Github website only provides the option to upload from one file at-a-time.

**Comment by eka7a** [comment]
There are many free programs available for this.
https://desktop.github.com
https://www.sublimemerge.com
https://tortoisegit.org
https://git-scm.com/downloads

**Comment by TheCartpenter** [comment]
@eka7a: You know you could provide as many tools as you'd like to avoid doing the big job on this repository. However, if there's one thing quite noticeable on the pull requests is the mount of commit awaiting to get merged aside from mine regardless of the tools being used.

The reason why @danielkerr assigned you those permissions is for you to be able to merge as many pull requests for the people dedicating their time to provide their codes and functionality where, some of them, might be about improving the codes on the platform as well as for the users to be able to use a more flexible platform in the future. One thing is for sure is I do dedicate my time on the project. While you're bragging around about the ways a pull request should be submitted, Github website does not require any software to be used nor is there any regulations that enforces the use of a software politically.

With that being said, if your only objective is to tell the people that third party tools should be used to create and merge pull requests, then with all certainty, the complaint you're posting about is only about one thing; that you ain't either up to the task to merge all the required pull requests or either you're not fast enough for me since, for me - without using these tools, I have been able to post all these commits overall since, either you like it or not, the reality is that the Projects tab on this repository is getting bigger and will only get bigger one day after the next with new objectives by @danielkerr. As long as you don't get that, you'll keep falling behind schedule and keep every contributor who posted their sight of view in the past on this repository.

It's up to you at this point to forseen how longer you want to keep these people waiting, including me, to fulfill these tasks. Granted, Github Opencart is opensource which is exactly my point; it's opensource and Github allows to use the website to submit opensource codes. It's simple as that buddy.

**Comment by eka7a** [comment]
There is no paid employee here. Everyone is trying to help in their free time and it does not concern me how much time you spend here! Time is your time. What you are doing is nothing but preventing the efficient use of the time allocated for here. You do not understand or do not want to understand this.

I show you the easy way, you insist on going the hard way.

**Comment by TheCartpenter** [comment]
The only thing you were able to show in here is how fast you're able to close a commit without closure notes. As proof, it shows right on the above.

**Pull request closed without merging**
