### PR TITLE
Fixed SQL abbreviation typo and pushed space - upload/system/library/db.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Review by cgcmart — COMMENTED** [review]
line 41, line 52, line 54

**Comment by TheCartpenter** [comment]
@cgcmart: What's wrong with these lines?

**Comment by cgcmart** [comment]
file source comparison: you corrected line 41, but left line 52 and line 54.
db

**Comment by TheCartpenter** [comment]
Based on other system/library files, those spaces are identical as well after the variable types. Depth's on 2 spaces.

**Pull request merged**
