### PR TITLE
Delete Deprecated

### PR DESCRIPTION
**Pull request by haxcop**
Update Delete() for del as is deprecated in redis latest version

### CODE REVIEW

**Comment by straightlight** [comment]
It is conceivable to say that the system/library/cache.php file convention method names could be confronted by its namespace cache library files in the cache subfolder ...

Good catch!

**Comment by haxcop** [comment]
Still exist on latest Release - Please merge or Update accordingly

**Comment by straightlight** [comment]
What latest release are you referring too? The master branch remains the same version as we speak ...

**Comment by haxcop** [comment]
> What latest release are you referring too? The master branch remains the same version as we speak ...

Hi, If you into upload/system/library/cache/redis.php in the master branch you would notice delete remains instead of del 

I tested the newest release 3.0.3 and still exist the same issue at least with Redis and the two pull request I submitted

**Comment by straightlight** [comment]
OC releases from opencart.com do not reflect the changes being done on the master branch.

**Comment by haxcop** [comment]
Well, then I don't know where you or they commit and apply this change because is nowhere to be found other than here...

**Comment by danielkerr** [comment]
Will do a new release

**Comment by straightlight** [comment]
So far, no problematic issues nor conflict has been reported by keeping the same conventional name. Therefore, this commit will now be closed.

**Comment by haxcop** [comment]
Looks like you didn't test this before closing... if anybody is looking to solve an error due to a deprecated call here's the answer. Redis 5 is no longer accepting the structure you guys have here setup...

**Comment by ADDCreative** [comment]
@straightlight This will need changing. PhpRedis delete method is deprecated. See: https://github.com/phpredis/phpredis/#del-delete-unlink

> Note: delete is an alias for del and will be removed in future versions of phpredis.

**Comment by ADDCreative** [comment]
Been fixed by https://github.com/opencart/opencart/pull/8048.

**Comment by danielkerr** [comment]
already been added.

**Pull request closed without merging**
