### PR TITLE
Added PHP 8.2 support

### PR DESCRIPTION
**Pull request by mhcwebdesign**
Update of several classes so as to solve errors about deprecated creation of dynamic properties.

### CODE REVIEW

**Comment by TheCartpenter** [comment]
By using namespaces to declare instanced variables is not good practice. Besides, if one states that modifying each constructor is better than modifying the proxy class (which I still don't agree on), then adding namespaces on instanced variables wouldn't provide better experience especially for extension developers.

**Comment by mhcwebdesign** [comment]
> i will do the fixes myself

No problem. But at least take a look at it, we need support for PHP 8.2 as soon as possible.

**Comment by danielkerr** [comment]
> By using namespaces to declare instanced variables is not good practice. Besides, if one states that modifying each constructor is better than modifying the proxy class (which I still don't agree on), then adding namespaces on instanced variables wouldn't provide better experience especially for extension developers.

agreed

**Comment by mhcwebdesign** [comment]
I think using **object** as a type is very generic, though it works, too.

Anyway, please add all the needed fixes for PHP 8.2 support, you still missed out on a few.

It still complains about these:

Opencart\System\Library\Mail::$parameter
Opencart\System\Library\Mail::$smtp_hostname
Opencart\System\Library\Mail::$smtp_username
Opencart\System\Library\Mail::$smtp_password
Opencart\System\Library\Mail::$smtp_port
Opencart\System\Library\Mail::$smtp_timeout

with **Creation of dynamic property deprecated** errors, caused by the lines 135 to 140 at

catalog/controller/information/contact.php

Also, the call to the **str_split** function needs to be fixed in system/library/mail/smtp.php

For a complete list, see my pull request.

**Comment by danielkerr** [comment]
U block the ability to interchange the objects when u force namespaces

**Pull request closed without merging**
