### PR TITLE
Fix send mail

### PR DESCRIPTION
**Pull request by Gendrop**
Message denied for spoofing attempt via SMTP Auth (From address: John Doe <john.doe@gmail.com> IP: xxx.xxx.xxx.xxx AuthenticatedID: store@mail.com Account owner: username)

The SMTP it’s blocking all emails because the FROM email, it’s different from the Authenticated one (<john.doe@gmail.com> != <store@mail.com> )

Reply-To header remains with the email address of the sender, so you can reply directly.

### CODE REVIEW

**Comment by danielkerr** [comment]
this might work only for you. it works fine for me on gmail

**Comment by Gendrop** [comment]
It's not a fix only for me, it's a fix for all the new SMTP with spoofing validations.
The sender email MUST be the same authenticated email.

**Comment by ADDCreative** [comment]
@Gendrop The smtp_username is not always a valid email address. So your suggested change could cause problems for some set ups.

**Comment by Gendrop** [comment]
@ADDCreative, that make sense. Let me figure a fix without messing with other configurations

**Pull request closed without merging**
