### PR TITLE
Facebook Share Meta tag add

### PR DESCRIPTION
**Pull request by JesseOC**
1. Add the meta tag on header
2. Setup set / get function in library/document
3. Product, information add the function to get the shared image, page title, URL, description for Facebook share, tested and works normally

### CODE REVIEW

**Comment by danijelGombac** [comment]
There is an error in 

`return $this->$url;`

should be 

`return $this->url;`

**Comment by JesseOC** [comment]
yes, forgot to fixed on submitted file, changed, thanks!

**Comment by pcmanik** [comment]
og:type for product should be product and not article.

**Comment by agatha65** [comment]
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=22963

**Comment by JesseOC** [comment]
yes, it has already been updated, thanks for the comment and feedback

**Pull request merged**
