### PR TITLE
Update search.tpl

### PR DESCRIPTION
**Pull request by p0v1n0m**
"sub_category" not cleared without "category_id", only disabled.

1ea566ec45514b7a9d04a3ca21bd7d58

### CODE REVIEW

**Comment by danielkerr** [comment]
you didnt finish the changes before commiting on your last commit. there where missing language files!

**Comment by p0v1n0m** [comment]
In settings? I added them several times. Other commits them cleared.

**Comment by p0v1n0m** [comment]
Why this not?

**Comment by p0v1n0m** [comment]
1. I added languages [searches](https://github.com/opencart/opencart/pull/4556/files#diff-d028a97e640f4531dcdbda9c725483e7) and [setting](https://github.com/opencart/opencart/pull/4554/files#diff-5a0f5c4ba382e5e1f255313cf0e8023b) in the first commit.
2. I again added languages for [searches](https://github.com/opencart/opencart/pull/4572/files#diff-d028a97e640f4531dcdbda9c725483e7) and [setting](https://github.com/opencart/opencart/pull/4561/files#diff-5a0f5c4ba382e5e1f255313cf0e8023b).
3. To avoid this, there are [rules](https://github.com/opencart/opencart/wiki/Creating-a-pull-request), I follow them. What claims to me? This my help for community, if it is not needed - tell me.
P.S. Why this commit rejected? This is useful changes.

**Pull request closed without merging**
