### PR TITLE
Update comment.php

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
Buttons (plural), but Heading, Text, Entry (singular)?

What's that all about. Why not focus on actual bugfixes? And when dealing with function/method descriptions use a tool like PHPDoc and run it for all the files in one go.

**Comment by TheCartpenter** [comment]
> Buttons (plural), but Heading, Text, Entry (singular)?
> 
> What's that all about. Why not focus on actual bugfixes? And when dealing with function/method descriptions use a tool like PHPDoc and run it for all the files in one go.

Not a bugfix commit: https://github.com/opencart/opencart/pull/13101 . Yet, no replies about it either. Therefore, it just proves another point that Pull Requests on Github aren't just meant for bugfixes but rather to submit proposals.

**Comment by TheCartpenter** [comment]
As for the heading, there's only one heading title per language file, therefore, does not require to be plurial.

**Comment by pemaier** [comment]
@TheCartpenter ... sorry the pr #13101 from me is based on the following issue and not only just for fun.
https://github.com/opencart/opencart.github.io/issues/327

**Comment by TheCartpenter** [comment]
> @TheCartpenter ... sorry the pr #13101 from me is based on the following issue and not only just for fun. [opencart/opencart.github.io#327](https://github.com/opencart/opencart.github.io/issues/327)

One thing's for sure, people using this platform does have the same habits to play games with.

**Pull request merged**
