### PR TITLE
fixed insecure randomness

### PR DESCRIPTION
**Pull request by wr3nch0x1**
fixed insecure randomness

### CODE REVIEW

**Comment by TheCartpenter** [comment]
A bit questionable on why the token() helper function is rather not used for this ...

**Comment by wr3nch0x1** [comment]
You can use that too, if you find it more suitable :)

You can use anything except rand()
<http://us.php.net/manual/en/function.rand.php>, srand()
<http://us.php.net/manual/en/function.srand.php>, mt_rand()
<http://us.php.net/manual/en/function.mt-rand.php>, mt_srand()
<http://us.php.net/manual/en/function.mt-srand.php>

**Comment by ADDCreative** [comment]
Don't forget this one. Probably more important.
https://github.com/opencart/opencart/blob/4cfcccf58b2b83f0f8554fa184580c8a904f3faf/upload/catalog/model/tool/upload.php#L5

**Comment by wr3nch0x1** [comment]
Yes. I have few more instances. Please confirm the pull request so that I
can push remaining thanks!

**Comment by wr3nch0x1** [comment]
If this patch is satisfactory for you, can I push remainings with the same?

**Comment by TheCartpenter** [comment]
The user_token would then need to be reviewed as well since it uses the same algorithm as the uploads.

**Comment by wr3nch0x1** [comment]
Can you please confirm it here?
https://www.huntr.dev/bounties/1625139296034-opencart/opencart/

**Comment by danielkerr** [comment]
added manually

**Pull request closed without merging**
