### PR TITLE
[3.0.x.x] Duplicated keys for array - admin config system

### PR DESCRIPTION
**Pull request by condor2**
I think has same effect as before.

### CODE REVIEW

**Comment by condor2** [comment]
As @TheCartpenter  changed in (https://github.com/opencart/opencart-3/blob/main/upload/system/config/admin.php#L51)

**Comment by mhcwebdesign** [comment]
I think this is wrong. The admin/controller/event/language.php actually uses a view/before event:

```
	public function index(&$route, &$args) {
		foreach ($this->language->all() as $key => $value) {
			if (!isset($args[$key])) {
				$args[$key] = $value;
			}
		}
	}

```

**Comment by condor2** [comment]
Yes....but duplicated keys

	'view/*/before' => array(
		999  => 'event/language',
		1000 => 'event/theme'
	),
	'view/*/before' => array(
		'event/language'
	)

**Comment by mhcwebdesign** [comment]
I'll look into it tomorrow.

**Comment by mhcwebdesign** [comment]
I think it needs to be like this for the system/config/admin.php :

```
....
// Action Events
$_['action_event'] = array(
	'controller/*/before' => array(
		'event/language/before'
	),
	'controller/*/after' => array(
		'event/language/after'
	),
	'view/*/before' => array(
		999  => 'event/language',
		1000 => 'event/theme'
	)
);
```

And the admin/controller/event/language.php needs this :

```
	.....
	public function index(&$route, &$args, &$template_code='') {
		foreach ($this->language->all() as $key => $value) {
			if (!isset($args[$key])) {
				$args[$key] = $value;
			}
		}
	}

```

Need to do some testing tomorrow.

**Comment by condor2** [comment]
@mhcwebdesign You have tested?

**Comment by mhcwebdesign** [comment]
> @mhcwebdesign You have tested?

I have tested it, and added the needed change to the 3.0.x.x .

**Pull request closed without merging**
