### PR TITLE
Update featured.php

### LINKED ISSUE #9761: Warning message printed when no featured products.
How to reproduce:
- Fresh setup with sample data.
- Remove all the sample products and categories from the admin
- Load the home page.

Warning: foreach() argument must be of type array|object, null given.
___/extension/opencart/catalog/controller/module/featured.php line 23.

It may be fixed by adding a product, and I doubt if it is worth mentioning as an issue.

### PR DESCRIPTION
**Pull request by anytizer**
Initiate $products variable. Fixes #9761.

### CODE REVIEW

**Review by anytizer — COMMENTED** [review]
View Minimum Order Quantity in products admin area - list view.

**Comment by anytizer** [comment]
Increase the number of paginated items.

**Comment by eka7a** [comment]
Hi @anytizer, There are files (636) with lots of changes. Review and resubmit your request.

**Comment by anytizer** [comment]
1. Composer update -- caused large file updates.
2. Adding MOQ column in product listing in admin.
3. Increase the number of paginated items from 10 to 100.
4. Some changes in .gitignore file.
5. Add .htaccess with directory listing disabled.

**Review by anytizer — COMMENTED** [review]
Edit: I will submit tiny changes at once.

**Pull request closed without merging**
