### PR TITLE
[Maintenance] - Terrible code structure - admin/model/extension/payment/amazon_login_pay.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
WTH designed this controller ? !

**Comment by condor2** [comment]
> WTH designed this controller ? !

Developers :))

**Comment by TheCartpenter** [comment]
> > WTH designed this controller ? !
> 
> Developers :))

It is to ask if somebody's really sure about that on that one ...

**Comment by TheCartpenter** [comment]
Closing. Resolved on opencart-3 repository.

**Pull request closed without merging**
