### PR TITLE
Added warning JSON key - admin/controller/extension/report.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by osworx** [comment]
Extremely boring what you are doing here!
As already others said, if you do not know how to handle Github and a single pull request, let it.

**Comment by juliocesar757** [comment]
Please, stop.

**Comment by stalker780** [comment]
I have created personal filter for Carpenter in gmail. Delete at once.
This is a first time I see such a spammer on github.

**Comment by TheCartpenter** [comment]
JSON keys have now been added in the Master Branch. Closing commit.

**Pull request closed without merging**
