### PR TITLE
Added flter_validate_float validation - admin/controller/sale/voucher.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by ADDCreative** [comment]
This is wrong. You shouldn't allow negative or zero vouchers.

**Comment by TheCartpenter** [comment]
Ok, fixed.

**Comment by ADDCreative** [comment]
Still wrong. You shouldn't allow negative.

**Comment by TheCartpenter** [comment]
Fixed it with this solution: https://www.php.net/manual/en/filter.filters.validate.php#116924 .

**Comment by TheCartpenter** [comment]
Closing. May not need this one.

**Pull request closed without merging**
