### PR TITLE
Correct various generic object types to there actual native types

### PR DESCRIPTION
**Pull request by AJenbo**

### CODE REVIEW

**Comment by danielkerr** [comment]
does this not restrict interoperability?

**Comment by AJenbo** [comment]
Not as long as they extend the class. It might be better to instead provide interfaces to assure that modifications for fill the expectations without needing to overwrite the parent.

**Comment by danielkerr** [comment]
I don't like interfaces. Must be a better way to describe a class

**Comment by AJenbo** [comment]
That's like saying you don't like legs for walking. I think the only other option is abstract classes. But one does not preclude the other.

**Comment by danielkerr** [comment]
do more testing next time!

**Comment by AJenbo** [comment]
I would but the PHPUnit setup was deleted around the time of OC4 so I will have to set something up from scratch at some point.

**Pull request merged**
