### PR TITLE
PHP 8.x support for 3.0.x.x_Maintenance branch

### PR DESCRIPTION
**Pull request by mhcwebdesign**
This pull request is to add PHP8.x-support for the **3.0.x.x_Maintenance** branch.

It includes minor changes to the following PHP files:

upload/admin/model/dashboard/extension/sale.php
upload/catalog/controller/startup/startup.php
upload/catalog/model/catalog/product.php
upload/system/library/db/mysqli.php
upload/system/library/session/db.php
composer.json
composer.lock

And it also includes an update to the current versions of the **upload/system/storage/vendor** folders and files (too many to be listed here), which I did via composer. The most important one of these is the usage of the latest Twig 3.3.8. And the addition of some formerly corrupted or missing vendor sub-folders for e.g. 'klarna/rco_rest' or 'cardinity/cardinity-sdk-php' etc.

### CODE REVIEW

**Comment by ADDCreative** [comment]
With the composer updates. Updating braintree/braintree_php breaks the extension. So maybe best to leave at 3.40 for now. A deprecated message in one of the test files (assuming that is the only issue) is only minor compared to the other issues. The same might go for the other payment SDKs.

It may be best to just update Twig for now, until the others can be tested and updated individually. There are probably a few PHP 8 issues with the payment extensions anyway.

react/promise isn't needed. It will be included if one of the others need it. php could do with being 7.3 to match startup.php.

**Comment by mhcwebdesign** [comment]
@AddCreative: Thanks for looking into it. I'll go through the composer stuff again when I have time.

As regards **react/promise**: You are right, it's not required by OpenCart as such, so could be removed from the 'composer.json'. It will still show up in the 'system/storage/vendor' folder from what I can see:

composer why react/promise
guzzlehttp/guzzle  5.3.4                    requires  react/promise (^2.2)

composer why guzzlehttp/guzzle
cardinity/cardinity-sdk-php  v1.0.3  requires  guzzlehttp/guzzle (~5.1)        
guzzlehttp/oauth-subscriber  0.2.0   requires  guzzlehttp/guzzle (~4.0|~5.0)   
klarna/kco_rest              v2.2.0  requires  guzzlehttp/guzzle (>=4.2,<6.0)

**Comment by mhcwebdesign** [comment]
I can also see that some of the files on github for e.g. the tagged releases 3.0.3.8, 3.0.3.7, 3.0.3.6, or the 3.0.x.x_Maintenance branch are currently missing, somewhere along the time the github repository got corrupted. 

See https://github.com/opencart/opencart/issues/10462 for more details.

**Comment by mhcwebdesign** [comment]
I have now updated the vendor folder at https://github.com/mhcwebdesign/opencart-php8/tree/3.0.x.x_Maintenance/upload/system/storage/vendor . For this, I completely deleted the vendor folder first, then ran a composer install, then updated the twig/twig to its latest version, then committed the changes to https://github.com/mhcwebdesign/opencart-php8/

I'll create a new pull request for 3.0.x.x_Maintenance branch.

**Pull request closed without merging**
