### PR TITLE
Directories

### PR DESCRIPTION
**Pull request by tblanchard**
I have had a lot of problems deploying opencart to cloud services out of git because it fails to create certain directories before trying to write files to them.  These changes fix that problem.

### CODE REVIEW

**Comment by danielkerr** [comment]
im not going to go into the long list of reason why you should not have the system creating directories on the fly if they dont exist.

**Comment by tblanchard** [comment]
It already does it - cache directories etc....

And then fails when it actually matters.

I suppose you are not interested in opencart working on cloud deployments.

**Comment by danielkerr** [comment]
already have it working on a cloud deployment.

the directories are already there so no need to create them.

sees like you have done this pull request to for your own projects not any one elses. also if u built a cloud system that require these directories t be built on the fly then you have not set it up properly!

stop wasting m time! this is an issue only for what ever you have built and not opencart! pull this crap again u will be blocked from posting issues.

**Comment by tblanchard** [comment]
Wow. You're a prick. Go suck an egg you miserable cunt. At no time did I do anything to deserve that level of hostility now go fuck yourself

**Comment by danielkerr** [comment]
your a prick for doing a pull request for somthing you want added to the project that nobody wants and would cause issues if config directories got messed up!

use you brain! i use my time to fix issues and add features. it should not be wasted!

**Pull request closed without merging**
