### PR TITLE
Update catalog.php

### PR DESCRIPTION
**Pull request by PhamToan**
need to load Language before loading SEO

### CODE REVIEW

**Comment by chulcha** [comment]
SEOURL  makes it possible to get language_id

**Comment by TheCartpenter** [comment]
The startup/language controller was recently moved down on the MB. I am not sure why it would be suggested to move it back up.

**Comment by PhamToan** [comment]
> The startup/language controller was recently moved down on the MB. I am not sure why it would be suggested to move it back up.

SEO URL builds with language_id, we need to load language first, I have submitted another merger in the past. but now it is back

**Comment by TheCartpenter** [comment]
I don't see the language ID in the SEO URL startup file: https://github.com/opencart/opencart/blob/master/upload/catalog/controller/startup/seo_url.php .

**Comment by TheCartpenter** [comment]
@danielkerr: Found it. It is stored in the design/seo_url model. It queries the store_id and the language_id .

**Comment by danielkerr** [comment]
SEO URL does not require language Id. It works fine in master.

**Comment by PhamToan** [comment]
> SEO URL does not require language Id. It works fine in master.

try with multi languages

**Pull request closed without merging**
