### PR TITLE
Add missing symbol visibility

### PR DESCRIPTION
**Pull request by AJenbo**
This was done using php-cs-fixer's visibility_required rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.

### CODE REVIEW

**Comment by TheCartpenter** [comment]
```public const CACHEDUMP_LIMIT = 9999;```

Any reason why these const should be put public?

**Comment by AJenbo** [comment]
For backwards comparability, previously they would be publicly available and might have been used by mods/extensions/plugins, and it would be best not to break that.
Now that all symbols have had visibility applied we can add a rule that tests that they are set correctly in new code so such mistakes are not made in the future.

**Comment by TheCartpenter** [comment]
Yes, I would agree here that a rule should be set for code structure. In order to achieve this, still, each commits would have to use the same templates - which is totally fine. It's just that not all builders / software uses the same criteria as defined rules.

**Comment by TheCartpenter** [comment]
Should it need a const to be put public for that? It would be more doubtful, since there might be other ways to achieve this from the workflows.

**Comment by AJenbo** [comment]
I have a rule set ready for php-cs-fixer that can be added as soon as thease PRs are evaluated an merged. Then anyone can install that and run it to have there code adjusted automatically.

**Comment by TheCartpenter** [comment]
> I have a rule set ready for php-cs-fixer that can be added as soon as thease PRs are evaluated an merged. Then anyone can install that and run it to have there code adjusted automatically.

Sounds interesting. This might be exactly what is needed in order to submit proposals worldwide especially if it uses the repository's indent settings as opposed to tabs, or different indents, at the beginning of each lines.

**Comment by AJenbo** [comment]
The rules I made are based on PSR12 (with a few adjustments to match the style of OC) + PHP 7.4 modernization. That's how I created the PRs I did today.

But there are still many more rules to evaluate and apply. I was thinking that maybe you would be interested in looking at that, then you can make PRs to make all the code formatted the same and then add the new rule to the configuration.

**Comment by TheCartpenter** [comment]
If we can find out soon enough, that'd be great to give it a try by also assuming it would cover the code structure with opened and closed parentheses along with the rest of each line statements from the code once proposals will be submitted.

**Pull request merged**
