### PR TITLE
Return copied product

### PR DESCRIPTION
**Pull request by stasdrvn**
In this case developers would be able to set an event on this method.

### CODE REVIEW

**Comment by artxneo** [comment]
Good idea!

**Comment by straightlight** [comment]
While this request might be a good idea, the only problematic is while a product may be copied, it does not include the order ID while the sales return feature requires the order ID.

**Comment by stasdrvn** [comment]
May I ask you how do orders connect with the cloned product?

**Comment by straightlight** [comment]
They're not and this is what my previous reply indicates. Which is why, to work with returned products, it requires an order ID.

**Comment by straightlight** [comment]
As confused it may sound to you, just look in the codes and you'll see. admn/model/sale/return.php file for instance.

**Comment by straightlight** [comment]
For the copied product itself, when gathering the new product ID you probably mean, then yes, an event could be created.

**Comment by stasdrvn** [comment]
Majestic!

**Comment by straightlight** [comment]
The returned object from the master branch has been updated since with its own function. Therefore, this commit will now be closed.

**Pull request closed without merging**
