### PR TITLE
Added format_size() helper function - catalog/controller/checkout/shipping_address.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by danielkerr** [comment]
im not doing format size!

**Comment by TheCartpenter** [comment]
The helper function is already in the core as you seem to have already used it in your admin/controller/marketplace/installer.php file. If you're referring to this commit specifically, however, I will simply close it.

**Comment by danielkerr** [comment]
some one added it noty me. and igf they fucked with my installer code its a problem for me.

**Comment by danielkerr** [comment]
im removing it. i should not have avccepted it

**Pull request closed without merging**
