### PR TITLE
Update summernote.js

### PR DESCRIPTION
**Pull request by saifwebberoo**
Padding issue fixed

### CODE REVIEW

**Comment by gob33** [comment]
And also update from 0.5.8 to the latest (0.6.0 ?).
I need the new function "insertText (node, text)" to do at least like the good old CKEditor for moving extensions to OC2.x. This is a necessity.

**Comment by gob33** [comment]
In fact, Summernote 0.5.8 exposes only 2 methods to outside: .code() and .destroy()
Summernote API is accessible inside plugins only, not from outside, it is in developpement, far from the point where it could be usable.
I suggest hardly dropping Summernote and revert back to CKEditor 4 + bootstrap style.
An OC extension already propose that for 2.x.

**Comment by jamesallsup** [comment]
Summernote will probably be updated to the latest version shortly.

**Comment by gob33** [comment]
Even in 0.6.2, Summernote is far away of CKEditor 4.
I will certainly drop certains functionalities (tags insertion in editor on double-click) in my extension(s) when passing from OC1.5.x to OC2.x because there is no API equivalent in Summernote.
This is a regression for merchants but I cant do it with your choice of Summernote.

**Comment by danielkerr** [comment]
latest summernote has just been added.

**Pull request closed without merging**
