### PR TITLE
OC4: Proposition for addStyles and addScript

### PR DESCRIPTION
**Pull request by stalker780**
1. Make possible adding styles to footer.
2. Make possible adding scripts properties, like `$prop = 'sync defer onload="myFunc();" id="my_script_id"'`

This is a must have for frontend templates and extensions, loading external resources.

This is a concept which changes array structure for both scripts and styles. So it requires simple changes but in lots of controllers preparing twig templates. Basically for addStyles and getStyles.

### CODE REVIEW

**Comment by TheCartpenter** [comment]
If addStyles or addScripts has a default parameter with its variable, then getStyles wouldn't need one.

**Comment by chulcha** [comment]
> 
> 
> If addStyles or addScripts has a default parameter with its variable, then getStyles wouldn't need one.

Does this somehow change the idea of the proposal?

**Comment by TheCartpenter** [comment]
The rest of the proposal remains to be seen.

**Comment by danielkerr** [comment]
its fine as it is,

**Pull request closed without merging**
