### PR TITLE
Update pp_express.php

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by condor2** [comment]
@mhcwebdesign It is correct?

**Comment by mhcwebdesign** [comment]
Looks good to me.

**Comment by mhcwebdesign** [comment]
Having said that, I don't think it will work, because of these lines:

```
			if ($this->config->get('payment_pp_express_test')) {
				$api_url = 'https://api-3t.sandbox.paypal.com/nvp';
				$api_username = $this->config->get('payment_pp_express_sandbox_username');
				$api_password = $this->config->get('payment_pp_express_sandbox_password');
				$api_signature = $this->config->get('payment_pp_express_sandbox_signature');
			} else {
				$api_url = 'https://api-3t.paypal.com/nvp';
				$api_username = $this->config->get('payment_pp_express_username');
				$api_password = $this->config->get('payment_pp_express_password');
				$api_signature = $this->config->get('payment_pp_express_signature');
			}

```

These config values don't exist anymore, we'd have to add a simple admin/controller/extension/payment/pp_express-recurring.php where it can be enabled and configured. 

But doesn't the PayPal Integration support recurring payments, too?

**Comment by condor2** [comment]
I think Paypal Express supported recurring payments.

**Comment by mhcwebdesign** [comment]
> I think Paypal Express supported recurring payments.

It probably did. I was just wondering whether the new PayPal Integration extension can support recurring payments, too.

**Comment by ADDCreative** [comment]
This just needs removing. There is no PayPal express extension anymore to set the payment_pp_express_xxx configuration settings. So this will just do nothing.

**Pull request merged**
