### PR TITLE
added latest Summernote editor version  v0.8.18

### PR DESCRIPTION
**Pull request by webkul-dilip**
added latest Summernote editor version  v0.8.18

### CODE REVIEW

**Comment by condor2** [comment]
- Summernote languages files not updated
- New functions not added
- No multilanguage support

**Comment by webkul-dilip** [comment]
> * New functions not added

Okay, We will check above mention point.
Thanks

**Comment by condor2** [comment]
Remove line 37

https://github.com/condor2/Opencart_2302/commit/2e9e0dc576765e765120211682b659a9c6a940d9#diff-700591e6f7f740b313f8256a67108e129afa2ca354da0b3ccd4d1d5fee4e2d8b

**Comment by webkul-dilip** [comment]
Now language will work perfectly. We need to add language code at admin in ISO 639-1 formate.
http://i.prntscr.com/ZSa4WpfoR4C2oqDg9b41Jg.png
http://i.prntscr.com/h7ZFjsBHQIiIasisZouMyA.png
http://i.prntscr.com/5EnzBKmPTBCS4OQ2FoZ25Q.png
http://i.prntscr.com/RCD5tiIMSmCxHYMoux1RaQ.png
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
@condor2  Could you please tell us which new functions are not added?

**Comment by condor2** [comment]
You didn't checked the URL...

> Remove line 37
> 
> [condor2/Opencart_2302@2e9e0dc#diff-700591e6f7f740b313f8256a67108e129afa2ca354da0b3ccd4d1d5fee4e2d8b](https://github.com/condor2/Opencart_2302/commit/2e9e0dc576765e765120211682b659a9c6a940d9#diff-700591e6f7f740b313f8256a67108e129afa2ca354da0b3ccd4d1d5fee4e2d8b)

**Comment by webkul-dilip** [comment]
> You didn't checked the URL...
> 
> > Remove line 37
> > [condor2/Opencart_2302@2e9e0dc#diff-700591e6f7f740b313f8256a67108e129afa2ca354da0b3ccd4d1d5fee4e2d8b](https://github.com/condor2/Opencart_2302/commit/2e9e0dc576765e765120211682b659a9c6a940d9#diff-700591e6f7f740b313f8256a67108e129afa2ca354da0b3ccd4d1d5fee4e2d8b)

Now code is implemented.

**Comment by condor2** [comment]
I said. Remove line 37 because when I made that commit I forgot to delete

`['imagesize', ['imageSize100', 'imageSize50', 'imageSize25']],`

**Pull request merged**
