### PR TITLE
Update common.js autocomplete (good)

### PR DESCRIPTION
**Pull request by BuslikDrev**
The latest version of Chrome has to click on the field 2 times for the window to appear. Also, the window quickly disappears on the first move of the mouse.

### CODE REVIEW

**Comment by danielkerr** [comment]
im using latest and its not doing it to me

**Comment by BuslikDrev** [comment]
> im using latest and its not doing it to me

[Edit category](https://demo.opencart.com/admin/index.php?route=catalog/category|form): click on the input "Parent" field. Do you immediately see a window with a list of options? Try to enable "save forms" in chrome - attribute autocomplete="on".

**Comment by danielkerr** [comment]
Start typing something should come up

**Comment by BuslikDrev** [comment]
> Start typing something should come up

When I type, the queries work. I don't get a listbox on the first click on the field (ajax works).

**Comment by danielkerr** [comment]
im not here to fix ur personall issue. if u have noticed no one else reporting this

**Comment by BuslikDrev** [comment]
> im not here to fix ur personall issue. if u have noticed no one else reporting this

You won't be able to catch the problem because of my bad English.
You ask others if they have an issue with the popup when autocomplete is enabled in google chrome. Have you ever tried adding non-existent data to any field on the demo site and clicking save so that the browser saves the options and starts offering them to you next time? Have you tried releasing the mouse quickly after the popup appears?

**Comment by BuslikDrev** [comment]
Due to new data appearing in the "tag datalist" on the focus event, the popup window disappears. The window appears if chrome offers options from autosave. It also happens when you click again and quickly move the mouse out of the field.

**Comment by stalker780** [comment]
I can also add a problem with autocomplete groups

Win10, Firefox 101

image
image

**Comment by BuslikDrev** [comment]
> I can also add a problem with autocomplete groups
> 
> Win10, Firefox 101

This problem is not in the js script, but in the sql query.

**Comment by stalker780** [comment]
No. JSON is fine.
But autocomplete selectbox does not group category options correctly
This is options structure

image

**Pull request closed without merging**
