### PR TITLE
Renamed return to returns in catalog/controller/account/returns.php

### PR DESCRIPTION
**Pull request by MagDevel**
Issue #12043

### CODE REVIEW

**Comment by TheCartpenter** [comment]
If we revert this, it will create issues with the term: ```return```. The reason this has been renamed was to resolved issues that were encountered in the past about this reserved terminology.

**Comment by MagDevel** [comment]
Ok. In that case, we have to rename "return" to "returns" in catalog/controller/account/returns.php as well.

**Comment by TheCartpenter** [comment]
> Ok. In that case, we have to rename "return" to "returns" in catalog/controller/account/returns.php as well.

Yes, correct, as this one's already done: https://github.com/opencart/opencart-3/blob/main/upload/catalog/controller/account/returns.php .

**Comment by danielkerr** [comment]
returns is used as return is a reserved word!

**Comment by danielkerr** [comment]
stop changing things u are wasting my time and will cause more issues.

**Comment by TheCartpenter** [comment]
This case is in regard to rename return into returns that was missing: https://github.com/opencart/opencart/pull/12045/commits/e67170778e9fea1cc23302d13d68d553aa5e3fa6 .

**Pull request closed without merging**
