### PR TITLE
[3.1.0.0_a2] Manage OpenCart javascript dependencies via package.json (npm/yarn)

### LINKED ISSUE #6765: Datetimepicker and BS4
Datetimepicker is not compatible with BS4. Open the product edit page and look the discount and special table.

Here is the new version, but i think it has some bugs. You can try:

https://github.com/tempusdominus/bootstrap-4

### LINKED ISSUE #6818: [3.1.0.0_a1] Use composer.json/(or package.json) for easier management of Bootstrap, jQuery, FortAwesome, etc.
placeholder...

### LINKED ISSUE #6830: Twice {% if custom_field.type == 'time' %} in register.twig
In [catalog/view/theme/default/template/account/register.twig](https://github.com/opencart/opencart/blob/master/upload/catalog/view/theme/default/template/account/register.twig) 
twice   `{% if custom_field.type == 'time' %}`.

Needs `{% if custom_field.type == 'datetime' %}`.

### PR DESCRIPTION
**Pull request by panreach**
By using `npm/yarn` we can do the following to publish the required `js/css` files needed.

Using `npm` (or `yarn`), for publishing `js/css`, should work well for managing our libraries in OpenCart.

Simply... all we need to do is update dependencies/versions via the `package.json` file in the root directory for building releases.

Then run the following:

`npm install`
or
`npm run publish` (after running `npm update`)

There is a script (`publish_packages.php`) that takes the files in `node_modules` (downloaded from `npm`/`yarn`) and copies everything over to production.  This must be ran with `npm/yarn` commands.  If trying to run via `php publish_packages.php` it probably won't work... (as you would need to instantiate with `new PublishPackages;` afterwards) ;-)

Although I haven't tested it, one could probably use `yarn install` and/or `yarn run publish` as well.  I'm sure most of you devs have one or the other of `npm`/`yarn` on your build machines... ;)

The publish_packages.php script, also erases the following:
`/upload/admin/view/stylesheet/bootstrap.css`
`/upload/catalog/view/theme/default/stylesheet/bootstrap.css`
`/upload/catalog/view/theme/default/stylesheet/stylesheet.css`

There might be a way to build these with a script?  But, I just load `http://catalog/[admin]` via my browser to generate them for a build.

`@TODO` test with https://github.com/opencart/opencart/pull/6848

Cheers!

This fixes #6818 
This fixes #6765 
This fixes #6830

### CODE REVIEW

**Comment by panreach** [comment]
@danielkerr Should I/we continue with this?  Or are there other plans?

**Comment by panreach** [comment]
I'll be going on vacation here in a week.  If I can finish this before, I'll start back up after the 17th.

Cheers!

**Comment by panreach** [comment]
@danielkerr Rather than muddying this PR up, I added a testing (build2) PR at https://github.com/opencart/opencart/pull/6848 for an actual build of the new javascript libraries via package.json.

**Comment by TheCartpenter** [comment]
This branch has conflicts ...

**Pull request closed without merging**
