### PR TITLE
Updated install steps

### PR DESCRIPTION
**Pull request by Hkr32**
Probably worth revising the style file opencart.css (old stylesheet.css).
I think it's still worth working on the promotion

- Added icons or changed them
- Moved scripts down
- Made tables responsive
- Several renames
- Removed unnecessary
- Updated libraries

oc-i-4
oc-i-3
oc-i-2
oc-i-1

### CODE REVIEW

**Comment by Hkr32** [comment]
I'm still looking at the opencart.css file.
If there are comments, I can correct them right away.

**Comment by Hkr32** [comment]
Ready to fix if you don't like something

**Comment by Hkr32** [comment]
install-steps--1
install-steps--2
install-steps--3
install-steps--4
install-error
install-upgrade--start
install-upgrade--active
install-upgrade--error

**Comment by Hkr32** [comment]
@danielkerr, please check and comment

**Comment by danielkerr** [comment]
this has all been fixed already

**Pull request closed without merging**
