### PR TITLE
Prevent double submit on save button

### PR DESCRIPTION
**Pull request by rensreinders**
We got SQL duplicate key errors. After some examination, we found out that the dit form got submit twice. This fixes block the default HTML behavior and only uses the javascript submit().

### CODE REVIEW

**Comment by condor2** [comment]
https://github.com/opencart/opencart/issues/7495

**Comment by rensreinders** [comment]
No clue, but latest release still has the bug so to see. All forms with id="form*" in the entire admin get submitted twice, lame...

**Comment by CodeInKlingon** [comment]
No clue how to communicate this problem and get a code commit through but I have narrowed down the problem. 
See this chrome bug thread: https://bugs.chromium.org/p/chromium/issues/detail?id=977882
The issue is in the common.js file. 
https://github.com/opencart/opencart/compare/master...CodeInKlingon:patch-1

**Comment by CodeInKlingon** [comment]
You can see more about this issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=977882

**Comment by danielkerr** [comment]
its been added

	//Form Submit for IE Browser
	if (isIE()) {
		$('button[type=\'submit\']').on('click', function() {
			$('form[id*=\'form-\']').submit();
		});

**Pull request closed without merging**
