### PR TITLE
pdo problem

### PR DESCRIPTION
**Pull request by smohamadabedy**
To solve the PDO problem in the issues section for searching and ...

### CODE REVIEW

**Comment by TheCartpenter** [comment]
That may not solve it for other DB libraries than PDO. Perhaps the escape function or the preg_replace function should be re-validated prior to use the query.

**Comment by smohamadabedy** [comment]
> That may not solve it for other DB libraries than PDO. Perhaps the escape method or the preg_replace function should be re-validated prior to use the query.

**Comment by smohamadabedy** [comment]
errors occure only in these two file, I checked others models and all of them pass % inside the skape.

**Comment by cgcmart** [comment]
`$implode[] = "pd.`name` LIKE '%" . $this->db->escape_like_str($word) . "%'";`

**Comment by TheCartpenter** [comment]
For MySQLi, this could differ based on the locations where the percentage is placed since the % would be also escaped.

**Comment by TheCartpenter** [comment]
This solution may help to use otherwise with LIKE: https://stackoverflow.com/a/51338452 .

**Comment by danielkerr** [comment]
already fixed

**Comment by smohamadabedy** [comment]
note that the problem is with `%`  and as far as I know real_escape_string function will NOT escape _ (underscore) and % (percent) signs, so there is no conflict to move `%` inside escape function.

**Pull request closed without merging**
