### PR TITLE
OC4 - WebP support

### PR DESCRIPTION
**Pull request by stalker780**
Add WebP image format support

PS
I am absolutely absent minded. Need to have some rest.
Of course I meant WebP format, not Twig

### CODE REVIEW

**Comment by stalker780** [comment]
Also committed SVG support for filemanager as @Hkr32 proposed in his pull request

**Comment by danielkerr** [comment]
nice one!

**Comment by stalker780** [comment]
@danielkerr
Any chance it will be included to OC4?

I can prepare a new pull request to fix branch conflicts.

**Comment by danielkerr** [comment]
Already added

**Comment by danielkerr** [comment]
SVG will not be supported

**Comment by danielkerr** [comment]
Are u winding me up. Do u know what SVG stands for?

**Comment by stalker780** [comment]
Great, don't see webp in latest master, that is why I was asking.

SVG is a vector format which is often used in information pages or as icons for categories for example.
Anyway, having webp would be good.

**Comment by Hkr32** [comment]
> Are u winding me up. Do u know what SVG stands for?

What's wrong with svg?

**Comment by danielkerr** [comment]
its not an image format. not a binary. its actual code.

**Comment by stalker780** [comment]
First one is without svg. But it has conflicts now
https://github.com/opencart/opencart/pull/8966/commits/501eac5a27f86a2883cd4c28789b35a9c8bda69d

**Pull request closed without merging**
