### PR TITLE
Escaping underscore with date function - controller/tool/log.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
The same could be done on the maintenance branch.

**Comment by mhcwebdesign** [comment]
Why do you want to escape the underscore character?

**Comment by TheCartpenter** [comment]
For the same reason as this one: https://stackoverflow.com/a/16516254

**Comment by ADDCreative** [comment]
You only need to escape recognised format characters.

**Comment by TheCartpenter** [comment]
As part of what the date function can gather, where does it state the underscore between the year date format and time format is recognized?

**Comment by ADDCreative** [comment]
Nowhere, which is why you don't need to escape it.

**Comment by TheCartpenter** [comment]
I would never thought that escaping were specifically meant for recognized characters rather than the other way around.

**Comment by ADDCreative** [comment]
From https://www.php.net/manual/en/function.date.php.
> You can prevent a recognized character in the format string from being expanded by escaping it with a preceding backslash.

So you only need to escape the ones listed here.
https://www.php.net/manual/en/datetime.format.php

**Comment by TheCartpenter** [comment]
It would seem from this page: https://www.php.net/manual/en/datetime.format.php that escaping characters are only meant for literal characters:

```To add literal characteres youi can escape with backslash (\):```

Therefore, this commit will now be closed.

**Pull request closed without merging**
