### PR TITLE
Memcached required for php7.0

### PR DESCRIPTION
**Pull request by howdu**

### CODE REVIEW

**Comment by danielkerr** [comment]
already in the dev version

**Comment by webcorvo** [comment]
sorry but don´t work with me.
my file name is mem.php

**Comment by webcorvo** [comment]
I change the code but don´t work 
[mem.zip](https://github.com/opencart/opencart/files/1009277/mem.zip)

**Comment by howdu** [comment]
@danielkerr  no dev only has support for memcache not memcached. With php7 there's only package 'php7.0-memcached'
https://github.com/opencart/opencart/tree/dev/upload/system/library/cache

**Comment by danielkerr** [comment]
ok

**Pull request merged**
