### PR TITLE
https://github.com/opencart/opencart/issues/8016

### PR DESCRIPTION
**Pull request by sdareios**

### CODE REVIEW

**Comment by straightlight** [comment]
```$json['next'] = str_replace('&amp;', '&', $this->url->link('marketing/contact/send', 'user_token=' . $this->session->data['user_token'] . '&page=' . ($page + 1), true));```

This won't work for the master branch. Are you posting this for the pre-release?

**Comment by sdareios** [comment]
> `$json['next'] = str_replace('&amp;', '&', $this->url->link('marketing/contact/send', 'user_token=' . $this->session->data['user_token'] . '&page=' . ($page + 1), true));`
> 
> This won't work for the master branch. Are you posting this for the pre-release?

Why doesn't it work?

**Comment by straightlight** [comment]
> > `$json['next'] = str_replace('&amp;', '&', $this->url->link('marketing/contact/send', 'user_token=' . $this->session->data['user_token'] . '&page=' . ($page + 1), true));`
> > This won't work for the master branch. Are you posting this for the pre-release?
> 
> Why doesn't it work?

Because you're using a true case where true cases with $this->url->link are no longer significant in the master branch.

**Comment by sdareios** [comment]
> > > `$json['next'] = str_replace('&amp;', '&', $this->url->link('marketing/contact/send', 'user_token=' . $this->session->data['user_token'] . '&page=' . ($page + 1), true));`
> > > This won't work for the master branch. Are you posting this for the pre-release?
> > 
> > 
> > Why doesn't it work?
> 
> Because you're using a true case where true cases with $this->url->link are no longer significant in the master branch.

Pre-release is this 3.0.3.4? I did according to what is said here - https://github.com/opencart/opencart/wiki/Creating-a-pull-request. Where should I make a change?

**Comment by straightlight** [comment]
Your first post states an empty description as it did not indicate which OC version you were posting this solution about. When creating a comment, please use the provided template for OC developers to understand the changes and the purpose of the change.

**Comment by sdareios** [comment]
Ok. Understand

**Comment by straightlight** [comment]
The suggested code is too manual. It could be added in the features-pre release with a $this->load->controller instead of using all these starts and ends manually as range. Besides, the common/pagination already uses this sort of ways throughout the master branch and the core-pre release.

**Comment by straightlight** [comment]
Ok, I will try it with this code. See the features-pre release if it's working as intended.

**Comment by sdareios** [comment]
Yes, it works in the features-pre release.

**Comment by sdareios** [comment]
For some reason, everything is very confusing for me. It is unclear what is in the main branch and what code should we use today.

**Comment by straightlight** [comment]
core-pre is about handling all (or most) of the bug-fixes from previous OC 3.x versions and the features-pre is about features that were added in the master branch but could have a fit in future OC stable releases for Opencart.com in the future and being integrated one step at a time as opposed to the core where the core all bug-fixes that can be found are being added more in realtime.

**Pull request closed without merging**
