### PR TITLE
Missing escape character for .twig extension

### PR DESCRIPTION
**Pull request by kenfai**
Added a missing escape character for .twig extension in the .htaccess file.

### CODE REVIEW

**Comment by straightlight** [comment]
Confirmed. Now added in the core-pre .

**Comment by straightlight** [comment]
Also added in the features-pre.

**Comment by reetp** [comment]
A typo in there as well if you wanted to add it

```
-# Prevent Directoy listing
+# Prevent Directory listing
```

**Comment by straightlight** [comment]
Added in both -pre.

**Comment by straightlight** [comment]
This issue has now been resolved. Therefore, this commit will now be closed.

**Pull request closed without merging**
