### PR TITLE
Update multiple security issues

### PR DESCRIPTION
**Pull request by dushanDissanayake**
FILTER_VALIDATE_EMAIL is replaced with a proper custom regex to validate emails at the registration.

### CODE REVIEW

**Comment by cgcmart** [comment]
What is the reason of the change?
[https://stackoverflow.com/questions/13719821/email-validation-using-regular-expression-in-php](url)

**Comment by dushanDissanayake** [comment]
> What is the reason of the change?
> 
> [https://stackoverflow.com/questions/13719821/email-validation-using-regular-expression-in-php](url)
> 
> > Using regular expressions to validate email addresses is not recommended as it is certainly not pretty, especially if you don't want to exclude somebody who has a valid email address that is correct according to RFC 822 grammar.

But the usage of FILTER_VALIDATE_EMAIL allows users to register with some emails which cannot even exist because opencart does not verify email addresses.
> Ex:- j!o*h+n$d%=o#e^@gmail.com is not a valid email in gmail domain. But this web application allows to create an account using this mail.

**Comment by cgcmart** [comment]
The fundamental problem is spambot attacking register form. The solution is implementing a smart spambot trap to stop spambot.

**Comment by ADDCreative** [comment]
Why prevent the use of TLS 1.3?

**Comment by straightlight** [comment]
This solution is user-defined. It will not guarantee its succession on preventing SPAM bots, in this case. Therefore, this commit will now be closed since vendors scripts are also being suggested. Please provide such solutions to the officials so to know their point of view in the future before officially posting such solutions in this namespace.

**Pull request closed without merging**
