### PR TITLE
Added meta_title for product in install sql

### PR DESCRIPTION
**Pull request by robinflyhigh**

### CODE REVIEW

**Comment by OpenCartAddons** [comment]
Strange.  I committed these changes a while back.  Something must have happened where they ended up getting reversed.

https://github.com/opencart/opencart/pull/3432


Cheers,
Joel.

**Comment by OpenCartAddons** [comment]
Looking back it looks like I accidentally added the meta titles to the tag column.  Shit, my bad.

Cheers,
Joel.

**Comment by robinflyhigh** [comment]
So are you fixing it or you want me to fix it for you @OpenCartAddons

**Comment by OpenCartAddons** [comment]
@robinflyhigh If you have time to revise your commit sure, otherwise I'll go through it tonight and fix it.

**Comment by robinflyhigh** [comment]
@OpenCartAddons I shall fix it for you in a moment.

**Comment by OpenCartAddons** [comment]
@robinflyhigh Thanks, very much appreciated.


Cheers,
Joel.

**Comment by robinflyhigh** [comment]
Done @OpenCartAddons

**Comment by OpenCartAddons** [comment]
@robinflyhigh @eka7a Is right, it looks like you accidentally replaced the oc_product portion of the install instead of the oc_product_description

**Comment by robinflyhigh** [comment]
I am so sorry. Fixed it and sent another pull request @eka7a @OpenCartAddons

**Comment by OpenCartAddons** [comment]
@robinflyhigh Thanks!

Cheers,
Joel.

**Pull request merged**
