### PR TITLE
Update article.php

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by AJenbo** [comment]
It would be good if you could use something like php-cs-fixer to fix each issues for all files in a single PR instead of so many PRs that do the same thing just one file at a time.

**Comment by TheCartpenter** [comment]
> It would be good if you could use something like php-cs-fixer to fix each issues for all files in a single PR instead of so many PRs that do the same thing just one file at a time.

You seem to have been provided full access to the MB for some... particular reasons. Therefore, I would please ask you to remain current with the founder's request: https://github.com/opencart/opencart/issues/12616#issuecomment-1676390828 . It has also been mentioned by @danielkerr that these sorts of pull requests can be be done within 10 minutes. I would assume you can do the same: https://github.com/opencart/opencart/issues/12616#issuecomment-1676388847 .

Thank you!

**Comment by AJenbo** [comment]
I agree that such PRs should be kept simple, that's why I'm suggesting to make one PR for each type of change, but for multiple files. I'll make a couple of examples.

**Comment by TheCartpenter** [comment]
> I agree that such PRs should be kept simple, that's why I'm suggesting to make one PR for each type of change, but for multiple files. I'll make a couple of examples.

Then, you are not agreeing with Daniel. You've spent more time showing examples of opened pull request with full access, just now, rather than merging the proposals you have submitted yourself and the ones I have recently submitted. As I have mentioned before to others as well, there are no website regulations in regard to the ways proposals are being submitted. You seem to put your focus on Time Management rather than Task Management and that is simply slowing everyone else that need to synch their forked trees with the Project Management.

Therefore, if you don't feel up to the task to merge those commits, that's fine; just let Daniel do it. So far, I think that since so many commits have been merged, based on my proposals, then - somehow - I must of done something right: https://github.com/opencart/opencart/pull/12843#issuecomment-1784198338 .

**Comment by AJenbo** [comment]
Calm down, I was just trying to give you a helpful suggestion. I'm not telling you that you have to do it one way or another. If you didn't notice I did actually merge quite a few of your PRs (the ones I felt sure about). I had some others suggestions for how you could do things more easily but I guess I will just not mention it if you don't like feedback.

I'll let Daniel evaluate the changes and see what he likes just like for everyone else instead of just forcing things without coordinating.

**Comment by TheCartpenter** [comment]
> Calm down, I was just trying to give you a helpful suggestion. I'm not telling you that you have to do it one way or another. If you didn't notice I did actually merge quite a few of your PRs (the ones I felt sure about). I had some others suggestions for how you could do things more easily but I guess I will just not mention it if you don't like feedback.
> 
> I'll let Daniel evaluate the changes and see what he likes just like for everyone else instead of just forcing things without coordinating.

It was already mentioned many times by previous users who attempted to take the same path as they've been told the same. As per my first post on this commit implies, while you may look pretty new on this project, I have also suggested to stay current and that was mentioned in good faith.

As for other suggestions, there were nowhere to be said that I would not consider other ideas. However, it just seem that no matter the idea being brought up, it more than often leads back to this one in general. Therefore, if you do have other suggestions you'd like to bring up to the table, I would be more than opened to hear them out.

**Comment by AJenbo** [comment]
What is your native language? It might be easier for me to understand.

**Pull request merged**
