### PR TITLE
fixed custom_field order edit issues & php8 compatible mail

### PR DESCRIPTION
**Pull request by prabhatkumaroc082**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Already fixed on the maintenance branch: https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/controller/api/customer.php .

**Comment by TheCartpenter** [comment]
Two separate packages have been worked on with the releases, that's probably why.

**Review by evaland999 — COMMENTED** [review]
Dear Sir,
I uploaded this code to my 3.0.3.7
And using PHP 8.xx
But still get wrong html contents

**Comment by prabhatkumaroc082** [comment]
> Dear Sir,
> I uploaded this code to my 3.0.3.7
> And using PHP 8.xx
> But still get wrong html contents

updated over the issue https://github.com/opencart/opencart/issues/9385#issuecomment-813238578

**Pull request merged**
