### PR TITLE
More work on subscriptions and removed opayo

### PR DESCRIPTION
**Pull request by TheCartpenter**
Worked on subscription discount reports and subscriptions order totals

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
I thought the subscription functionality was completed a few months ago, is it being re-worked again?

**Comment by TheCartpenter** [comment]
> I thought the subscription functionality was completed a few months ago, is it being re-worked again?

It's still in-progress.

**Comment by TheCartpenter** [comment]
image

```order_product_id``` and the ```product_id``` fields must be removed from the ```subscription``` table. Otherwise, the ```subscription_id``` will keep incrementing from the ```subscriptionPayment``` method since the ```subscription_id``` constantly needs to follow the ```product_id```, ```order_product_id``` and the related the transaction when using: ```$this->setPaymentData``` . 

Each subscription needs to remain unique with each orders since the ```subscription_id``` and the ```transaction_id``` also need to remain unique at the beginning or at the end of the process.

**Comment by danielkerr** [comment]
its nearly complete. i still need to add the emails

**Comment by TheCartpenter** [comment]
Closing this due to this report from Opayo repository: https://github.com/opencart/opencart/issues/11765#issuecomment-1908392931 . Setting a discount field would be acquired to achieve subscription discounts in the meantime. However, it won't prevent the transaction to be rejected by the payment service provider due to an invalid total amount that is initiated during payment. Since Opayo has been merged on this branch, the latest SCA requirements for 3D Secure also need to be built-in.

**Pull request closed without merging**
