### PR TITLE
Same website URL for IP check

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by ADDCreative** [comment]
Should be ```https://``` not ```//```.

**Comment by condor2** [comment]
When you use // will auto detect if is https or http so in the end url will be http:// or https://depending on the case.

**Comment by ADDCreative** [comment]
I know exactly what it does and that is actually the reason for not using ```//```, It's a external link. You should not base the protocol of an external link on the local protocol.

**Comment by condor2** [comment]
Changed...
https://github.com/opencart/opencart/pull/8682

**Pull request merged**
