### PR TITLE
Changed Application to Catalog Model - admin/controller/setting/loader.php file.

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by cgcmart** [comment]
Should change to Admin

**Comment by cgcmart** [comment]
> $this->autoloader->register('Opencart\Application\Controller\Extension\\' . $extension, DIR_EXTENSION . $result['extension'] . '/admin/controller/');
			$this->autoloader->register('Opencart\Application\Model\Extension\\' . $extension, DIR_EXTENSION . $result['extension'] . '/admin/model/');
			$this->autoloader->register('Opencart\System\Extension\\' . $extension, DIR_EXTENSION . $result['extension'] . '/system/');

**Comment by TheCartpenter** [comment]
> > $this->autoloader->register('Opencart\Application\Controller\Extension\' . $extension, DIR_EXTENSION . $result['extension'] . '/admin/controller/');
> > $this->autoloader->register('Opencart\Application\Model\Extension\' . $extension, DIR_EXTENSION . $result['extension'] . '/admin/model/');
> > $this->autoloader->register('Opencart\System\Extension\' . $extension, DIR_EXTENSION . $result['extension'] . '/system/');

It is no longer Application\Model . It is Catalog\Model now. Since the extensions are also loading the catalog template, then I believe it does indeed need to remain on the catalog folder and not the admin.

**Comment by cgcmart** [comment]
`$this->autoloader->register('Opencart\Application\Controller\Extension\\' . $extension, DIR_EXTENSION . $result['extension'] . '/catalog/controller/');`
			`$this->autoloader->register('Opencart\Extension\\', DIR_EXTENSION . $result['extension'] . '/catalog/model/');`
			`$this->autoloader->register('Opencart\System\Extension\\' . $extension, DIR_EXTENSION . $result['extension'] . '/system/');`

**Comment by TheCartpenter** [comment]
By doing that, people won't be able to call the models from the Engine but simply loading the model route from the extension since the namespace is originally owned by the Catalog\Model in this context.

**Comment by cgcmart** [comment]
Opencart\System\Extension does not exist. Is the place holder created for  DIR_EXTENSION?

`$this->autoloader->register('Opencart\System\Extension\\' . $extension, DIR_EXTENSION . $result['extension'] . '/system/');`
should be removed as default extension/opencart/ doesn't have system folder.
I believe that someone already pointed out before.

**Comment by TheCartpenter** [comment]
According to this commit line, it does exist: https://github.com/opencart/opencart/commit/5385d6b784c83364f6750ab0939fb9e858c7e5ba#diff-b245991332ebfa52c4d29054f29a39533e390a36548f9d7890a218874422e17eR16

**Comment by cgcmart** [comment]
> 
> 
> According to this commit line, it does exist: [5385d6b#diff-b245991332ebfa52c4d29054f29a39533e390a36548f9d7890a218874422e17eR16](https://github.com/opencart/opencart/commit/5385d6b784c83364f6750ab0939fb9e858c7e5ba#diff-b245991332ebfa52c4d29054f29a39533e390a36548f9d7890a218874422e17eR16)

I think it also needs to change upload/admin/controller/startup/extension.php as the loader file says `// Register controllers, models and system extension folders`
Both Opencart/model and Opencart/system does not have `extension` folder

**Comment by TheCartpenter** [comment]
I see the same on this commit file: https://github.com/opencart/opencart/commit/5385d6b784c83364f6750ab0939fb9e858c7e5ba#diff-262691ae23a7de8e961b559cbaed6dcfa8734d457cb284ed91b1dff56b8d9c95R16 .

**Comment by TheCartpenter** [comment]
Issue resolved:

https://github.com/opencart/opencart/blob/9bc4a38db4cfe61686f40ea3b783be457ac668ef/upload/admin/controller/setting/loader.php#L23
https://github.com/opencart/opencart/blob/9bc4a38db4cfe61686f40ea3b783be457ac668ef/upload/catalog/controller/startup/extension.php#L14

Therefore, this commit will now be closed.

**Pull request closed without merging**
