### PR TITLE
Fixed list Time Zone

### PR DESCRIPTION
**Pull request by v5manoel**
The previous function that display the time zone difference in hours it is wrong.

### CODE REVIEW

**Comment by danielkerr** [comment]
makes no sense.  does not change the value of the time stamp.

i think what i have commited is fine!

**Comment by danijelGombac** [comment]
Once you set the time zone the timezone list options text change.

UTC selected ->Pacific/Wallis (+12:00)

Europe/Zurich selected ->Pacific/Wallis (+1:00)

**Comment by v5manoel** [comment]
@danijelGombac Test my fix and make sure the issue is resolved.

**Comment by v5manoel** [comment]
@danielkerr You may not accept my correction, but you will have to correct the time zone listing because it has the problem reported by @danijelGombac

**Comment by danijelGombac** [comment]
@v5manoel 

With your fix the issue is resolved. Thanks.

**Pull request merged**
