### PR TITLE
Update redis.php

### PR DESCRIPTION
**Pull request by TheCartpenter**
Unaligned $prefix variable.

https://github.com/opencart/opencart/pull/13318

### CODE REVIEW

**Comment by AJenbo** [comment]
Stop doing this, it's wroing. It's not supposed to be alligned, no other ones are. That's why tests failed. https://github.com/opencart/opencart/actions/runs/7364655276/job/20045222365

image

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart/blob/master/upload/admin/model/catalog/attribute.php#L37-L38

**Comment by AJenbo** [comment]
_PHPDoc_ **parameters** and _PHP_ **properties** are not the same things.

**Comment by TheCartpenter** [comment]
It's the same alignment for variables regardless of their properties. The $ begins at the same position after one space.

**Pull request closed without merging**
