### PR TITLE
Adding SagePay Opayo in extensions

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Review by AJenbo — CHANGES_REQUESTED** [review]
These files have lots of syntax (`string|bool`) that is invalid in PHP 7.4

**Comment by condor2** [comment]
Possible PR wil not ne accepted. I think Daniel want to be added only on 3.0.x.x branch

**Comment by TheCartpenter** [comment]
It says the operation was cancelled. I don't see any errors in the logs.

**Comment by TheCartpenter** [comment]
Needs further completion anyways. I'll repost this later.

**Comment by condor2** [comment]
Parse error: syntax error, unexpected '|', expecting ';' or '{' in upload/extension/opencart/catalog/model/payment/opayo.php on line 126
Errors parsing upload/extension/opencart/catalog/model/payment/opayo.php

Parse error: syntax error, unexpected '|', expecting ';' or '{' in upload/extension/opencart/admin/model/payment/opayo.php on line 100
Errors parsing upload/extension/opencart/admin/model/payment/opayo.php
Syntax errors were found.
Error: Process completed with exit code 1.

**Comment by AJenbo** [comment]
> It says the operation was cancelled. I don't see any errors in the logs.

Read the filing one, not the cancelled ones (they are cancelled because the other on already failed):

image

**Pull request closed without merging**
