### PR TITLE
Fix incorrect indentation in mail subscription

### PR DESCRIPTION
**Pull request by AJenbo**
This was done using php-cs-fixer's indentation_type rule. Once all oustanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.

### CODE REVIEW

**Comment by TheCartpenter** [comment]
> This was done using php-cs-fixer's indentation_type rule. Once all oustanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.

Then, it is not automated. Users still have to use proper formatting on their own coding styles in order to fit this in. As per the above, you're also using the CS Fixer plugin which means that you need to use a fixer prior to submit the proposal on the repository. If they'd be a universal way to use the coding styles, no fixers would be required, that's pretty much what the message describes and that's already expected unfortunately.

Therefore, what are the coding styles settings that should match with the ```.editorconfig``` file since this file seem to override our settings in the first place?

**Comment by AJenbo** [comment]
I think you are just being overly pedantic here. Besides it could be fully automated if desired.

> Therefore, what are the coding styles settings that should match with the .editorconfig file since this file seem to override our settings in the first place?

Go read https://editorconfig.org/ it's very simple format and does not have any language specific functionality.

Many IDEs can work with php-cs-fixer and in those cases it wold work the way I think you are thinking of with .editorconfig.

**Comment by TheCartpenter** [comment]
> I think you are just being overly pedantic here. Besides it could be fully automated if desired.
> 
> > Therefore, what are the coding styles settings that should match with the .editorconfig file since this file seem to override our settings in the first place?
> 
> Go read https://editorconfig.org/ it's very simple format and does not have any language specific functionality.
> 
> Many IDEs can work with php-cs-fixer and in those cases it wold work the way I think you are thinking of with .editorconfig.

No insults intended here, just stating the facts as per: https://github.com/opencart/opencart/pull/13177#issuecomment-1859212443 . It did not had any mention for users still having to use their own formatting as per the first post on this commit.

**Comment by AJenbo** [comment]
Well just like an IDE must support editorconfig for .editorconfig to have an effect they must also support php-cs-fixer intergration for this to take effect. Thought they can also opt to install it as a separate tool if they prefer.

**Comment by TheCartpenter** [comment]
> Well just like an IDE must support editorconfig for .editorconfig to have an effect they must also support php-cs-fixer intergration for this to take effect. Thought they can also opt to install it as a separate tool if they prefer.

When I commit and push the changes from my tool, on my repository, when I create a pull request to this forked repository, it just seem to keep accumulating for some reason even though the patches have been deleted (not the opencart-3 repository related). I keep synching the forked tree from my repository, it does synch when changes occurs on this MB but the pull requests that I submit just keeps growing.

Now, I can't even create a new pull request directly from my tree. Is there a way to clear that previous list once pushed since this tree is obviously protected?

**Comment by AJenbo** [comment]
MB?

**Comment by TheCartpenter** [comment]
> MB?

Master Branch

**Comment by AJenbo** [comment]
> When I commit and push the changes from my tool

What tool? It's easier to help if I know the context since different tools have different workflows and terms.

> on my repository, when I create a pull request to this forked repository,

This repository (`opencart/opencart`) is the original upstream, not a fork. https://github.com/TheCartpenter/opencart is your fork on github.

Note that each clone of a git repository is a fully independent repository. That means that both `opencart/opencart`, `TheCartpenter/opencart`, AND the one on your computer are 3 different repositories.

> it just seem to keep accumulating for some reason.

Make sure to create the new branch based on `opencart/opencart:master` (or one in sync with it, since that is what you want to merge with) before committing changes meant for another PR.

> even though the patches have been deleted (not the opencart-3 repository related).

A patch is a file that contains a commit as a diff. I'm going to assume you mean branch.

Deleting a branch on `TheCartpenter/opencart` won't delete it from your computer or vice versa. So if you just add another commit to the same local branch on your computer and then push it you will be pushing all the previous commits back on to github again even if you deleted them from github previously.

It does not look like you delete branches from your fork on github: https://github.com/TheCartpenter/opencart/branches
It's not that you need to do so but just so we are on the same page.

> I keep synching the forked tree from my repository, it does synch when changes occurs on this MB

You lost me a bit here, are you syncing the one on your computer, `opencart/opencart-3` or both? Maybe describe how you do the syncing?

> but the pull requests that I submit just keeps growing.

Can you give me an example, I don't see any branches on your repo that shows this?

> Now, I can't even create a new pull request directly from my tree.

You can protect branchs, not entier trees. I don't think any branches are actually protected in this repository since Darren keeps pushing directly to master. I guess you are just refering to having write access to the repository.

> Is there a way to clear that previous list once pushed since this tree is obviously protected?

You can reset and force push, but I think the best option is to create a new branch, though it's a little hard to say for sure until I better understand what you are doing and what you are trying to do.

**Comment by TheCartpenter** [comment]
As mentioned above, it is not opencart-3 related. When I sync from TheCartpenter/opencart , it syncs just fine but the commit are accumulating when pushing new commits on top of previous ones even though previous ones have been merged / closed. As to create a new branch, I'll have to look into it but I also need to know how to remove the previous commits so that it doesn't accumulate on the list even though patches have been deleted previously.

**Comment by AJenbo** [comment]
I'm not referering to opencart-3 at any point, I don't even know what it is, you mentioning it here is the first I hear of it.

> sync from TheCartpenter/opencart for opencart/opencart

This is not grammatically correct so I don't understand if you are syncing TheCartpenter/opencart from opencart/opencart, or saying that your commits are synced from TheCartpenter/opencart to opencart/opencart.

> even though previous ones have been merged / closed. As to create a new branch

A PR (Pull Request) is not the same as a branch. A pull request referes to two branches, closing/merging a PR does not delete the source branch. When merged the commits in the source branch are copied to the target branch.
You can set github up to also delete the source branch on either events, but you have not done so:
https://github.com/opencart/opencart/pull/13242 is merged, but https://github.com/TheCartpenter/opencart/tree/patch-65 still exists.

> I also need to know how to remove the previous commits so that it doesn't accumulate on the list even though patches have been deleted previously.

No, you are misunderstanding how it works. You don't delete previous commits, you switch branches. Again if you can give me an example of where you have accumulated changes then I can better help explain what step you are getting wrong.

**Comment by TheCartpenter** [comment]
> I'm not referering to opencart-3 at any point, I don't even know what it is, you mentioning it here is the first I hear of it.
> 
> > sync from TheCartpenter/opencart for opencart/opencart
> 
> This is not grammatically correct so I don't understand if you are syncing TheCartpenter/opencart from opencart/opencart, or saying that your commits are synced from TheCartpenter/opencart to opencart/opencart.
> 
> > even though previous ones have been merged / closed. As to create a new branch
> 
> A PR (Pull Request) is not the same as a branch. A pull request referes to two branches, closing/merging a PR does not delete the source branch. When merged the commits in the source branch are copied to the target branch. You can set github up to also delete the source branch on either events, but you have not done so: #13242 is merged, but https://github.com/TheCartpenter/opencart/tree/patch-65 still exists.
> 
> > I also need to know how to remove the previous commits so that it doesn't accumulate on the list even though patches have been deleted previously.
> 
> No, you are misunderstanding how it works. You don't delete previous commits, you switch branches. Again if you can give me an example of where you have accumulated changes then I can better help explain what step you are getting wrong.

The Submit tPull Request button is not showing on the site anymore. Perhaps it's because there are too many requests at once on that list awaiting. It is allowing me to click on the New Pull Request button but I cannot go beyond that point.

**Comment by AJenbo** [comment]
> The Submit tPull Request button is not showing on the site anymore.

It only shows the suggestion if the branch is new, or had recent changes, and does not match the name of another recent branch.

> Perhaps it's because there are too many requests at once on that list awaiting.

I have 139 on my project and it's showing fine

> It is allowing me to click on the New Pull Request button but I cannot go beyond that point.

I need more context, what repo and branch are you attempting to create a PR for?

**Comment by AJenbo** [comment]
https://github.com/opencart/opencart/compare/master...TheCartpenter:opencart:master

> When I commit and push the changes from my tool, on my repository, when I create a pull request to this forked repository, it just seem to keep accumulating for some reason

I explored your for a bit, it looks like you are commit straight to the master branch on your tree. As mentioned you should create separate branches for each change set you want to create a PR for.

image

Since I don't know what tool you are using I can't help you with how to create a branch.

> I also need to know how to remove the previous commits

It's best to keep your master branch in sync with the upstream master branch if your intent is just to use the fork to work on PRs for the upsteam repo. Right now your master branch has diverged with 90 commits. I would suggest you do a hard reset of the master branch against the commit of the upstream master branch (currently 4fe7435) and then force push to your github repo.
That will make it easier to create new branches with out also having to add the upstream repo as a remote for the repo on your computer.

Again with out knowing what tool you use I can't properly guide you on how to do so.

**Comment by AJenbo** [comment]
I would also suggest that you start deleting some of your old branches that have already been merged, there are nearly 500, which probably isn't helping anyone either: https://github.com/TheCartpenter/opencart/branches/all

>  It is allowing me to click on the New Pull Request button but I cannot go beyond that point.

Here is a link for creating PRs from your fork to this one:
https://github.com/opencart/opencart/compare/master...TheCartpenter:opencart:master
(you can pick your source branch in the right most drop down)

**Comment by TheCartpenter** [comment]
> I would also suggest that you start deleting some of your old branches that have already been merged, there are nearly 500, which probably isn't helping anyone either: https://github.com/TheCartpenter/opencart/branches/all
> 
> > It is allowing me to click on the New Pull Request button but I cannot go beyond that point.
> 
> Here is a link for creating PRs from your fork to this one: [master...TheCartpenter:opencart:master](https://github.com/opencart/opencart/compare/master...TheCartpenter:opencart:master) (you can pick your source branch in the right most drop down)

This is the link page I was referring to. Normally, on the lower-right corner of the page, I use a green button that allows me to create a merged PR. Now, I cannot submit new PRS at all. It only shows this compare list from that link.

**Comment by AJenbo** [comment]
Don't know, it seems to work for me. Maybe there is some setting or something:
https://github.com/opencart/opencart/compare/master...TheCartpenter:opencart:patch-190

**Comment by TheCartpenter** [comment]
> Don't know, it seems to work for me. Maybe there is some setting or something.
> 
> You did leave a lot unanswered so I can't really help anymore then I have here.

Ok, I created a new branch and I was able to create a new PR: https://github.com/opencart/opencart/pull/13247 . Need one commit merged specifically: https://github.com/opencart/opencart/pull/13247 .

As you can see, I deleted all the branches as instructed and the issue is still ongoing with past commits.

**Comment by AJenbo** [comment]
I see you also deleted the branches for your pending PRs, with out a source branch a PR is not valid and will be closed (example https://github.com/opencart/opencart/pull/13147), you might want to restor those branches if you wan to re-open them.

> Need one commit merged specifically: https://github.com/opencart/opencart/pull/13247

That's not a commit, it's a PR for a branch, with 90 commits, many which are reversts of other commits. What are  you trying to do?

If you want to create a PR with just the changes in https://github.com/opencart/opencart/commit/cedbeb481f861be4363c41fbc6e488781b0b45d9 then you need to create a new branch based on `opencart/opencart:master`, apply just that change (you could cherry-pick the commit) to that branch, push the branch to github, and then open a pull request.
Then switch away from the branch and not work any further on it (unless you want to update the PR with more changes).

> the issue is still ongoing with past commits.

With out you giving the information I have asked for I cannot help you any further.

**Comment by AJenbo** [comment]
>  I deleted all the branches as instructed

It looks like you created the new branch (patch-54) from your `TheCartpenter/opencart:master` branch, and you have still not reset it to match the `opencart/opencart:master` so you will be getting the extra 90 commits from it in your PR.

Either reset `TheCartpenter/opencart:master`, or create your new branch based on `opencart/opencart:master`.

**Comment by TheCartpenter** [comment]
> > I deleted all the branches as instructed
> 
> It looks like you created the new branch (patch-54) from your `TheCartpenter/opencart:master` branch, and you have still not reset it to match the `opencart/opencart:master` so you will be getting the extra 90 commits from it in your PR.
> 
> Either reset `TheCartpenter/opencart:master`, or create your new branch based on `opencart/opencart:master`.

What I am trying to do is to remove all previous PRs and only keep the most recent one so that the list doesn't accumulate upon each proposals.

I did reset my tree already but the issue still persists with the previous PRs. I am trying the opencart/opencart:master for a new branch now.

**Comment by TheCartpenter** [comment]
> > > I deleted all the branches as instructed
> > 
> > 
> > It looks like you created the new branch (patch-54) from your `TheCartpenter/opencart:master` branch, and you have still not reset it to match the `opencart/opencart:master` so you will be getting the extra 90 commits from it in your PR.
> > Either reset `TheCartpenter/opencart:master`, or create your new branch based on `opencart/opencart:master`.
> 
> What I am trying to do is to remove all previous PRs and only keep the most recent one so that the list doesn't accumulate upon each proposals.
> 
> I did reset my tree already but the issue still persists with the previous PRs. I am trying the opencart/opencart:master for a new branch now.

The full list is still there...

image

The screenshot shows: opencart/opencart:master

**Comment by TheCartpenter** [comment]
image

When I push from my tool, it shows this list even though I am not selecting them. I only want to push the first one. When I try a cherry-pick for patch-56, the tool says that there is nothing to cherry-pick. All changes from <<commit #>> have already been applied.

**Comment by TheCartpenter** [comment]
I think, now, might be the day!

Got the last two latest changes as expected. Should work now; I found the issue. Hard reset and has to drop previous commits in order to get rid of the files from the push page (screenshot).

https://github.com/opencart/opencart/pull/13250

**Comment by AJenbo** [comment]
Yes that's what [I said](https://github.com/opencart/opencart/pull/13243#issuecomment-1863196662) 😄
I can confirm that TheCartpenter/opencart:master now looks correct.

I still don't understand why you won't say what tool you are using, it made this much harder to communicate.

**Comment by TheCartpenter** [comment]
In regard to the tool, I do tend to keep it low profile for obvious reasons while working on the project. As for your instructions, you did mentioned to delete previous patches and to clear the most as to do a HEAD reset (I selected the hard one multiple times) but what wasn't instructed about was to drop the previous created commits from the logs.

However, I do thank you for your patience in this, I have been trying to solve the issue for a long time on this one, I can now resume with the merged version of my proposals. :)

**Comment by AJenbo** [comment]
No that isn't obvious, if it's something you build youeself then just say "git cli" or whatever you use under the hood, or something else that you are comfortable with.

> As for your instructions, you did mentioned to delete previous patches and to clear the most as to do a HEAD reset (I selected the hard one multiple times) but what wasn't instructed about was to drop the previous created commits

That just isn't true, I never even mentioned HEAD and I gave you the exact hash to reset to.

**Comment by TheCartpenter** [comment]
> No that isn't obvious, if it's something you build youeself then just say "git cli" or whatever you use under the hood, or something else that you are comfortable with.
> 
> > As for your instructions, you did mentioned to delete previous patches and to clear the most as to do a HEAD reset (I selected the hard one multiple times) but what wasn't instructed about was to drop the previous created commits
> 
> That just isn't true, I never even mentioned HEAD and I gave you the exact hash to reset to.

Your exact words were:

```Either reset TheCartpenter/opencart:master, or create your new branch based on opencart/opencart:master.```

I did mentioned I did a hard HEAD reset which resolved the issue. I did thanked you for your assistance, still. You did provided guidance on this post.

**Comment by AJenbo** [comment]
I also said:

> do a hard reset of the master branch against the commit of the upstream master branch (currently https://github.com/opencart/opencart/commit/4fe74350866e8d530867d1be087a60582f98d4d5) and then force push to your github

And:

> you have still not reset it (`TheCartpenter/opencart:master`) to match the `opencart/opencart:master`

**Comment by TheCartpenter** [comment]
I did say here that I did reset the tree: https://github.com/opencart/opencart/pull/13243#issuecomment-1863593170 (HEAD) . Your solution worked then and still works now...

**Pull request merged**
