### PR TITLE
[3.0.x.x] Undefined variable: $data- upload model

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Already fixed in opencart-3. The core shows a mandatory array, not an optional parameter for this method.

**Comment by TheCartpenter** [comment]
Looks like it's optional after all. Corrected it, now.

**Comment by condor2** [comment]
Why only $data and not $data = array ?
Is like getTotalProducts from product model

**Comment by TheCartpenter** [comment]
> Why only $data and not $data = array ? Is like getTotalProducts from product model

Replied on the above.

**Comment by condor2** [comment]
Posted at the same time :)

**Pull request merged**
