### PR TITLE
Warning: A non-numeric value encountered php7+

### PR DESCRIPTION
**Pull request by BuslikDrev**
If you turn off the SEO URLs and turn on the error output, then at php7 it gives an error: "Warning: A non-numeric value encountered".
https://demo.opencart.com/index.php?route=product/search&search=&page=sdf

### CODE REVIEW

**Comment by straightlight** [comment]
All these issues have already been reported and fixed on the master branch.

**Comment by straightlight** [comment]
The closing brackets of methods don't need to contain extra spaces. As for the config pagination, it may still be questionable due to the limitations of the autocomplete results. As for the arrays, that would be right.

**Comment by straightlight** [comment]
Aside from the array arrows change, it's not required.

**Comment by BuslikDrev** [comment]
> Обо всех этих проблемах уже сообщалось и исправлено в основной ветке.

Main where? What is this thread for? All that I offered now in vain?

**Comment by straightlight** [comment]
The arrays are not in vain.

**Comment by BuslikDrev** [comment]
> The arrays are not in vain.

Tell me which branch to submit your code to?

**Comment by straightlight** [comment]
This location is the right one. It's just that, as explained above, aside from the array changes you made, they don't require changes.

**Comment by ADDCreative** [comment]
3.0.x.x_Google_Pay is the wrong branch, you need to use 3.0.x.x_Maintenance and/or master.

**Pull request closed without merging**
