### PR TITLE
Hotfix/twig payment

### PR DESCRIPTION
**Pull request by chris-wm**
testing and updating payment gateways after twig

### CODE REVIEW

**Comment by danielkerr** [comment]
if it has twig changes it should be committed to the dev branch.

**Comment by danielkerr** [comment]
will ass james to look into it

**Comment by jamesallsup** [comment]
needs to be merged into dev

**Comment by chris-wm** [comment]
This is to be ignored, all the changes were re-submitted as part of pr #4693

Kind regards

*Chris Dixon*

Development & Integrations Manager



*Welford Media Ltd*
Suite 28, 30-38 Dock Street
Leeds
LS10 1JF


T: +44 (0)113 350 6099
Web: www.welfordmedia.co.uk
Twitter: www.twitter.com/welfordmedia

Facebook: www.facebook.com/welfordmedia

Registered in England
Registered number: 05315622
VAT: GB 873374987

**Pull request closed without merging**
