### PR TITLE
Fixed IF statement - admin/controller/sale/api.php file.

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
I still think that, either, the admin/controller/marketing/contact.php , marketing.php and admin/controller/startup/marketing.php files should validate the store ID since the admin/controller/sale/api.php file does validate the store ID which means that any relevant store ID lookup could then capture the entire marketing data regardless of the store ID the marketing ID or code might be associated with.

**Comment by danijelGombac** [comment]
@TheCartpenter  Why you changing unfinished stuff? You could wait at least a couple of days so Daniel can finish what he started .

**Comment by TheCartpenter** [comment]
Because Pull Requests are meant to suggest code changes whereas this file has been publicized by the Project Owner originally.

**Comment by danijelGombac** [comment]
@TheCartpenter 

Luckily there are few smart people who think like you, because otherwise Daniel could half the day only reviewing pull requests.

**Comment by TheCartpenter** [comment]
> Because Pull Requests are meant to suggest code changes whereas this file has been publicized by the Project Owner originally.

Then, your criticism has nothing to do specifically with my PR but rather with the project owner.

**Comment by TheCartpenter** [comment]
Solved on this commit: https://github.com/opencart/opencart/blob/977710c5ba995d49261f20273e971482c584970b/upload/admin/controller/sale/api.php .

**Pull request closed without merging**
