### PR TITLE
getProductsByCategoryId not used

### PR DESCRIPTION
**Pull request by Grumvol**

### CODE REVIEW

**Comment by straightlight** [comment]
Confirmed. Found in the master branch. Nice catch!

**Comment by Grumvol** [comment]
Here are still unused methods.

catalog\model\catalog\product.php
getLatest

catalog\model\catalog\product.php
getPopular

catalog\model\catalog\category.php
getTotalCategoriesByCategoryId

admin\model\catalog\product.php
getOptionValues

admin\model\catalog\product.php
getTotalOptionsByOptionId

**Comment by straightlight** [comment]
Jesus that's BAD!

Confirmed. Also found the first three ones in the pre-release. I'll make the update today. All five have been found in the master branch.

**Comment by ADDCreative** [comment]
What if there are extensions that use them?

**Pull request closed without merging**
