### PR TITLE
OC4: Fix extension installer upload form

### PR DESCRIPTION
**Pull request by stalker780**
Fix this finally please.

How many weeks are needed for this? :)

### CODE REVIEW

**Comment by cgcmart** [comment]
@stalker780  Did you test it?

There are 8 files using '#upload-form' including upload/admin/view/javascript/common.js

**Comment by stalker780** [comment]
@cgcmart Yes. This does the job for this form.
Here were several mentions about extensions upload not working.

**Comment by stalker780** [comment]
I am glad to help with other forms. This is a simple task.
But I don't want to waste my time. As these pulls are mostly ignored and this does not help to finish OC4 faster.

**Comment by cgcmart** [comment]
Pulls from forks often cause conflicts with git alert when oc master origin updates, that bring extra labor and repeated fix work if pulls not reviewed and merged or closed, that is, timely handled by administrator or authors.
Keep one private depository and update change log maybe saves time to repeat fix work.

**Comment by stalker780** [comment]
Looks like this is fixed already

**Pull request closed without merging**
