### PR TITLE
[3.0.x.x] Make identically identified functions have the same signature

### PR DESCRIPTION
**Pull request by AJenbo**
@mhcwebdesign nice progress on the PHPStan issues. This PR should make the branch pass the check fully.

The reason it's failing is that there are multiple classes with the same name and namespace, coatning method with the same name but different signatures.

This is just a proposed solution, idk if you prefer to solve it by renaming them or some other way.

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
This doesn't explain the phpstan bugs, see https://github.com/opencart/opencart/issues/13663 

For a given set of PHP files, phpstan should always produce the same results, it doesn't! Until then, I suggest we disable phpstan, or come up with a proper fix!

**Comment by mhcwebdesign** [comment]
Besides, your change to the model/extension/payment/opayo.php for the sendCurl is wrong! phpstan needs to be fixed if it can't cope with functions using optional parameters.

**Comment by AJenbo** [comment]
Hm maybe you didn't understand what I wrote in the first message.

The issue at hand is that there are multiple classes in OC3 with the same class name.

> phpstan needs to be fixed if it can't cope with functions using optional parameters.

This has noting to do with optional parameters. It's caused by there being two classes with the same name that both have a method called sendCurl(). One has 3 arguments the other 2. So it depends on which one is processed first and there for will give different results on different computers.
This issue was solved in OC4 by using namespace.

My proposed solution for OC3 is to have identical signatures for identically named signatures.
The alternative would be to make sure they are globally unique.

**Comment by mhcwebdesign** [comment]
Sorry, you are wrong. Different classes in PHP, using the same name for a method, can use different method signatures for this. These are not bugs in OC 3.0.x.x! And developers shouldn't have to worry about how they name class methods, with what signatures, as long the methods are correctly used and called upon.

I reported this bug here: https://github.com/phpstan/phpstan/issues/10560 on the phpstan repository, though I don't have time to write  more sample codes for this on their repo. Busy making OC 3.0.x.x stable again!

**Comment by AJenbo** [comment]
Sure, you are entitled to your opinion of cause.

**Pull request merged**
