### PR TITLE
Email IDN validation

### PR DESCRIPTION
**Pull request by stalker780**
https://github.com/opencart/opencart/issues/9755

Another attempt.

Validation still uses native PHP filter_var. But it encodes mail domain to punycode.

Perhaps Mail library must be also modified to encode domains with `oc_punycode()`.
However my external SMTP test to real `info@домен.укр` was successful even without this. 
Need more Mail/SMTP tests with different servers.

Here are validation results:
```
latin.email.com -> punycode: latin.email.com -> filter_var result: false

latin@email.com -> punycode: latin@email.com -> filter_var result: true

latin@email@example.com -> punycode: latin@email@example.com -> filter_var result: false

ghfh@renangonçalves.com -> punycode: ghfh@xn--renangonalves-pgb.com -> filter_var result: true

用户@例子.广告 -> punycode: 用户@xn--fsqu00a.xn--4rr70v -> filter_var result: true

ಬೆಂಬಲ@ಡೇಟಾಮೇಲ್.ಭಾರತ -> punycode: ಬೆಂಬಲ@xn--xscd4bq2d9bd3c.xn--2scrj9c -> filter_var result: false

अजय@डाटा.भारत -> punycode: अजय@xn--c2bd1gb.xn--h2brj9c -> filter_var result: true

квіточка@пошта.укр -> punycode: квіточка@xn--80a1acn3a.xn--j1amh -> filter_var result: true

χρήστης@παράδειγμα.ελ -> punycode: χρήστης@xn--hxajbheg2az3al.xn--qxam -> filter_var result: true

Dörte@Sörensen.example.com -> punycode: Dörte@xn--srensen-90a.example.com -> filter_var result: true

коля@пример.рф -> punycode: коля@xn--e1afmkfd.xn--p1ai -> filter_var result: true

support@ツッ.com -> punycode: support@xn--9ckb.com -> filter_var result: true

info@xn--80a1acn3a.xn--j1amh -> punycode: info@xn--80a1acn3a.xn--j1amh -> filter_var result: true

info%@пошта.укр -> punycode: info%@xn--80a1acn3a.xn--j1amh -> filter_var result: true

info(%)@пошта.укр -> punycode: info(%)@xn--80a1acn3a.xn--j1amh -> filter_var result: false

info[]@example.com -> punycode: info[]@example.com -> filter_var result: false
```

### CODE REVIEW

**Comment by ADDCreative** [comment]
> Perhaps Mail library must be also modified to encode domains with `oc_punycode()`. However my external SMTP test to real `info@домен.укр` was successful even without this. Need more Mail/SMTP tests with different servers.

Are you saying you were able to send an email to that domain via OpenCart, without modifying the SMTP class?

**Comment by stalker780** [comment]
> > Perhaps Mail library must be also modified to encode domains with `oc_punycode()`. However my external SMTP test to real `info@домен.укр` was successful even without this. Need more Mail/SMTP tests with different servers.
> 
> Are you saying you were able to send an email to that domain via OpenCart, without modifying the SMTP class?

Exactly. Mailgun SMTP. Don't know, perhaps their server has own punycode converter. That's why more tests are required.

**Comment by stalker780** [comment]
Anyway we need to start with something.
First step to allow idn domains to be added to DB.
After this we will get reports from OC users if something else needs to be fixed.

**Comment by ADDCreative** [comment]
> Exactly. Mailgun SMTP. Don't know, perhaps their server has own punycode converter. That's why more tests are required.

@stalker780 That's interesting. All the SMTP servers I tested would reject emails with non-ASCII characters in the address. Some such as Gmail would only work if SMTPUTF8 was added to the SMTP class as per RFC 6531. In that case they did convert the domain to punycode for the DNS lookup.

**Comment by stalker780** [comment]
@ADDCreative It's not a problem to add several lines of code to the Mail class.

**Pull request closed without merging**
