### PR TITLE
Admin category list filters

### PR DESCRIPTION
**Pull request by stalker780**
Modern stores have hundreds and even thousands of categories. Category list must have filters by name, parent, status

image

### CODE REVIEW

**Comment by pemaier** [comment]
+1

**Comment by mhcwebdesign** [comment]
@stalker780 : 

> Modern stores have hundreds and even thousands of categories.

Sorry, but the number of products or categories has nothing to do with so-called modern stores, the latter is a matter of personal taste and design. Though I agree having some more filters can be useful. In the meantime why not search the marketplace for a suitable extension?

**Comment by pemaier** [comment]
@mhcwebdesign Thank you for the comment. I also agree that there should not be a endless list of filters. But related to the common philosophy of our project we should give the project a basic filter set. This should be a basic list of filters for the main functionality within OpenCart - not more but also not less.

In Catalog: Categories, Products, Manufacturers, Downloads and Information
Common filters: Name, Store, Status
and in Products also: Model, Category, Manufacturer, Store, Price, Quantity

I think this is the basic list which is required for a comfortable work with small and big shops for our baseline of shop functionality.
For all additional filters (eg. Creation Date, Last Modification, ...) I agree this is an individual set for a marketplace extensions.

**Comment by stalker780** [comment]
@mhcwebdesign are you serious?
Why there are filters for products, reviews, orders?
Everyone could search for an extension on the Marketplace.

We can still use OC1.5 with extensions. No need in OC4.

Sorry for this sarcasm, but what you said can be applied to any OC update or feature.

Still there is a basic functionality which every store must have right out of the box. Otherwise all these product/category/order/customer lists are unusable.

**Comment by stalker780** [comment]
As to marketplace extensions... Extensions->Installer and Extensions->Extensions should have filters by name and status either :)

**Comment by danielkerr** [comment]
fine but seems like ur adding this for no reason

**Pull request merged**
