### PR TITLE
Fixed bug with unsetting parent category

### PR DESCRIPTION
**Pull request by adamlanningmolyneux**
Hyphens cannot be used in jQuery UI autocomplete, which results in the parent_id not being changed to 0 when you select 'None' as the parent category in the category form.

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
Not enough details, unable to reproduce your error.

**Comment by nexadomain** [comment]
_"You have half-baked knowledge of JS."_

_First_ of all, you haven't provided enough details.

_Second_, as you mentioned, "Hyphens cannot be used". 
_You need to sanitize your knowledge,_ Hyphens cannot be used in variable names in JS. However variable values can have any characters (provided: they are properly passed and escapes)

_Third_, the Changes you made, had a hyphen in value.
The hyphen was not creating any trouble.

Changes you made are not adding any significant value, so accepting/rejecting doesn't; matter much.
However, existing `$_['text_none']                     = ' --- None --- ';` looks much better

**Comment by danielkerr** [comment]
its not Query UI autocomplete

**Comment by danielkerr** [comment]
time waster!

**Comment by adamlanningmolyneux** [comment]
Your social skills leave something to be desired lol. I do not have a half-baked knowledge of JS, I have a half baked knowledge of jQuery UI because no one uses it, alas I am not wrong. The problem also exists on demo.opencart.com. 

To reproduce try to set a category with a parent to have the parent "--- None ---", save it, and the parent will not have changed. 

Daniel, it is using jQuery autocomplete, see line 225 of upload/admin/view/template/catalog/category_form.twig

And an apology please?

**Comment by danielkerr** [comment]
It's not jQuery UI. 

I wrote the code my self. Check common.js it's at the bottom.

**Comment by mhcwebdesign** [comment]
Actually, I can reproduce the same issue on OC 4.0.1.1. Will have to test it with the latest master branch, too, to see whether this issue still exists.

**Comment by mhcwebdesign** [comment]
Just tested it with today's master branch, this issue still exists!

**Comment by danielkerr** [comment]
> Just tested it with today's master branch, this issue still exists!

Did I say it was fixed! I spotted it. Will come up with a fix that keeps the current way none is

**Comment by nexadomain** [comment]
> To reproduce try to set a category with a parent to have the parent "--- None ---", save it, and the parent will not have changed. Try it with my code and it will work - I am correct. It's a pretty obvious bug - I didn't think I'd really need to elaborate any more than I did.
> 
> it is using jQuery UI autocomplete, see line 225 of upload/admin/view/template/catalog/category_form.twig
>

@adamlanningmolyneux 
Can you provide detailed steps to follow or screen recording?
I am unable to reproduce the same error in OC **4.0.1.1** .

I created a category with a parent "---None---" and saved it. It worked.
Again, I created another Category with the parent as first created category and saved it. It worked
Tried to modify the same too, and it saved without any issue.

You are very much confident about your solution, but you are not giving enough details to reproduce the error.
If you don't explain your issue properly, how do you expect us to know what you want?
We are not God to dig into your brain and know - what you want.
You are just forcing us to use your code without properly explaining what's wrong with the existing code.

**Comment by nexadomain** [comment]
Hey @danielkerr 
Can we trim all variables in easy way, while parsing language files?

**Comment by adamlanningmolyneux** [comment]
Removing spaces is a better solution, I presumed it was using jUI's autocomplete function due to the similar arguments.

It might be betterr to just have a button that removes the parent next to the select, rather than expecting the user to know to type out 'None'.

**Comment by danielkerr** [comment]
uj guys dont know what ur talking aboout. stop giving suggestions. ill fix it afrter i fix other stuff.

**Comment by adamlanningmolyneux** [comment]
Says the guy with a tenuous grasp on the English language. People literally helping you for free and that makes you angry, you need a holiday or something.

Spotted more errors I could help with but due to your bizarre outbursts my contributions end with this comment.

**Comment by danielkerr** [comment]
im not adding shit code because the people fixing think removing spaces is a fix.

the key is a string it needs to act like one

**Comment by danielkerr** [comment]
amateur time

**Pull request closed without merging**
