### PR TITLE
Update dashboard.php

### PR DESCRIPTION
**Pull request by osworx**
Prefix too much

### CODE REVIEW

**Comment by arnisjuraga** [comment]
@osworx seems you need to update your fork? This one has been already merged last year:
https://github.com/cartbinder/opencart/commit/ae1a6f4d6c76eeeaa63359ceb470d59633ec2c15

**Comment by osworx** [comment]
And why is it not applied until now (dev branch - Daniel worked 5 days ago) ?

**Comment by arnisjuraga** [comment]
You are right! In Dev branch, "somehow" this has been reverted/left behind. @danielkerr ?
https://github.com/opencart/opencart/commit/b517439118e66fb3997d8aa8360bd1eaecf7cb64#diff-9a55bced76a58d91eeaba72d751c0048L41

**Comment by danielkerr** [comment]
already fixed

**Pull request closed without merging**
