### PR TITLE
Added Timezone

### PR DESCRIPTION
**Pull request by eka7a**

### CODE REVIEW

**Comment by danielkerr** [comment]
big thx!

**Comment by eka7a** [comment]
you are welcome

**Comment by danielkerr** [comment]
Yo! why did you just take the code from arasta!!!!!

dont post anything from that piece s*** project!

**Comment by eka7a** [comment]
Hi,
these codes is not a special code to arastta. only variable that has changed names in arastta.
http://stackoverflow.com/a/17355238

**Comment by eka7a** [comment]
Also, arastta project, one to one by copying steal opencart codes.

**Comment by danielkerr** [comment]
ok sorry. but it looked very copied and pasted. we got sent a take down notice. and its not even their code!

**Comment by danielkerr** [comment]
I will add it back but will do it how i would do it.

**Comment by eka7a** [comment]
@danielkerr
I could not write an answer because I'm on holiday. I will revise to OpenCart and push again.

**Pull request merged**
