### PR TITLE
Fixed issue with json_decode helper function.

### PR DESCRIPTION
**Pull request by n4s3r**

### CODE REVIEW

**Comment by danielkerr** [comment]
no issue has been reported. are you fixing bugs that dont exist?

**Comment by n4s3r** [comment]
OpenCart json_decode function Remote PHP Code Execution https://github.com/opencart/opencart/issues/4220

**Comment by Rpent001** [comment]
I couldn't comment on the 4220 request, but the moron that posted the bug still has the instructional video up showing how to do it and who knows how many people copied and reposted it.  I'd push this fix ASAP and get the word out to site admins.  Maybe you should think about working in a messaging system like Magento has to alert users of important things like this.

**Comment by CoverUp** [comment]
83 original lines are now 830 lines, 10 times bigger, when you just have to work around the return $json line only.

**Pull request closed without merging**
