### PR TITLE
Important: New features/security for session library

### PR DESCRIPTION
**Pull request by v5mvidal**
Optimizes and ensures the security of session management, in addition to adding protection against: session hijacking and session fixation.

**Do not discard our contribution if you encounter any problems. Let us know that we will make the necessary adjustments.**

> Please, I ask you to test before accepting, as we carry out exhaustive tests, but nothing is perfect.

**New features:**

- 32 character for session_id.
- Session cookie management.
- Cookies HTTPOnly for default.
- Cookies Secure when HTTPS is detected.
- Cookie SameSite when PHP 7.3 or higher.
- Support for garbage collector with delay in execution.
- Support to check if the new session_id is already in use (generate new and unique).
- Support to regenerate session_id when: login, password change and data editing.
- Support to clear the session and invalidate the cookie when logoff.

### CODE REVIEW

**Comment by opencartstore** [comment]
> Optimizes and ensures the security of session management, in addition to adding protection against: session hijacking and session fixation.
> 
> **Do not discard our contribution if you encounter any problems. Let us know that we will make the necessary adjustments.**
> 
> > Please, I ask you to test before accepting, as we carry out exhaustive tests, but nothing is perfect.
> 
> **New features:**
> 
> * 32 character for session_id.
> * Session cookie management.
> * Cookies HTTPOnly for default.
> * Cookies Secure when HTTPS is detected.
> * Cookie SameSite when PHP 7.3 or higher.
> * Support for garbage collector with delay in execution.
> * Support to check if the new session_id is already in use (generate new and unique).
> * Support to regenerate session_id when: login, password change and data editing.
> * Support to clear the session and invalidate the cookie when logoff.

The second parameter of the constructor must become mandatory, otherwise the code will break if some smart guy instantiates the Session object without passing the Registry object.

Please, change:
`public function __construct($adaptor, $registry = '') {`

For this:
`public function __construct(string $adaptor, Registry $registry) {`

The conditional `if ($registry)` can then be removed

**Comment by v5mvidal** [comment]
The constructor was kept in the original pattern to facilitate acceptance by Daniel, after the pull is approved, he can make the change if he deems it necessary.

We are happy that you have evaluated. =)

**Comment by opencartstore** [comment]
I hope Daniel accepts or at least looks at his PR.

This was being needed in the OC.

**Comment by straightlight** [comment]
Too repetitive. The:

```$this->load->controller('common/session');```

could possibly return all these calls from one controller rather than handling all these since we might never know what to expect with 3rd party extensions playing with search lines that may also affect those sessions once we see the results.

**Comment by cgcmart** [comment]
#8133
#8141

**Pull request closed without merging**
