### PR TITLE
Fix: removed unnecessary calls trim

### PR DESCRIPTION
**Pull request by Grumvol**
Remove spaces in the class Request

	public function clean($data) {
		if (is_array($data)) {
			foreach ($data as $key => $value) {
				unset($data[$key]);

				$data[$this->clean($key)] = $this->clean($value);
			}
		} else {
			$data = trim(htmlspecialchars($data, ENT_COMPAT, 'UTF-8'));
		}

		return $data;
	}

### CODE REVIEW

**Comment by condor2** [comment]
Using trim in request will broke currency. If you add a space before symbol and save and edit again, the space is removed.

So you can't use something like this:

`4 Euro`

**Comment by condor2** [comment]
When you remove trim from controllers. You can save using only white spaces. So is needed another method of warning.
Screenshot_2020-08-11_08-46-25

**Comment by Grumvol** [comment]
You cannot specify a space as the name of an attribute group, there is validation

**Comment by condor2** [comment]
There is no validation if you remove trim from controllers...
I added only spaces. Branch is cloned yesterday.

**Comment by Grumvol** [comment]
It's strange. Trim is used in the clean method of the Request class. Check file system/library/request.php, there should be a line

    $data = trim(htmlspecialchars($data, ENT_COMPAT, 'UTF-8'));

**Comment by condor2** [comment]
I know about trim in request but need to be removed untill currency symbol space is fixed.

**Comment by Grumvol** [comment]
The space before the currency symbol needs to be implemented in a different way. Storing a space at the beginning of a line in the database is not a good idea.

**Pull request closed without merging**
