### PR TITLE
Update twig.php

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
I can't see any changes or bugfixes here!

**Comment by stalker780** [comment]
@mhcwebdesign TheCartpenter better should not fix anything LOL

https://github.com/opencart/opencart/commit/fd3697b415668c5ac8117aa127dd1d695ea95ba8
https://github.com/opencart/opencart/commit/2d2262d4ab29c71b7a2053e8d6e37035141e8dd9
https://github.com/opencart/opencart/pull/13072/commits/97f13af30859c3ae146e52e26c3d199721345041

**Comment by chulcha** [comment]
> I can't see any changes or bugfixes here!

spam detected (like everything else from him)

**Comment by mhcwebdesign** [comment]
If it is just documentation changes, why not run something the phpdoc for all the files and then just create one pull request for this? And then focus on actual testing and bugfixes.

**Comment by TheCartpenter** [comment]
All I see in these posts are the so many times the people complains about. Yet, what I haven't seen yet, is who do take initiative on making those changes, regardless of the ways of proposals to submit those changes, prior to my commits.

**Comment by stalker780** [comment]
> If it is just documentation changes, why not run something the phpdoc for all the files and then just create one pull request for this? And then focus on actual testing and bugfixes.

Private: Why are we sweeping the parade ground with a crowbar?
Sergeant: I don’t need this place to be clean, I need you to get tired

**Comment by TheCartpenter** [comment]
> > If it is just documentation changes, why not run something the phpdoc for all the files and then just create one pull request for this? And then focus on actual testing and bugfixes.
> 
> Private: Why are we sweeping the parade ground with a crowbar? Sergeant: I don’t need this place to be clean, I need you to get tired

Simple. Because you're the one chasing the people that shares the change rather than helping the cause.

**Comment by mhcwebdesign** [comment]
It's still the same doc here in particular file:
```

/**
	 * Constructor
	 *
	 * @param    string  $adaptor
	 *
	 */
```

As I said, why not use a tool like phpdoc for all the files, and have it all done in one go? Then we'll have a chance to do some actual testing, including OCMod-based modifications in extensions, and finding genuine bugs.

**Comment by TheCartpenter** [comment]
> It's still the same doc here in this particular file:
> 
> ```
> 
> /**
> 	 * Constructor
> 	 *
> 	 * @param    string  $adaptor
> 	 *
> 	 */
> ```
> 
> As I said, why not use a tool like phpdoc for all the files, and have it all done in one go? Then we'll have a chance to do some actual testing, including OCMod-based modifications in extensions, and finding genuine bugs.

The tools I am using are nobody's Business. As you have been told before, pull requests aren't only about posting bug reports, it is about posting code changes which is exactly what I am doing.

Besides, I don't see anybody complain when a contributor posts a pull requests and also duplicates commits into the issues tab to point out pull requests afterwards.

Therefore, since Daniel rather prefer to have split files posted in their own commits to ease the task and decisions he has to make, this is the way I have always posted them, the way I am still posting them as I will keep posting them accordingly. OCMod as nothing to do with that.

**Comment by TheCartpenter** [comment]
Furthermore about OCMod, you are one of the people who objected about the fact that the engine was being re-integrated from the Discussions tab. While you are also handling the maintenance branch, and while I haven't shared my opinion on that since I rather decided to remain silent until now, I am foreseeing this as a bad example on your behalf since you are also encouraging people to go the other way around with OCMod while you are also maintaining the core project of OC v3.0.x.x where the OCMod is still built-in.

**Comment by mhcwebdesign** [comment]
@TheCartpenter: I am not using OCmod myself, but you missed the point: OCmod relies on XML-based modifications of the underlying source code PHP and template files, and because of your many daily unneeded cosmetic source changes nobody will be able to start developing modification extensions using this tool, not at least until things have settled down.

And yes, nobody understands why you can't use combined pull-requests, especially for the generated PHP docs, couldn't this be done in one go?

**Comment by ADDCreative** [comment]
@TheCartpenter This pull request does not comply with the OpenCart coding standard regarding indentation.
https://github.com/opencart/opencart/wiki/Coding-Standards#indentation

It will make a mess for any editors that aren't using the same tab size as you.

**Pull request closed without merging**
