### PR TITLE
Added backward escaped quotes - catalog/model/account/voucher_theme.php file.

### PR DESCRIPTION
**Pull request by TheCartpenter**
Added backward escaped quotes.

### CODE REVIEW

**Comment by eka7a** [comment]
@TheCartpenter Please submit in one pull request for same changes.

**Comment by TheCartpenter** [comment]
This file only contains one change.

**Comment by eka7a** [comment]
https://github.com/opencart/opencart/pull/9180
https://github.com/opencart/opencart/pull/9179
https://github.com/opencart/opencart/pull/9178
https://github.com/opencart/opencart/pull/9177
...........
and others pull requests. These are all the same changes.

**Comment by TheCartpenter** [comment]
Not sure how to merge them, that's why I post them one-by-one.

**Comment by TheCartpenter** [comment]
May be like this:

https://github.com/opencart/opencart/pull/9180
https://github.com/opencart/opencart/pull/9179
https://github.com/opencart/opencart/pull/9177
https://github.com/opencart/opencart/pull/9176
https://github.com/opencart/opencart/pull/9175
https://github.com/opencart/opencart/pull/9174
https://github.com/opencart/opencart/pull/9173
https://github.com/opencart/opencart/pull/9172
https://github.com/opencart/opencart/pull/9171
https://github.com/opencart/opencart/pull/9170
https://github.com/opencart/opencart/pull/9169
https://github.com/opencart/opencart/pull/9168
https://github.com/TheCartpenter/opencart/commit/208918e2186b3634fe832a7bfe7923fd13fd04a7

**Comment by cgcmart** [comment]
It's only way to make all changes in one commit and use git push in one your depository from your local work station, then pull a request from your depository.

**Comment by TheCartpenter** [comment]
Ok. I think I got it now. I pushed one of the change as a test and now showing here: https://github.com/TheCartpenter/opencart/commit/ec92cc7eb1c8e808415f1441b87d677bf550d490

**Comment by TheCartpenter** [comment]
I also managed to download the changes from the master branch instead of updating manually: https://github.com/TheCartpenter/opencart/commits . My changes are also implicit in this commit list.

**Comment by TheCartpenter** [comment]
Ok, figured it out. It seem, for now, the changes are reflected on pull request: #9167 .

**Comment by TheCartpenter** [comment]
@eka7a: Ok, it's done into one commit now: https://github.com/TheCartpenter/opencart/commit/670625a6e7ed603b377e8ded17c11b676e3dfb90 .

**Comment by eka7a** [comment]
@TheCartpenter The commits right now in your repo. You must submit a pull request for commits.

**Comment by TheCartpenter** [comment]
The rest of the patches are over there. You want them, merge them all you want.

**Comment by TheCartpenter** [comment]
It says opencart/opencart commits on pull request #9167 already: https://github.com/opencart/opencart/pull/9167/commits/670625a6e7ed603b377e8ded17c11b676e3dfb90 .

**Pull request closed without merging**
