### PR TITLE
Config Iterator & ArrayAccess interface.

### PR DESCRIPTION
**Pull request by unckleg**
With implemented [Iterator interface](http://php.net/manual/en/class.iterator.php) developers will have ability to iterate over config items (key -> val) and that will ease development very much, primarily data variable population:

**Before:**
```php
    $data['fraud_fraudlabspro_status'] = $this->config->get('fraud_fraudlabspro_status');
    $data['fraud_fraudlabspro_simulate_ip'] = $this->config->get('fraud_fraudlabspro_simulate_ip');
    $data['fraud_fraudlabspro_reject_status_id'] = $this->config->get('fraud_fraudlabspro_reject_status_id');
```

**After:**
```php
    foreach ($this->config as $key => $value) {
        if (strpos($key, 'fraud_fraudlabspro') !== false) {
            $data[$key] = $value;    
        }
    }
```

Also with implemented [ArrayAccess ](http://php.net/manual/en/class.arrayaccess.php)interface developers will have ability to access object in context of array.

**Before:**
```php
    $data['fraud_fraudlabspro_status'] = $this->config->get('fraud_fraudlabspro_status');
    $data['fraud_fraudlabspro_simulate_ip'] = $this->config->get('fraud_fraudlabspro_simulate_ip');
    $data['fraud_fraudlabspro_reject_status_id'] = $this->config->get('fraud_fraudlabspro_reject_status_id');
```

**After:**
```php
    $data['fraud_fraudlabspro_status'] = $this->config->fraud_fraudlabspro_status;
    $data['fraud_fraudlabspro_simulate_ip'] = $this->config->fraud_fraudlabspro_simulate_ip;
    $data['fraud_fraudlabspro_reject_status_id'] = $this->config->fraud_fraudlabspro_reject_status_id;
```

**No BC breaks & interfaces are presented with PHP 5 so there will be no problem with older versions of OC.**

### CODE REVIEW

**Comment by unckleg** [comment]
@danielkerr What core team thinks 'bout this ?

**Comment by unckleg** [comment]
@danielkerr ping

**Comment by straightlight** [comment]
One problem with this solution is the ->get public variable that is no longer visible as compared to the one that's been developed in the library.

**Comment by straightlight** [comment]
The fraudlabspro extension/extension has been removed from the master branch and from the pre-release version. Therefore, this commit will now be closed.

**Comment by danielkerr** [comment]
no need for  Iterator interface. i preffer to use arrays.

**Comment by unckleg** [comment]
> The fraudlabspro extension/extension has been removed from the master branch and from the pre-release version. Therefore, this commit will now be closed.

_fraudlabspro_ extension was just an example.

> no need for Iterator interface. i preffer to use arrays.

Arrays are not iterable, developers must explicitly access any of array config key, outcome of that is thousands of unnecessary lines of code, using Iterator interface (if you know the purpose of the same) is a big plus and help for developing any of opencart extensions/stuff.

**Comment by unckleg** [comment]
Anyhow, @danielkerr you are widely know (in opensource community) as person with stubbornness and arrogance and everything but not developer.

Opencart will stay in the history dustbin, you should remove PR & Issue access from this repo since this repo is everything but not opensource.

**Comment by danielkerr** [comment]
Arrays are not iterable, developers must explicitly access any of array config key, outcome of that is thousands of unnecessary lines of code, using Iterator interface (if you know the purpose of the same) is a big plus and help for developing any of opencart extensions/stuff.

That's only in your mind. Also opencart has the highest number of live sites more than magento

**Pull request closed without merging**
