### PR TITLE
Suggestion: current password should be validated if new password is created on change password page.

### PR DESCRIPTION
**Pull request by prabhatkumaroc082**

### CODE REVIEW

**Comment by prabhatkumaroc082** [comment]
@jeffreyeng-opencart please check it once.

**Comment by jeffreyeng-opencart** [comment]
@prabhatkumaroc082: Since this is a suggestion and not a fix, I cannot make approval of the merge. These changes still has to go through with Daniel.

**Comment by prabhatkumaroc082** [comment]
@jeffreyeng-opencart Ok, Waiting for Mr. Daniel's response about this feature.

**Comment by jeffreyeng-opencart** [comment]
@prabhatkumaroc082: Thank you for your understanding.

**Comment by straightlight** [comment]
The master branch uses a new password algorithm to verify passwords. A user-defined validation is no longer required. Therefore, this commit will now be closed.

**Pull request closed without merging**
