### PR TITLE
Fixed Additional Alert Emails

### PR DESCRIPTION
**Pull request by OpenCartAddons**
Replaced `config_alert_mail` with `config_mail_alert_mail` as per settings page.

### CODE REVIEW

**Comment by arnisjuraga** [comment]
#5249 
#4757
#5228

**Comment by pnair39** [comment]
Just to make sure please double these paths are correct since; I downloaded a fresh copy of 2.3.0.2 just to compare on test site.  **mail folder does not exist under /catalog/controller/ on the paths below**

/catalog/controller/**mail**/register.php
/catalog/controller/mail/affiliate.php
/catalog/controller/mail/order.php
/catalog/controller/mail/register.php

**Comment by OpenCartAddons** [comment]
This PR is for the dev branch

**Comment by kriziw** [comment]
Is there any way to solve this in the current 2.3.0.2 version until the next patch/version is released?

Thanks,

Kristofer

**Comment by ADDCreative** [comment]
The changes submitted to the master branch here should work.
https://github.com/opencart/opencart/pull/4757

**Comment by pnair39** [comment]
@kriziw 2.3.0.2 correct paths https://github.com/pnair39/opencart-fixes/

This covers the non working parts of opencart additional alerts.,

**Comment by kriziw** [comment]
@pnair39 Thank you!!! :)

**Comment by kriziw** [comment]
I just checked your fix. Those lines are already there. So unfortunatly not resolved.

**Comment by pnair39** [comment]
@kriziw Yes, that is correct you still use make the changes according to the above Dev branch info above.
example:

**orders:**
https://github.com/opencart/opencart/pull/5259/commits/7c8d752eb46e819e356a6bc67da65c45cf5bb15f
**review:**
https://github.com/opencart/opencart/pull/5259/commits/8ed57155c36a304c2bb7f69ff5c606b0bcea5c9c

and there are no changes required for registration since it works correctly.

**Pull request merged**
