### PR TITLE
[OC 3.0.x] Fix affiliate custom fields in admin

### PR DESCRIPTION
**Pull request by MarvinKlein1508**
This pull request fixes some issues with custom fields within customer_form.twig and controller/customer.php within admin.

The custom fields for affiliate have been displayed based on the account custom fields. Furthermore the index "affiliate" for the post data has been missing.

### CODE REVIEW

**Comment by MarvinKlein1508** [comment]
Added commit [9df9d6f](https://github.com/opencart/opencart/pull/11457/commits/9df9d6ff17a9b4950c44e94ee057ed6981657df9) to fix custom fields on `editAffiliate`

**Comment by MarvinKlein1508** [comment]
Added commit [0a19f9e](https://github.com/opencart/opencart/pull/11457/commits/0a19f9e141844a81d18ca1b6ca15b9033ff9b86b) which fixes the saving on customer create via admin

**Comment by MarvinKlein1508** [comment]
@mhcwebdesign this only applies to custom fields within the affiliate section. It is for all types of custom fields. Right now you cannot edit them within admin panel. This commits fixes this behaviour.

To reproduce:
1. Install OC 3 shop based on maintenance branch
2. Activate any custom fields for affiliate
3. try to create a customer with affiliate in admin / edit affiliate info for customer in admin


You will see Opencart won't save the custom fields because someone has messed up with this. The create method tries to insert `$data['custom_field']` which holds all information for custom_fields based on account and not on affiliate.

The edit function tries to save 
`$data['custom_field']['affliate']` which never gets set because a) the form has wrong names for those custom fields (missing `['affiliate']` and b) those fields display data again based on account custom fields and not on affiliate.

I've tested this changes on a local store:
1. Created a new customer through admin with affiliate data
2. Updated affiliate data for customer in admin
3. For all types of custom_fields which can be specified

**Comment by danielkerr** [comment]
for version 3.x 

https://github.com/opencart/opencart-3

**Comment by MarvinKlein1508** [comment]
@danielkerr I've just checked the repo you've mentioned and installed it in my local server. This version is completely different from the current releases opencart 3. The affiliate system isn't bundled with the customer_form.twig anymore. Moreover I cannot register as an affiliate as a customer.
TypeError: Cannot assign null to property Router::$error of type object in /home/webpages/lima-city/marvinkleinmusic/opencart/system/engine/router.php on line 75

Could you please explain three things for me?
1.) For what is this Maintenance branch then?
2.) Why is the code from the opencart 3 repo so different from the current releases opencart 3 version?
3.) Will you release this edited opencart 3 version with the bug fixes ?

**Comment by mhcwebdesign** [comment]
@MarvinKlein1508 : I asked the same question a while ago here: https://github.com/opencart/opencart/discussions/10685

As far as I understand, the 3.0.x.x_Maintenance branch is closely backwards compatible with 3.0.3.8, it mainly contains bugfixes and support for PHP 8. The Opencart-3 repository appears to have introduced many changes which have nothing to do with bugfixes, and will therefore be different from previous 3.0.3.x releases.

**Comment by MarvinKlein1508** [comment]
@mhcwebdesign this is really confusing. The maintenance branch has so many bugfixes which haven't been released yet. The OC3 repository instead fixed the SQL lines for the affiliate system (such as my commits here do). But these fixes from the opencart-3 repository are not shown within the maintenance branch.  Moreover the affiliate system in the other repository is completly broken.

In my opinion the current Mainteneance branch is the current working version for Opencart 3. This one can be installed without any issues (except for the broken affiliate system).

This should be cleared @danielkerr where should we create pull requests to fix bugs in Opencart 3?

**Comment by mhcwebdesign** [comment]
@MarvinKlein: I finally had a chance to test your changes, and they seem to work fine, hence I added them to the 3.0.x.x._Maintenance branch.

As regards the question whether to use 3.0.x.x_Maintenance branch or the new opencart-3 repository:

I think the new opencart-3 repository has more changes beyond a simple maintenance and bugfixes scope, think of it as an upcoming OpenCart 3.1, as opposed to 3.0.x.x_Maintenance branch which will be more like a future 3.0.3.9 (basically a 3.0.3.8 with bugfixes and PHP 8 support).

**Pull request closed without merging**
