### PR TITLE
Correct spaces around assigments

### PR DESCRIPTION
**Pull request by AJenbo**
This was done using php-cs-fixer's binary_operator_spaces rule. Once all outstanding PR regarding code formatting have been merged future changes can be checked for issues in GitHub action and developers can run the tool locally to fix any formatting issues with there code.

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
Almost every day I get between 50 to 100 email notifications from you or TheCartpenter about these little changes. Can't you do them all in one go, using a suitable PHP source code / docs format tool? After this we can then start with the real testing and bugfixes. And hopefully Daniel will first do a public 4.0.2.4.beta release, to get more public users onboard for testing, before the final 4.0.2.4 release.

**Comment by AJenbo** [comment]
@mhcwebdesign I'm doing this exactly solve that issue, cause it way also annoying for me. I have done one PR for each rule in php-cs-fixer to get the whole project to comply with a PSR-12 like configuration so that the tool can be applied in general going forward and we can avoid PRs like the ones you are complaining about.

The reason it's split up in rules and sections is so that Daniel can better evaluate what he wants the style to be like so I don't just force something on the project. These where all done in one day, and for the whole project so you won't be getting any more regarding style changes from me. I actually stated all of this in the PR description, maybe you didn't see it?

**Comment by AJenbo** [comment]
@osworx @mhcwebdesign you might consider changing your settings regarding what notifications you get from the project:

image

**Comment by mhcwebdesign** [comment]
I don't have this detailed Notifications menu on github settings. All it offers is 

```
Select notification channels
    On GitHub
    Email

```

**Comment by AJenbo** [comment]
You configure it for each project on the project page: https://github.com/opencart/opencart

image

**Comment by mhcwebdesign** [comment]
OK, thanks, found it.

**Comment by osworx** [comment]
> @osworx @mhcwebdesign you might consider changing your settings regarding what notifications you get from the project:

What do you think I have - since a looong time (as one of the others here started with PRs for each comma a while ago!).

While I am really happy what you have already done (and there could be a few more tests and further tasks for automatisations like in other projects), it's boring to get 100s of notifications each day.
One reason I had OC (especially the 4.x branch) a while in the background (beside it's still not ready for production usage after 1 1/2 years!).

**Comment by AJenbo** [comment]
> What do you think I have

All activities :shrug:

I can tell there are lots of frustrations in this community, I have tried helping out with some of that but changing things takes time. I also find the tone here to be generally pretty hostile, not a very welcoming place all in all.

> there could be a few more tests

I'm not sure it's going to get much further then what I have already done as further work to make the system testable was rejected https://github.com/opencart/opencart/pull/12958 I'm going to see if I can write a dynamic rule for this but if that doesn't work or is also rejected then I won't be able to get any further with that.

> further tasks for automatisations like in other projects

Your commenting on my effort to set one up for code style

**Comment by osworx** [comment]
@AJenbo Believe me (and others), after 13 years with Daniel, guess we know him all very well.
The top users here (and in the forum) had all (internal) discussions with him, some ended good, some bad.

Nevertheless, while he considers something not (very) useful, he has made a very good shopping system at all.
One reason why a few of us stay with him.
Because those believe, that it could be made better.

What the whole project badly miss, are guidelines and clearly defined tasks, time lines and side projects (e.g. time enough and early published beta releases to test them before going live).
Guess many of us tried to help him in some way - finally it's his decision ..

**Comment by IP-CAM** [comment]
#I also find the tone here to be generally pretty hostile, not a very welcoming place all in all.

Well, Opencart is not about making friends, for most people, especially for Newcomers, it's sole purpose is, to hopefully generate income, by use of free Software as well as possibly free Support. 

But one should better not expect, to find lots of Friends around OC, just waiting, to be of free help, OC is all about generating income, in one or the other Way, for most everybody involved.  And as further the Project gets, the more commercial it will be. And that leaves not much room for free Assistance for those, expecting to have found free Heaven, to make them rich and famous in the Online Business.

**Comment by AJenbo** [comment]
Well that doesn't sound to interesting then. I have no interest in the commercial side of it, I'm just interested in open source and the collaborative side of things. I just came here to see how other project work and solve there problems.

**Comment by IP-CAM** [comment]
>  I have no interest in the commercial side of it, I'm just interested in open source and the collaborative side of things.

Well, I am in a similar situation. I was only looking for some new coding excitement, after EveryAuction closed down it's operation in 2013, and Opencart v.1.5.x was an interesting project at that time to actively participate. And I'm still around, despite of the fact, that it's not half as much fun anymore, as it used to be, mainly due to the fact, that OC grew more and more into a strictly commercial Enterprise, for most everyone around. And from that point of view, it's understandable, that 'free' Support is no longer a primary goal, but more and more a thing out of the past. 
So much to this, take it easy and not personal !

**Pull request merged**
