### PR TITLE
Supported multiple files upload for common/filemanager

### PR DESCRIPTION
**Pull request by khanhicetea**
I think the most inconvenience of OpenCart Admin Panel is uploading only 1 file per time. Hope this PR can help to resolve that :)

### CODE REVIEW

**Comment by CoverUp** [comment]
Nice

**Comment by danielkerr** [comment]
can you fix the conflicts and i will merge it.

**Comment by khanhicetea** [comment]
@danielkerr I just fixed the conflicts :smiley:

**Comment by danielkerr** [comment]
a better solution would be file[]

**Pull request closed without merging**
