### PR TITLE
[3.0.x.x] Added SCSSPHP 8.1 warning fix

### PR DESCRIPTION
**Pull request by condor2**
https://github.com/opencart/opencart/blob/master/upload/admin/controller/startup/sass.php#L18

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
Thank you for pointing it out.

The SCSSPHP is a 3rd party vendor script integrated into OpenCart via composer.

So rather then directly patching it, could you look into a newer version of scssphp (e.g. at gitgub.com/scssphp) which is compliant with PHP8.1?  Then we can just update the composer.json and do a refresh of the vendor plugins.

**Comment by condor2** [comment]
With updated SCSSPHP you will get deprecated function because the function was changed

The "ScssPhp\ScssPhp\Compiler::compile" method is deprecated. Use "compileString" instead

https://github.com/scssphp/scssphp/blob/master/src/Compiler.php#L345

**Comment by mhcwebdesign** [comment]
Thanks for your explanations. Will the updated SCSSPHP still work with bootstrap 3.3.5?

**Comment by condor2** [comment]
yes

**Comment by condor2** [comment]
But if you needed I can give you this version with jquery 3.6.0, summernote 0.8.20, bootstrap 3.4.1

**Comment by mhcwebdesign** [comment]
I'll try it all out on my local test server first later today or tomorrow.

**Comment by mhcwebdesign** [comment]
SCSSPHP now updated, along with your suggested change, see https://github.com/opencart/opencart/pull/10684

**Pull request closed without merging**
