### PR TITLE
Bootstrap 5.2.1 fix tooltips (another attempt)

### PR DESCRIPTION
**Pull request by stalker780**
https://github.com/opencart/opencart/pull/11759

No JS errors now. Tooltips are shown every time they are hovered.

Checked in Firefox and Chrome.

Sometimes, when you slide very fast between multiple buttons, a tooltip looses it's style and position. But at least this is not so noticeable as current implementation when tooltips are always displaced on second hover. This looks like a BS tooltip or popover bug.

### CODE REVIEW

**Comment by danielkerr** [comment]
i can not see any issue. can u do a recording of what is happening.

**Comment by stalker780** [comment]
> i can not see any issue. can u do a recording of what is happening.

Just try to hover a button, then leave it, and hover again.
On second hover there is no tooltip. It is placed under footer.
I will try to record video when I get to PC

**Comment by stalker780** [comment]
https://user-images.githubusercontent.com/6297070/193430130-08dbb7e9-70db-4857-a8f1-1939fc59a9fc.mp4

Check this video. Pay attention to page scrollbar.

I have added screenshots here before https://github.com/opencart/opencart/pull/11759

**Comment by stalker780** [comment]
https://user-images.githubusercontent.com/6297070/193430420-154598d0-773d-4458-8330-37b665417883.mp4

Same for frontend

**Comment by stalker780** [comment]
Today was released BS 5.2.2
It contains some fix for dynamic tooltips.
I will check it today.

**Comment by stalker780** [comment]
No changes for BS 5.2.2. 
Same behavior.
So this fix is valid for latest BS too.

**Comment by stalker780** [comment]
Hi @danielkerr 
Is something wrong with this PR? This fix works fine on my test store after 2 weeks of testing.
If you do not plan to use it please close. 
Otherwise I cannot use GitHub Desktop with OC project. All OC PRs are committed in this PR turning it into a mess.

**Pull request merged**
