### PR TITLE
Add option to disable affiliate marketing

### PR DESCRIPTION
**Pull request by falconkirtaran**
Adds an option to shut affiliate marketing off.  Things related to it will still be displayed in the admin panel if it's off, but affiliate links won't do anything to orders (so commission won't be tracked) and the signup and edit stuff will be disabled and links to it will not be displayed.  It can be turned on and off again without any persistent changes, e.g. turning it on will reactivate old affiliate accounts and start tracking commission on new orders.

### CODE REVIEW

**Comment by falconkirtaran** [comment]
I updated this to resolve a merge conflict resulting from the admin en-gb language file update.

**Comment by falconkirtaran** [comment]
And, updated again because I accidentally removed a line while merging!

**Comment by eka7a** [comment]
Added
https://github.com/opencart/opencart/commit/70f97e50bf5c96388f2cd905293aa4759692a358

**Comment by Khnaz35** [comment]
Is this method work with latest OC version with 3.0.3.6?

**Comment by drave** [comment]
No, it was never merged..

**Comment by isbullaml** [comment]
hi, is it merged to latest version ?

**Comment by aimiliano** [comment]
doesnt work with 3.x :P 
needs re-merge / re-make with 3.x and 4.x

**Pull request closed without merging**
