### PR TITLE
oc_punycode

### PR DESCRIPTION
**Pull request by stalker780**
https://github.com/opencart/opencart/issues/9755

### CODE REVIEW

**Comment by stalker780** [comment]
yep. this does not work with all emails. need another solution

**Comment by stalker780** [comment]
here. now it works correctly with emails

```
latin@email.com -> punycode: latin@email.com -> filter_var result: true

ghfh@renangonçalves.com -> punycode: ghfh@xn--renangonalves-pgb.com -> filter_var result: true

用户@例子.广告 -> punycode: xn--zouo53b@xn--fsqu00a.xn--4rr70v -> filter_var result: true

ಬೆಂಬಲ@ಡೇಟಾಮೇಲ್.ಭಾರತ -> punycode: xn--3rc7fby1h@xn--xscd4bq2d9bd3c.xn--2scrj9c -> filter_var result: true

अजय@डाटा.भारत -> punycode: xn--l1b0cxc@xn--c2bd1gb.xn--h2brj9c -> filter_var result: true

квіточка@пошта.укр -> punycode: xn--80adxbtx0b7h@xn--80a1acn3a.xn--j1amh -> filter_var result: true

χρήστης@παράδειγμα.ελ -> punycode: xn--jxas2agdgr@xn--hxajbheg2az3al.xn--qxam -> filter_var result: true

Dörte@Sörensen.example.com -> punycode: xn--drte-5qa@xn--srensen-90a.example.com -> filter_var result: true

коля@пример.рф -> punycode: xn--j1aci3e@xn--e1afmkfd.xn--p1ai -> filter_var result: true

support@ツッ.com -> punycode: support@xn--9ckb.com -> filter_var result: true
```

**Comment by stalker780** [comment]
If needed we can create a separate function `oc_email_validate` and use it instead of `filter_var`. 
This will reduce repeated code in controllers. Also easier to maintain in the future.

Daniel, please let me know if I need to modify this PR.

**Comment by TheCartpenter** [comment]
By returning an imploded email, it will return a user-defined email address string rather than a validated email...

**Comment by stalker780** [comment]
@TheCartpenter oc_punycode is intended to encode international email. Not to validate.

Anyway I will prepare another PR.

**Pull request closed without merging**
