### PR TITLE
https://github.com/opencart/opencart/issues/8654

### PR DESCRIPTION
**Pull request by ClayRabbit**
Issue #8654 still present.
Fixed in 2020 but lost?

### CODE REVIEW

**Comment by ADDCreative** [comment]
You could block that one exception. But what about all the other parts of the code where PHP will generate, exceptions, errors, warings, ect. which could have sensitive data in.

You need make sure display errors in set to off in all 3 places. Your PHP settings, in system/config/default.php and in the settings. Not only can this cause minor notices and warnings to cause bigger errors, it can also be a security risk.

1. In your PHP settings make sure display_errors is set to Off. Use phpinfo() to check. It should be off by default, but there are lots of rubbish hosts out there.

2. In system/config/default.php set error_display to false.

3. In your OpenCart Setting on the server tab set Display Errors to No.

**Comment by ClayRabbit** [comment]
I agree in general, but:
1. Yes, lots of rubbish hosts.
2. Source file modification will be lost on update.
3. OpenCart Setting has no effect on that particular issue.

**Comment by ClayRabbit** [comment]
MySQL DB password will be revealed (inside stack trace) on DB connect error if display_errors = On
https://onlinephp.io/c/698e6
`Fatal error: Uncaught Exception: Error: Could not make a database link using db_user@127.0.0.1! in /home/user/scripts/code.php:21
Stack trace:
#0 /home/user/scripts/code.php(27): DB\MySQLi->__construct('127.0.0.1', 'db_user', 'db_password', 'db_name')
#1 {main}
  thrown in /home/user/scripts/code.php on line 21`

**Comment by mhcwebdesign** [comment]
@ClayRabbit: There is no scripts/code.php in OpenCart. 

In the worst case scenario, when the MySqli connection fails, and **display_errors** is turned on, it would display something like this:

```
Fatal error: Uncaught mysqli_sql_exception: xxxxxxx in /home/juergen/htdocs/opencart-3-0-x-x-maintenance/upload/system/library/db/mysqli.php:8 
Stack trace: 
#0 /home/xxxx/htdocs/opencart-3-0-x-x-maintenance/upload/system/library/db/mysqli.php(8): mysqli->__construct() 
#1 /home/xxxx/htdocs/opencart-3-0-x-x-maintenance/upload/system/library/db.php(31): DB\MySQLi->__construct() 
#2 /home/xxxx/htdocs/opencart-3-0-x-x-maintenance/upload/system/framework.php(80): DB->__construct() 
#3 /home/xxxx/htdocs/opencart-3-0-x-x-maintenance/upload/system/startup.php(104): require_once('...') 
#4 /home/xxxx/htdocs/opencart-3-0-x-x-maintenance/upload/index.php(19): start() 
#5 {main} thrown in /home/xxxx/htdocs/opencart-3-0-x-x-maintenance/upload/system/library/db/mysqli.php on line 8

```
No password is revealed.
 
Issue closed.

**Comment by ADDCreative** [comment]
Sorry, you are right about the password being in the stack trace,. I had set zend.exception_ignore_args to On, as required for a production environment.

However, as I have pointed out, why just change the one exception. What about this one, that reveals the same stack trace, and all the possible others.
https://github.com/opencart/opencart/blob/98fc45171cfb5e52a3a60b96009bcf7bd058d28d/upload/system/library/db.php#L33

You need to use correctly configured hosting or properly handle all exceptions.

**Comment by ClayRabbit** [comment]
@mhcwebdesign 
> @ClayRabbit: There is no scripts/code.php in OpenCart.

Sure, because it's just a demonstration with similar code on php sandbox.

**DB password is revealed** on DB connect error if **display_errors** is turned On and **zend.exception_ignore_args** not turned Off
https://oc3.clayrabbit.ru/

<pre><b>Fatal error</b>:  Uncaught Exception: Error: Could not make a database link using db_user@localhost! in /home/clayrabb/domains/clayrabbit.ru/public_html/oc3/system/library/db/mysqli.php:19
Stack trace:
#0 /home/clayrabb/domains/clayrabbit.ru/public_html/oc3/system/library/db.php(31): DB\MySQLi-&gt;__construct('localhost', 'db_user', 'dp_pwd', 'db_name', '3306')
#1 /home/clayrabb/domains/clayrabbit.ru/public_html/oc3/system/framework.php(80): DB-&gt;__construct('mysqli', 'localhost', 'db_user', 'dp_pwd', 'db_name', '3306')
#2 /home/clayrabb/domains/clayrabbit.ru/public_html/oc3/system/startup.php(104): require_once('/home/clayrabb/...')
#3 /home/clayrabb/domains/clayrabbit.ru/public_html/oc3/index.php(19): start('catalog')
#4 {main}
  thrown in <b>/home/clayrabb/domains/clayrabbit.ru/public_html/oc3/system/library/db/mysqli.php</b> on line <b>19</b></pre>

> In other words: It still won't show the password! So what kind of badly configured webhost do you need in order to reveal the password? Seriously, I don't think it's an issue.

Just any host with display_errors: On (by default or left by accident) and without zend.exception_ignore_args (or PHP version < 7.4)

**Pull request closed without merging**
