### PR TITLE
Resolved reward validation issue

### PR DESCRIPTION
**Pull request by webkul-dilip**
Added suggestion https://github.com/opencart/opencart/issues/8704

### CODE REVIEW

**Comment by straightlight** [comment]
For the core, this fix does make sense. The only differences will be with developed extensions where other var types may come along.

**Comment by webkul-dilip** [comment]
> For the core, this fix does make sense. The only differences will be with developed extensions where other var types may come along.

>> Okay, We will change the code

**Comment by straightlight** [comment]
Idealistically speaking, however, based on your suggestion, a shorter code could be used to validate the voucher POST:

```if (!isset($this->request->post['reward']) || !is_numeric($this->request->post['reward']) || ($this->request->post['reward'] <= 0)) {```

for:

```if (!isset($this->request->post['reward']) || !filter_var($this->request->post['reward'], FILTER_VALIDATE_INT)) {```

But, again, that won't resolve extension validations to maintain the example of what the core would already demonstrate in the first place unfortunately.

**Comment by webkul-dilip** [comment]
if (!isset($this->request->post['reward']) || !filter_var($this->request->post['reward'], FILTER_VALIDATE_INT)) {
In the case of a float number like 20.5, it will show a warning message.  In this case, it will only check value is an integer or not.

**Comment by webkul-dilip** [comment]
if (!isset($this->request->post['reward']) || !filter_var($this->request->post['reward'], FILTER_VALIDATE_INT)) {

ok, I will change

**Comment by webkul-dilip** [comment]
https://github.com/opencart/opencart/pull/8831 @straightlight, please check

**Comment by straightlight** [comment]
There has been previous replies regarding float use instead of int. Perhaps replacing FILTER_VALIDATE_INT with FILTER_VALIDATE_FLOAT could do it for the core and extensions altogether. The only problem will be with extensions directly calling a string type from service providers but that is not good practice anyways. All service providers string types should be associated with database INTs at this point prior to compare the data on the browser.

**Comment by webkul-dilip** [comment]
As I checked in the database all places use Int for reward point, so FILTER_VALIDATE_INT will fine for this case. OR we need to change in the database plase check https://github.com/opencart/opencart/blob/ab11174fbfb818f3e047c2525142fb503844051f/upload/system/helper/db_schema.php#L1623-L1626

**Comment by straightlight** [comment]
We don't necessarily need to change the database for this, since all associated types should be validated with INT types on the database as mentioned above.

**Comment by ADDCreative** [comment]
@webkul-dilip You still need to check for zero and possibly negative.

So maybe something like.
```php
if (!isset($this->request->post['reward']) || !filter_var($this->request->post['reward'], FILTER_VALIDATE_INT) || ($this->request->post['reward'] <= 0)) {
```
Or got back to using empty() but with FILTER_VALIDATE_INT if you are happy with negative values.

**Comment by straightlight** [comment]
Yes, correct. However, empty() would also check for other variable types, not only INT types.

**Comment by straightlight** [comment]
Another possibility to validate INTs by range with only positive values: https://stackoverflow.com/questions/4844916/best-way-to-check-for-positive-integer-php .

**Comment by ADDCreative** [comment]
> Yes, correct. However, empty() would also check for other variable types, not only INT types.

Which is why I said "empty() but WITH FILTER_VALIDATE_INT".

**Comment by straightlight** [comment]
The $filter_options should do it since it does not require other functions but simply a switch case within the same function of filter_var .

**Pull request merged**
