### PR TITLE
Error from admin/controller/startup/startup.php

### PR DESCRIPTION
**Pull request by JesseOC**
Check config_timezone is exists or not
Fix the error Notice: date_default_timezone_set(): Timezone ID '' is invalid in C:\xampp\htdocs\OpenCart\master-test\admin\controller\startup\startup.php on line 17
And JSON error popup

### CODE REVIEW

**Comment by fabiodemelo** [comment]
When things get fixed here after a bug report does the files (the download) file get updated as well? I am wondering if a user downloads the 3.0.2.0 does he gets these fixed already included or he needs to come back here and download the fixes?  Thank you..

**Comment by ADDCreative** [comment]
@fabiodemelo The downloads are not updated. You need to apply the updates yourself or wait for the next version release.

**Comment by DariyGRAY** [comment]
You can download the master brunch, where all updates are applied

**Comment by fabiodemelo** [comment]
Thank you.

**Comment by sazpurua** [comment]
@DariyGRAY Are the master brunch files for v3.0.2.0? for all the files here I don't see anywhere an indicator of which version they belong.
Thanks

**Pull request merged**
