### PR TITLE
Update cart.php

### PR DESCRIPTION
**Pull request by kurtulusoz**
When the discount and the campaign are applied together, the price does not work correctly. I revised the code and installed it.

### CODE REVIEW

**Comment by kurtitasarim** [comment]
Cart module price discount and special in use together problem fixed.

**Comment by TheCartpenter** [comment]
I don't agree with this change since specials can be mixed with discounts.

**Comment by kurtitasarim** [comment]
When both a discount and a campaign are applied to the product, the basket does not calculate properly. you can try it as a test

Kurtuluş ÖZ 
Junior Developer ~ Linux Admin
www.kurtulusoz.com.tr ~ www.kurtitasarim.com

**Comment by TheCartpenter** [comment]
If this issue is based on cart calculations, then mixing specials with discounts in the lookup is not the right course of action. More information is needed on how supporters can reproduce the issue you're addressing about.

**Pull request closed without merging**
