### PR TITLE
Implement CSRF protection in user setting forms

### PR DESCRIPTION
**Pull request by shinkbr**
Hi,

This is a fix for a CSRF vulnerability discussed in #5151.
(I'm aware that this is a closed issue but I believe that this needs to be fixed and therefore I wrote a patch.)

There are still more endpoints that should be protected from CSRF (such as the checkout form), but I will keep this PR to the most important two and cover the rest later if this seems OK.

Please correct me if there is a problem with the way I implemented this.

Thanks,

### CODE REVIEW

**Comment by arnisjuraga** [comment]
BUG: csrf token is not generated uppon account/register!

**Comment by shinkbr** [comment]
@arnisjuraga Thanks for pointing out! I will fix it, as we were going to use this for our service regardless.

**Comment by arnisjuraga** [comment]
Please, give a note here too, if someone else is willing to use iet.

**Comment by akzogibbs** [comment]
@shinkbr @arnisjuraga @danielkerr  - Does anyone know if this has been addressed in the most recent V2 build 2.0.3.0? I've been having massive issues with malware injections to point where i'm about to drop Opencart and move to another solution. When i've run scans on the site i'm being told the vulnerabilities are in various input forms?

**Comment by RaidoDev** [comment]
Hi @akzogibbs ! 

Available vulnerabilities do not guarantee, that your site has been infected through them. There can be multiple reasons, why your site has the problem.

You can contact me and I can have a look, what exactly has been broken.

**Comment by akzogibbs** [comment]
@RaidoDev - Yes please. I'll send you an email

**Comment by shinkbr** [comment]
@akzogibbs CSRF is not the kind of vulnerability that can directly result in a malware injection. Perhaps there is another issue in the system.

**Comment by danielkerr** [comment]
This does not sound like an OC issue. If files are being added u can check the logs where there IP is uploading the files

**Comment by akzogibbs** [comment]
thanks for the feedback @danielkerr , @shinkbr ...much appriciated

**Comment by danielkerr** [comment]
also yopur issue is nothing to do with CSRF .

**Comment by schiggi** [comment]
Is this patch available as an vqmod or ocmod file?

**Pull request closed without merging**
