### PR TITLE
[Maintenance] - Added payment prefixes - admin/view/template/extension/payment/klarna_checkout.twig file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by danielkerr** [comment]
i just setup a new repository for version 3.x

https://github.com/opencart/opencart-3

**Comment by mhcwebdesign** [comment]
Does this also include the committed changes from the 3.0.x.x_Maintenance branch?

**Comment by TheCartpenter** [comment]
> Does this also include the committed changes from the 3.0.x.x_Maintenance branch?

You can see some / most of the change in here: https://github.com/opencart/opencart-3/commit/ff899f5bd3f7a4444bba95be56977cf8ee03900f . I also identified that some payment_ prefixes were added as well compared to the maintenance branch.

**Comment by TheCartpenter** [comment]
Closing. Resolved on opencart-3 repository.

**Pull request closed without merging**
