### PR TITLE
Update robots.txt

### PR DESCRIPTION
**Pull request by mathsolutions**
robots not working without specifying User-agent: * at the beginning. Tested with webmasters tools

### CODE REVIEW

**Comment by TheCartpenter** [comment]
It has already been added in the MB.

**Comment by TheCartpenter** [comment]
https://github.com/opencart/opencart/blob/master/upload/robots.txt

**Comment by mhcwebdesign** [comment]
Just added it to the 3.0.x.x branch, too.

**Comment by mhcwebdesign** [comment]
Already done for 3.0.x.x

**Pull request closed without merging**
