### PR TITLE
Correct getRateName() return type

### PR DESCRIPTION
**Pull request by AJenbo**
Introduced in https://github.com/opencart/opencart/commit/977710c5ba995d49261f20273e971482c584970b

### CODE REVIEW

**Comment by TheCartpenter** [comment]
The rate could also be returned as an empty string instead of false and rather the use of ```string|false```.

**Comment by AJenbo** [comment]
Or null, but I don't really want to change how things work, just fix the bug as is.

**Comment by TheCartpenter** [comment]
Still indicates that ```false``` is returned in the ```else``` statement. It could be replaced with: ```''``` and set the ```@return``` to: ```string```.

**Comment by AJenbo** [comment]
@TheCartpenter you are welcome to make such a PR yourself if you think it would be an improvement.

**Pull request merged**
