### PR TITLE
Fix the admin order add / edit customer group restriction.

### PR DESCRIPTION
**Pull request by danijelGombac**
#6854

### CODE REVIEW

**Comment by straightlight** [comment]
The (array) validation has already been added by Daniel prior on Github in order to resolved these issues. An example would be with this one: https://forum.opencart.com/viewtopic.php?f=201&t=206915#p734216

**Comment by danijelGombac** [comment]
Before commenting take a look the changed code. There is no array validation.

**Comment by straightlight** [comment]
The original code is about validating an array which you decided to replace with an not empty statement with the array which this array is identified right from the OC installation in install/opencart.sql file:

`(0, 'config', 'config_customer_group_display', '["1"]', 1),`

As you can see, it is JSONized. As explained, and properly replied on the above, Daniel did made those changes accordingly based on the arrays that should rather be validated as I was the one who did reported it last time on GitHub.

**Comment by danijelGombac** [comment]
This restriction is stupid and belong to customer forms, not admin. And why is no restiriction in the admin customer edit page. You can select customer group, but can't use it.

**Comment by straightlight** [comment]
With higher PHP versions, these validations have been mostly rectified. Therefore, this commit will now be closed.

**Pull request closed without merging**
