### PR TITLE
[Master] - Removed reference method - catalog/model/account/subscription.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
So far I have received about a hundred email notifications from your today's pull requests, and I am not even looking at them anymore.
Can't you use a proper github client software and make your pull requests all in one go, rather than doing hundreds each day?

**Comment by TheCartpenter** [comment]
Well, not according to what you said last time; the notifications would be off which means, if you still have to ask about it, it means you haven't. Otherwise, it wouldn't bother you.

**Comment by TheCartpenter** [comment]
@mhcwebdesign: I cleared out most of the old commits just now since past declared issues have already been changed in the master branch between those times.

**Comment by condor2** [comment]
> Can't you use a proper github client software and make your pull requests all in one go, rather than doing hundreds each day?

Once I made many changes on a pull request and Daniel told me to make for each file....

**Comment by TheCartpenter** [comment]
Each file is better. It is clearer and consist.

**Comment by cgcmart** [comment]
> > Can't you use a proper github client software and make your pull requests all in one go, rather than doing hundreds each day?
> 
> Once I made many changes on a pull request and Daniel told me to make for each file....

I believe whether a pull request is for each file or not depends on the issue. If the issue is related to multiple files, it's better to make a pull request for all them, that reduces massive pull requests.

**Pull request closed without merging**
