### PR TITLE
Fix HTTPS issue admin order edit. Change API URL based on request admin URL

### PR DESCRIPTION
**Pull request by howdu**
Fixes error:
Mixed Content: The page at 'https://www.example.com/admin/index.php?route=sale/order/add&user_token=123' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.example.com/index.php?route=api/currency&api_token=123&store_id=0'. This request has been blocked; the content must be served over HTTPS

### CODE REVIEW

**Comment by danielkerr** [comment]
make sure the default config is for the front and the admin are the same!!

**Comment by danielkerr** [comment]
it will still have issues because of cross domain

**Comment by howdu** [comment]
The error is clear. The change is simple. If the admin is https then ajax request must be also.

https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content

**Comment by howdu** [comment]
Or could be fixed by removing the http so it starts '//www.example.com'.

```php
$data['catalog'] = preg_replace("(^https?://)", "", HTTP_CATALOG)';
```

**Pull request closed without merging**
