### PR TITLE
Removed 'is_null' from Customer model

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by straightlight** [comment]
Yeah, I wondered why those two !is_null were there originally. I would suggest replacing both entire lines from the two commits you posted to: !empty . This will shorten the line codes as , typically, this is what the lines means anyways.

**Comment by straightlight** [comment]
Besides, the !empty / empty function implicits the isset.

**Comment by condor2** [comment]
That two !is_null are from 3.0.x.x migrated from 2.x.x.

And if you mean to replace these lines 

`if (isset($data['filter_newsletter']) && $data['filter_newsletter'] !== '') {`

are more lines like that

**Comment by straightlight** [comment]
Leftovers probably. Yes, those are the lines I meant and should all be replaced by !empty instead of using isset and !is_null since, as mentioned above, !empty already includes those lookups on the server-end side in anyhow.

**Comment by condor2** [comment]
@danielkerr change the code because is still there.

**Comment by danielkerr** [comment]
added manually

**Pull request closed without merging**
