### PR TITLE
Filemanager "Directory does not exist" fix.

### PR DESCRIPTION
**Pull request by emahieu**
Fixed an issue wherin uploading files in the admin using the filemanager incorrectly states "Directory does not exist" (also referred by previously closed issue #5078 and more recently #6108 )

### CODE REVIEW

**Comment by elcopdoo** [comment]
I confirm this resolve the issue.

**Comment by danielkerr** [comment]
this does not fix anything!

**Comment by cufeo** [comment]
I confirm the warning still persist!

**Comment by danielkerr** [comment]
@elcopdoo are u high! let me guess you are same person as emahieu. just wastign my F'ing time!

**Comment by danielkerr** [comment]
ok spotted the issue.

**Comment by phildabill** [comment]
Heads up,

Can say this does not fix the problem.  Clean install of 3.0.2.0 with php5-fpm.

With or without the / after catalog I get "Directory does not exist" warning. When I swap to "$json['error'] = $directory;" to see the folder, it always lists "/var/www/public/image" (correct folder with correct permissions).  

If I remove the complete || statement in the if, the upload works perfectly!

Something is funky here!

**Pull request closed without merging**
