### PR TITLE
Update order.php

### PR DESCRIPTION
**Pull request by GautamMKGarg**
Mails are getting sent even if notify was set to false. Now I am checking notify before sending mail.

### CODE REVIEW

**Comment by GautamMKGarg** [comment]
Hello Team,

Is there any update on this? This pull request is pending since long. Do you need more clarification before approving the pull request?

**Comment by ADDCreative** [comment]
Notify is already checked before sending, at least for edit. If you don't want to send a email for add then you shouldn't call the function at all.

https://github.com/opencart/opencart/blob/2cc1b4f0c4cada4213423e7d8419f96cf0d38b21/upload/catalog/controller/mail/order.php#L38-L40

**Comment by GautamMKGarg** [comment]
I am payment gateway plugin developer, I am using this function to save the history of order
$this->model_checkout_order->addOrderHistory
This function is sending order emails to customers even if email notification is off for orders. But in actual, it should not send a notification email to the customer if order emails is off in settings, but it is not working.
Am I doing something wrong?

**Comment by danijelGombac** [comment]
The setting option is for admin email notification, not customer.

**Comment by GautamMKGarg** [comment]
ok, from where should I choose wether to send email notification to customer or not?

**Comment by danijelGombac** [comment]
I think you should remove or disable the "mail_order_add" event.

**Comment by ADDCreative** [comment]
As long as the fourth parameter of $this->model_checkout_order->addOrderHistory is false or not supplied, no email will be sent when changing the order history.

To ensure that a email is not sent on setting the first status. Add  ```&& $notify``` to:
https://github.com/opencart/opencart/blob/2cc1b4f0c4cada4213423e7d8419f96cf0d38b21/upload/catalog/controller/mail/order.php#L33

However, doing this would cause problems for some payment modules where the comment is intended for the admin only, but the email is still required to be sent. One such example.
https://github.com/opencart/opencart/blob/4ba536198a4638b6d3902a7c720ce8503b0dc394/upload/catalog/controller/extension/payment/authorizenet_aim.php#L151-L156

**Pull request closed without merging**
