### PR TITLE
Upgraded aws/aws-sdk-php vendor to v3.315.3

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
It looks like there's never going to be a stable OC 4.1.0.0 release because of the daily aws/aws/sdk-php updates.

**Review by TheCartpenter — COMMENTED** [review]
It looks like somebody in here didn't get the picture. It's ok, I'll provide it. While the core is still in development, it does not prevent any release being published in any way from any vendors with the exception of the system/vendor.

Besides, the leftover and opened PRs on this repository does not contain these notes nor have they prevented any releases in the past. Therefore, the vendors updates do not create any impacts on this project.

**Review by TheCartpenter — COMMENTED** [review]
That's because, without using the search, this is where I was able to find it: https://github.com/opencart/opencart/tree/master/upload/system/storage/vendor/aws and it's the same location it's always been.

**Comment by mhcwebdesign** [comment]
> That's because, without using the search, this is where I was able to find it: https://github.com/opencart/opencart/tree/master/upload/system/storage/vendor/aws and it's the same location it's always been.

Yes, but where in OpenCart is this vendor library actually needed?

**Review by TheCartpenter — COMMENTED** [review]
Being used by extensions relying to this location to simplify the tasks.

**Comment by mhcwebdesign** [comment]
> Being used by extensions relying to this location to simplify the tasks.

I can't find any extension at https://github.com/opencart/opencart/tree/master/upload/extension using aws.

**Review by TheCartpenter — COMMENTED** [review]
They're located on the Marketplace. It's just a matter on keeping up-to-date with the stuff that's going on at times.

**Comment by mhcwebdesign** [comment]
> They're located on the Marketplace. It's just a matter on keeping up-to-date with the stuff that's going on at times.

I still think the system/storage/vendor should only contain libraries that are actually being used by the OpenCart core, or OpenCart standard extensions. 3rd party extensions from the marketplace should use their own libraries, or vendor libraries, as needed.

BTW.: Another redundant library is the system/library/db/pgsql.php, with all the unneeded changes to the SQL queries over the past few months we are now a far cry from getting OpenCart to work with a PostgreSQL database.

**Review by TheCartpenter — COMMENTED** [review]
It has been integrated in the core since quite sometime now. AWS is becoming quite popular to many platforms these days. As for the pgsql library, that has already been handled in the OC v3.2.1.0 release.

**Review by TheCartpenter — COMMENTED** [review]
AWS has been integrated in the core since quite sometime now. It is becoming more popular by many platforms as their vendors packages are being updated on a regular basis. As for the pgsql.php file, that has already been handled in the OC v3.2.1 release.

**Comment by mhcwebdesign** [comment]
>As for the pgsql library, that has already been handled in the OC v3.2.1.0 release.

I can see that you added the

`$sql = preg_replace('/`([A-Za-z0-9\.\-_]+)*[^\'\"\s]?/', '$1', $sql);`

to the queries. Have you fully tested 3.2.1.0 with a PostgreSQL database?

**Review by TheCartpenter — COMMENTED** [review]
It works from the most simplest to the most complexed SQL queries in the platform as it was achieved with a single ```$1``` to resolve the backticks issues with PostgreSQL.

**Pull request merged**
