### PR TITLE
Update en-gb.php

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by ADDCreative** [comment]
This is pointless. Are you going to change Text to Texts, Entry to Entries and Error to Errors in all the language files as well?

**Comment by stalker780** [comment]
@ADDCreative yep. One by one. Every single file 🤣

**Comment by TheCartpenter** [comment]
> This is pointless. Are you going to change Text to Texts, Entry to Entries and Error to Errors in all the language files as well?

If need be. So far, I haven't seen any of those enumerated from the above in the core

**Comment by TheCartpenter** [comment]
> Can we just focus on genuine testing and bugfixes please? OpenCart 4 still has a number of issues to be addressed, nobody cares about minor cosmetic changes.

What's in the core is already what's being focused on.

**Pull request merged**
