### PR TITLE
Capture the folder name if the user rename

### PR DESCRIPTION
**Pull request by valdeir2000**
https://forum.opencartbrasil.com.br/viewtopic.php?p=70464#p70464

### CODE REVIEW

**Comment by jamesallsup** [comment]
duplicate.

**Comment by valdeir2000** [comment]
It is not duplicated. I do not know if you noticed that there are two different files.

One is admin and is another catalog.

I made by the browser and can only send a commit by file.

**Comment by jamesallsup** [comment]
ok thanks, didnt see that it was different locations

**Comment by straightlight** [comment]
This will cause increased error messages showing in the logs while the basename is correctly set with the DIR_IMAGE. Therefore, this commit will now be closed.

**Pull request closed without merging**
