### PR TITLE
Fixed text_security variable - admin/view/template/common/security.twig file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Why was this commit closed?

**Comment by eka7a** [comment]
Merged

**Comment by TheCartpenter** [comment]
Yeah, it's merged, that's what it says; it's merged to your branch and closed from this repository. Why is it closed from this repository?

**Comment by eka7a** [comment]
I don't understand what you mean. Merged with maintenance branch.
https://github.com/opencart/opencart/commits/3.0.x.x_Maintenance

**Comment by eka7a** [comment]
There is nothing wrong with that. Because every merged pull request is closed automatically.

**Comment by TheCartpenter** [comment]
Ok, no problem.

**Pull request merged**
