### PR TITLE
Added array cast - extension/opencart/admin/controller/total/tax.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by danielkerr** [comment]
u can put these changes together instead of opening lots of tickets. the only thing i dont what to see is loads of reverts and merges.

**Comment by TheCartpenter** [comment]
Smartgit doesn't let me commit from the tool on this repository at all. Which is why, I am submitting the pull requests from the site but the site doesn't have the combined function either. Only on opencart-3 repository am I allowed to do both.

**Comment by ADDCreative** [comment]
> Smartgit doesn't let me commit from the tool on this repository at all. Which is why, I am submitting the pull requests from the site but the site doesn't have the combined function either. Only on opencart-3 repository am I allowed to do both.

@TheCartpenter Are you trying to commit direct to opencart/master? That won't work. You need to create a new branch (based on master) on your fork. Commit your changes to this branch on your fork. The create a pull request from that branch to opencart/master.

**Comment by TheCartpenter** [comment]
Take a look at my /commits list on my fork repository, there's a red x on each commits that I submit which is why it doesn't allow me to do it on the forked branch.

**Comment by TheCartpenter** [comment]
I think I fixed it now.

**Comment by ADDCreative** [comment]
Looks like your master is out of sync with opencart/master. With things like an added 'Changes' submodule. You probably want to fetch the upstream and then reset --hard.

Then you should be able to create a branch off your master.

**Comment by TheCartpenter** [comment]
Did a hard reset, it says to be a success. Did a sync, it says it's a success. Commits are pushed on /commits but the red x on each rows still shows.

**Comment by mhcwebdesign** [comment]
> Smartgit doesn't let me commit from the tool on this repository at all. Which is why, I am submitting the pull requests from the site but the site doesn't have the combined function either. Only on opencart-3 repository am I allowed to do both.

You are using Smartgit the wrong way then. Just create your own fork on github fromf the OpenCart master branch, then add/create your local test site from your github fork. Now you can do all your changes and tests on your local test server. And once completed, click on Smartgit's 'Sync' button to get it all uploaded to your github fork. And finally create a pull request from your updated github fork. This should result in just one single pull request for all your little changes rather than your daily tens or hundreds small pull requests.

**Comment by TheCartpenter** [comment]
If I'd be using Smartgit the wrong way, I wouldn't go really far on the opencart-3 repository. I used the fork button from my repository and pasted the opencart git file on it. Since, it still shows that red x regardless if the sync function in Smartgit has been used.

**Comment by ADDCreative** [comment]
> I created a new pull request, closed it. Still showing a red x.

That's because you master is still out of sync and you have an added Changes submodule. You need to get that fixed. And never commit to the master of your fork if you want to do a pull request. Always create a new branch for every pull request.

**Comment by TheCartpenter** [comment]
It, then, means 2 steps each for a single commit from a tool where the site allows to post a commit directly. I do see the Changes folder but it's empty. There's nothing in it.

**Comment by TheCartpenter** [comment]
I tried several times with these branches and checkout stuff. I am done with this. The site uploads directly for this repository with no questions asked, nothing that requires a leading trail when uploading new files. The web version is strict to the point and that's what I want; to keep moving forward without a tool restricting my uploads.

**Comment by mhcwebdesign** [comment]
So how come others can combine multiple changes into a single push-request then? Something else must have gone wrong with the way you handled it.

**Comment by TheCartpenter** [comment]
I wouldn't know the whole definition of the term: 'others' where even the Master Branch and the Maintenance Branch, did have a lot of conflicts to be resolved and that being for several years until Daniel cleared 99% of these commits since recently. What I do know, however, is that I use the same default preferences and settings as much on the opencart-3 that it is on the master branch repository and I can definitely say that I don't encounter these issues on the opencart-3 nor from the website.

Which is why, I am submitting the full path and filename on each commit subjects so that I can ensure that the revealed locations on the repository are not hitting conflicts until being merged or closed. That strategy does not require to create any branches from a tool where all Github users can see the results of the consequences that it may cause when using new branches as it contains mixed branches with accumulated branches and that is another way for cause and effect. Thank god the website version exists to create the commits. Otherwise, I wouldn't imagine where past users vs. the new upcoming users would still reveal from their commits and right at their beginning of process since, again, on the opencart-3, I don't face these issues.

**Comment by ADDCreative** [comment]
opencart/opencart-3 works because you have write access. You don't to opencart/opencart so need to to a pull request from a branch on your fork.

First to get you master in sync and assuming upstream is a remote pointing to opencart/opencart (if not you can add it with `git remote add upstream https://github.com/opencart/opencart` or just replace upstream with opencart if that is the correct remote). Do the the following.

```
git fetch upstream
git checkout master
git reset --hard upstream/master  
git push origin master --force
```

This should sync your TheCartpenter/opencart master with opencart/opencart master.

You can check it works by goin going to https://github.com/TheCartpenter/opencart and check the Changes (Testing change) submodule folder has been removed.

If everything is correct. You now create a new branch with `git branch new-patch-1` where new-patch-1 is the name you want to call it. Then switch to it with `git checkout new-patch-1`. Now make your changes and commit them. You can then do a pull request to opencart/opencart master.

For your next changes sync you master again by doing a fetch and merge. Create a new branch with `git branch new-patch-2` and so on.

**Comment by TheCartpenter** [comment]
After applying your command lines, this is what I have now compared to yesterday when I try to submit a commit from Smartgit:

```git.exe push --porcelain --progress --recurse-submodules=check upstream refs/heads/master:refs/heads/master
remote: Permission to opencart/opencart.git denied to TheCartpenter.```

**Comment by TheCartpenter** [comment]
As for the full access, take note that this commit user does not have full access either and, by posting multiple branches in the same commit by the same submitter, these are the results: https://github.com/opencart/opencart-3/pull/21

**Comment by TheCartpenter** [comment]
Ok, remote works now, Just tried one more time and even when creating a new branch, it's still accumulating with previous ones: https://github.com/opencart/opencart/pull/11220 .

**Comment by TheCartpenter** [comment]
The only things that changed on my commits list from my repository, since the command lines applied from the above, are the commit updates from Daniel and the fact that when he merges, it now shows a green checkmark (good stuff though). Otherwise, I don't see any difference.

**Pull request merged**
