### PR TITLE
Removed spaced / on br - admin/view/template/sale/order_invoice.twig file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by osworx** [comment]
Why?
Read (for example): https://stackoverflow.com/questions/1946426/html-5-is-it-br-br-or-br

**Comment by TheCartpenter** [comment]
On the master branch, it's already using the <br/> as opposed to <br />

**Comment by osworx** [comment]
> 
> 
> On the master branch, it's already using the br/ as opposed to br /

Master branch is still using many useless code parts as well as repetitions!
Just a sample:
https://github.com/opencart/opencart/blob/4f33534279ecdfe2307e4dfa7577a70689543088/upload/admin/view/template/catalog/attribute.twig#L23

**Comment by TheCartpenter** [comment]
A little bit like this file, right ? https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/catalog/view/theme/default/template/information/contact.twig

**Comment by mhcwebdesign** [comment]
I think there are more important issues to be fixed first! I couldn't care less whether it's` '<br'>, '<br />', or '<br/>'`.

**Comment by TheCartpenter** [comment]
@mhcwebdesign: It's getting there. Also requires code trimming on option values. These haven't been fixed since ages.

**Comment by mhcwebdesign** [comment]
> Really nobody needs nowadays that `type="text/javascript"` and `<!--`

According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script :

> Omitted or a JavaScript MIME type: This indicates the script is JavaScript. The HTML5 specification urges authors to omit the attribute rather than provide a redundant MIME type. In earlier browsers, this identified the scripting language of the embedded or imported (via the src attribute) code. JavaScript MIME types are listed in the specification.

Hence there is no harm done here. There are more important issues to be addressed!

**Pull request closed without merging**
