### PR TITLE
Upgraded aws/aws-sdk-php vendor to v3.317.0

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
So what are we going to do once OC 4.1.0.0 has been released? As I said, it seems they are unable to provide a stable aws-sdk-php.

**Comment by TheCartpenter** [comment]
> So what are we going to do once OC 4.1.0.0 has been released? As I said, it seems they are unable to provide a stable aws-sdk-php.

Simple. As you said on the official channels of the AWS repository, OC v4.x releases gets distributed with the integration of the specific version of AWS during that period of time: https://github.com/aws/aws-sdk-php/discussions/2965#discussioncomment-10160604 which means that the next and upcoming releases of vendors will keep being put up-to-date with the next and upcoming releases of OC since vendors shows no interference with the OC core projects in general.

**Comment by danielkerr** [comment]
stable branch only please!

**Comment by TheCartpenter** [comment]
> stable branch only please!

https://github.com/opencart/opencart/issues/14063#issuecomment-2271288240

**Comment by mhcwebdesign** [comment]
@Daniel : The aws-skd-php obviously isn't able to provide a stable branch, see https://github.com/aws/aws-sdk-php/discussions/2965

**Comment by TheCartpenter** [comment]
And, as the AWS team already mentioned on that topic: https://github.com/aws/aws-sdk-php/discussions/2965#discussioncomment-10267493 , each releases are stable, not only on the Amazon website but also on to their repository's homepage.

**Comment by AJenbo** [comment]
It's because TheCapenter keeps updating it from PHP 8.1+ rather then using PHP 7.4 when updating the composer.lock file. If he had done that it would have pulled the latest PHP 7.4 compatible one instead of the one for PHP 8.1.

**Comment by TheCartpenter** [comment]
As addressed here: https://github.com/opencart/opencart/pull/14081#issuecomment-2289066580 .

**Comment by TheCartpenter** [comment]
And here: https://github.com/opencart/opencart/pull/13971#issuecomment-2138235081 .

**Comment by AJenbo** [comment]
That's just admitting that you intentionally keep breaking things because you want it to be 8.1+

**Comment by TheCartpenter** [comment]
> That's just admitting that you intentionally keep breaking things because you want it to be 8.1+

It's not what it says.

**Pull request closed without merging**
