### PR TITLE
Use same path when call functions - order/cehckout model

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
What is the point of this pull request?

**Comment by condor2** [comment]
To be the same....in some places use same....

https://github.com/opencart/opencart/blob/master/upload/catalog/model/checkout/order.php#L55

**Comment by stalker780** [comment]
Do not do that. You are breaking events for model methods.

On the contrary all model methods should be called using proxy `$this->model_checkout_order->method` to make events work correctly.

**Comment by condor2** [comment]
Then others should be made $this->model_checkout_order->method...

Line 55, line 265...

**Review by aaron-muti-420 — APPROVED** [review]
Looks Great

**Pull request closed without merging**
