### PR TITLE
[Maintenance] Define version header

### PR DESCRIPTION
**Pull request by haxcop**
Without this addition the upgrade will throw a lot of warning lines, Feel free to suggest a better dynamic method

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Not sure why we would need that in there ...

**Comment by haxcop** [comment]
> Not sure why we would need that in there ...

If you propose a better way I'm happy with it too :)

**Comment by mhcwebdesign** [comment]
@haxcop: You really need to provide some more details about what exactly you, from where you upgraded from, and how. otherwise nobody will be able to reproduce it here, let alone be able to help you.

**Comment by haxcop** [comment]
> @haxcop: You really need to provide some more details about what exactly you, from where you upgraded from, and how. otherwise nobody will be able to reproduce it here, let alone be able to help you.

My apologies:

From version 3.0.3.6 to the Latest 3.0.3.8
PHP V 7.3 and 7.4

Warning: Use of undefined constant VERSION - assumed 'VERSION' (this will throw an Error in a future version of PHP) in /home/.../system/storage/modification/system/library/template/twig.php on line 37 

With the proposed commit this warning dissapears

**Comment by condor2** [comment]
@mhcwebdesign if you notice it is /system**/storage/modification/**system/library/template/twig.php

**Comment by condor2** [comment]
No, but who know what ocmod extension changed twig file :)

**Comment by danielkerr** [comment]
its added in index.php

**Pull request closed without merging**
