### PR TITLE
Updating information subjects of the Russian Federation

### PR DESCRIPTION
**Pull request by Hkr32**
Based on page: https://en.wikipedia.org/wiki/Federal_subjects_of_Russia

### CODE REVIEW

**Comment by Hkr32** [comment]
@osworx, https://github.com/opencart/opencart/commit/4d036c60d370c2b48007e010af3c809bfd643395

**Comment by stalker780** [comment]
@danielkerr 
Do you feel fine?
Sevastopol and Crimea are Ukraine

**Comment by stalker780** [comment]
@danielkerr 
Please check this commit
https://uk.wikipedia.org/wiki/%D0%9E%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%96_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B8


Since March 18, 2014, the Russian Federation constitutionally consists of 85 federal subjects.[[2]](https://en.wikipedia.org/wiki/Federal_subjects_of_Russia#cite_note-Constitution65-2) The two located on the [Crimean Peninsula](https://en.wikipedia.org/wiki/Crimea), [Sevastopol](https://en.wikipedia.org/wiki/Sevastopol) and the [Republic of Crimea](https://en.wikipedia.org/wiki/Republic_of_Crimea),[ are not internationally recognized](https://en.wikipedia.org/wiki/United_Nations_General_Assembly_Resolution_68/262) as part of Russia

Crimea and Sevastopol are not russian regions, only Russia claims it russian.
With such approach you may add Luhansk, Donetsk, Transnistria, Abkhazia , etc, as russian regions too 😈

**Comment by dhrebeniuk** [comment]
@stalker780 , need ask GitHub support, because this violates policies, need ask GitHub support about this.

**Comment by stalker780** [comment]
> @stalker780 , need ask GitHub support, because this violates policies, need ask GitHub support about this.

I would ban the creator of this commit.

**Comment by dhrebeniuk** [comment]
https://github.blog/2022-03-02-our-response-to-the-war-in-ukraine/

**Pull request closed without merging**
