### PR TITLE
Missing translation file: promotion.php

### PR DESCRIPTION
**Pull request by osworx**
Also missing in 3.0.3.2

### CODE REVIEW

**Comment by engwalid1971** [comment]
The file is not needed at all !

**Comment by osworx** [comment]
Then remove that file: https://github.com/opencart/opencart/blob/master/upload/admin/controller/extension/extension/promotion.php
Otherwise in any 3.0.3.2 installation at many clients I see the error in the dropdown (extension):
`heading_title(0)`
I (and we) know that it useless, but do that also the customers?

**Comment by engwalid1971** [comment]
> Otherwise in any 3.0.3.2 installation at many clients I see the error in the dropdown (extension):
> `heading_title(0)`

**The same issue:**
https://github.com/opencart/opencart/issues/7162
**The solution:**
https://github.com/opencart/opencart/commit/15b592ebbcc4bade488f11b3c99e37917c61dd16

**Comment by osworx** [comment]
"The Solution" was a commit on the 29 Jan 2019
The release of v3.0.3.2 was April 09, 2019

Sounds good ..?

**Question:**
Why is the message still displayed when there was a fix?
And I am sure it will be also in 3.0.3.3 (whenever this will be published - IF).

**Comment by engwalid1971** [comment]
The release of 3.0.3.2 is the same as 3.0.3.1, but only includes fixes for Google Shopping.
The release of 3.0.3.1 was Jan 07, 2019

Screenshot from 2019-08-31 13-52-28

**Comment by osworx** [comment]
Cool down baby ...

I know exactly when is what and how published.
So, either delete the controller or add the language file.
Simple solution and hopefully for the 3.0.3.3 release - if ever.

**Pull request merged**
