### PR TITLE
Added true case - catalog/controller/account/address.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
There used to be a battled discussion about the ways to sanitize the address ID in the past. Now that the CSRF token lookup has been added into the catalog startup, this should reduce concerns due to the customer_token that is also integrated into the account address controller.

**Comment by ADDCreative** [comment]
You have `=== true` for this one as well.

**Comment by TheCartpenter** [comment]
Just fixed it at the same time. I am working on the trim function in the mean time.

**Comment by TheCartpenter** [comment]
Closing due to conflicts.

**Pull request closed without merging**
