### PR TITLE
Changed int|void to int|bool - extension/opencart/catalog/model/fraud/ip.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**
As per: https://github.com/opencart/opencart/issues/11137#issuecomment-1152733931

### CODE REVIEW

**Comment by ProjectMyst** [comment]
> As per: https://github.com/opencart/opencart/issues/11137#issuecomment-1152733931

Pull request didn't merge.

**Comment by TheCartpenter** [comment]
It won't be, since this suggestion was to let pass of an IP address lookup behind the scenes while managing an order within an API whereas, either, this extension should rather be more informative to the admin API users regarding a restriction imposed or for this extension to be entirely removed.

**Comment by TheCartpenter** [comment]
An admin API group feature would need to be added by design in order to achieve this without affecting the fraud extensions as well as the orders based on an event /before trigger with JSON.

**Comment by TheCartpenter** [comment]
Or, by using a fraud extension lookup by service.

**Pull request closed without merging**
