### PR TITLE
Update user.php

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by ppalashturov** [comment]
Stop spamming please make a PR with all the commits not file by file!

**Comment by TheCartpenter** [comment]
> Stop spamming please make a PR with all the commits not file by file!

Another late in the news. That's fine. All you have to do is to read this commit post before posting against the expectations: https://github.com/opencart/opencart/issues/12616#issuecomment-1676390828

**Comment by TheCartpenter** [comment]
Besides, there are also commits containing multiple changes rather than posting each changes for every commit. Otherwise, it would create conflicts on anyhow.

**Comment by batumibiz** [comment]
@danielkerr please stop this spam crap from TheCarpenter.
He doesn't want to understand that all these small changes can be made in one PR, and creates a serious inconvenience for everyone else.

Please figure it out, it’s impossible to tolerate this anymore.

**Comment by TheCartpenter** [comment]
> @danielkerr please stop this spam crap from TheCarpenter. He doesn't want to understand that all these small changes can be made in one PR, and creates a serious inconvenience for everyone else.
> 
> Please figure it out, it’s impossible to tolerate this anymore.

Email notifications are based on personal preferences. You don't like receiving my commit post as notifications while other users are also doing it on this repository? Then, put it on the ignore list!

**Comment by mhcwebdesign** [comment]
I counted 58 pull requests from TheCartpenter during the past 24 hours, mostly cosmetic changes. So yes, it would have made sense to combine them into a single one. The next release will have an unnecessary long change history.

**Comment by TheCartpenter** [comment]
> I counted 58 pull requests from TheCartpenter during the past 24 hours, mostly cosmetic changes. So yes, it would have made sense to combine them into a single one. The next release will have an unnecessary long change history.

Cosmetic changes are only a matter of opinion. The proposed changes are already located elsewhere in the core as I am only filling the rest of the blanks. If you believe these changes will be unnecessary to be announced in the changelog, then it means you do not fully understand the changes that's been already made in the core.

**Comment by condor2** [comment]
Who don't like the 'SPAM'....just change notifcation settings.....

**Comment by batumibiz** [comment]
> Who don't like the 'SPAM'....just change notifcation settings.....

This creates some inconvenience.
A more correct way is to fight the source of spam. This should not happen on a serious project.

**Comment by condor2** [comment]
> This creates some inconvenience. .

For what you need Email notification on other project?

**Comment by batumibiz** [comment]
> For what you need Email notification on other project?

What are you talking about now?
The main complaint here is not the large number of notifications, but the fact that the **GIT history is clogged**. 80% of minor changes that do not correct anything and do not affect the algorithm can be combined into 1 commit and, accordingly, 1 PR can be sent.

**Comment by condor2** [comment]
> The main complaint here is not the large number of notifications

And what is the problem?....

Just change Github settings so that notifications to be only on github page and not e-mail.....

**Comment by mhcwebdesign** [comment]
> > The main complaint here is not the large number of notifications
> 
> And what is the problem?....
> 
> Just change Github settings so that notifications to be only on github page and not e-mail.....

Then how do you prevent the clogged GIT history? And how can we selectively prevent notifications coming from TheCartpenter, but not others?

**Comment by stalker780** [comment]
@mhcwebdesign  I have added a filter in gmail which deletes every message containing sender `TheCartpenter` couple years ago.

It's vain to ask him to change his behavior. He does not understand what he is doing. 
He simply shows his disrespect to OC community and breaking github notifications in public repo. 
Perhaps he behaves the same in the street and other public places :)

Try to contact github support if Daniel ignores this. But I don't think this will help a lot.

**Comment by TheCartpenter** [comment]
> @mhcwebdesign I have added a filter in gmail which deletes every message containing sender `TheCartpenter` couple years ago.
> 
> It's vain to ask him to change his behavior. He does not understand what he is doing. He simply shows his disrespect to OC community and breaking github notifications in public repo. Perhaps he behaves the same in the street and other public places :)
> 
> Try to contact github support if Daniel ignores this. But I don't think this will help a lot.

No disrespect has been shown on the commit, as I am still following Github's regulations as to post suggested code changes. No official regulations dictates that these posts needs to be put into a single commit altogether. Since these arguments seem to be about email notifications, as said on my previous post, email notifications are based on personal preferences. What users decides with their notifications are decisions based on their own.

**Comment by danielkerr** [comment]
yeah leave him alone. i appreciate the help. i don't include all his commits but he does have some good push requests! i need all the help i can get. i prefer people people helping than complaining.

**Pull request merged**
