### PR TITLE
Checkout confirm button doesn't work error fixed

### PR DESCRIPTION
**Pull request by TheBiTTixX**
I deactivated subscription method temporarly until next update. You can replace your files  /catalog/model/checkout/oprder.php file with this.

### CODE REVIEW

**Comment by TheBiTTixX** [comment]
by the way , Dont forget clear all caches.

**Comment by polcape** [comment]
With last commit when I try to load payment get this errore in console

<b>Exception</b>: <b>Notice</b>:  Undefined property: Proxy::getMethods in <b>/app/sito/catalog/model/checkout/payment_method.php</b> on line <b>15</b> in <b>/app/sito/system/engine/proxy.php</b> on line <b>83</b>

**Comment by cgcmart** [comment]
> 
@polcape 
are you still on opencart?

I have the sale error log, #12351.

It looks nobody gets opencart 4 work.

**Comment by hayden-t** [comment]
Im on oc4 build a site, logged several bugs too, ahve not got as far as testing the checkout yet

**Pull request closed without merging**
