### PR TITLE
Update FontAwesome 6.2.0 & jQuery 3.6.1

### PR DESCRIPTION
**Pull request by stalker780**
https://github.com/opencart/opencart/issues/11652

I would also like to help to update to latest Bootstrap 5.2.1, but I am not sure I can compile it correctly. So I hope Daniel will make this update from outdated nowadays BS 5.1.

### CODE REVIEW

**Comment by nexadomain** [comment]
The **Fontawesome** folder contains too many assets that are not necessary for web projects and OpenCart.

For Web Project, only 2 folders are required
1. CSS
2. Webfonts

Even CSS folders have a lot of stylesheets, but we are using only 1
i.e `all.min.css`
So other stylesheets are not at all required except `v4-shims.min`
_"v4-shims.min"_ is required only when we need to display icons using font awesome v4 code. But with Opencart 4, every icon is being rendered with Fontawesome v6 code, so won't need
```
// Font Awesome v4.7
<i class="fa fa-opencart"></i>

// Font Awesome v6
<i class="fa-brands fa-opencart"></i>
```

Since you have already committed, I would request to delete the rest of the folders and stylesheet to make Opencart slimmer. Also with svgs folder, it makes 4000+ changes that are untraceable.

You can read Font Awesome latest Documentation. For web projects, only the CSS folder and WebFonts folder are required.
JS folder also works instead of CSS, but with Opencart we are parsing icons using CSS only, so the JS folder is also not required.
Fontawesome-Required-folder-for-Web-Project
Fontawesome-Required-Stylesheets

----------------------
----------------------

For **Bootstrap**, you just need to copy `scss` folder from the _Bootstrap_ vendor to `view/stylesheet/scss` (admin & catalog directory)
Then Delete the file `view/stylesheet/bootstrap.css` and now run the Opencart Application in Browser.
Opencart has _startup_ named **sass** ( `admin|catalog/controller/startup/sass.php` ) , which creates new CSS file after compiling the scss if CSS file not found.

**Comment by stalker780** [comment]
@nexadomain 
Agree with you about excessive FontAwesome folders. Perhaps I will make such pull request. Hope Daniel will commit this.

**Comment by stalker780** [comment]
@nexadomain 
> For **Bootstrap**, you just need to copy `scss` folder

Yes, but it breaks font-size, OC colors and dropdown arrows. Perhaps it requires some configuration or custom styles. So copying new files is not enough.

**Comment by nexadomain** [comment]
I compared **Bootstrap 5.0.0** `scss` folder and **Opencart 4.0.1.1** `view/styslesheet/scss` folder
_3 files_ are _modified_
```
1. scss/_carousel.scss
2. scss/_variables.scss
3. scss/forms/_input-group.scss
```
`_variables.scss` contains _changes_ such as _color, sizing, height, margins, padding,_ etc

You can check the comparison commit
[here "https://github.com/nexadomain/Opencart-Bootstrap/commit/05f22f5d7a72a271c990a90f6bfa8ed91604cf6d](https://github.com/nexadomain/Opencart-Bootstrap/commit/05f22f5d7a72a271c990a90f6bfa8ed91604cf6d)"

Also, Bootstrap 5.2.0 contains a major revamp from Bootstrap 5.0.0.
You can check the comparison
[here "https://github.com/twbs/bootstrap/compare/v5.0.0...v5.2.1#files_bucket](https://github.com/twbs/bootstrap/compare/v5.0.0...v5.2.1#files_bucket)"

**Comment by stalker780** [comment]
@nexadomain 
Yes, I have compared them too. But don't have enough time for debugging now. Perhaps will return to this update later.

I think this is not correct to modify core BS scss files. Hardcoding third-party library files is a bad practice. 
There should be a separate opencart.scss file which contains all OC custom variables. This would make BS update much more simple.

**Comment by stalker780** [comment]
Also, I would spend so much time for update only if Daniel will confirm he wants BS 5.2.1 update. 
I don't want to waste my time if this commit will be closed and lost like many others.

**Comment by nexadomain** [comment]
> Also, I would spend so much time on updating only if Daniel will confirm he wants the BS 5.2.1 update. I don't want to waste my time if this commit will be closed and lost like many others.

@stalker780 
Chances are more that he will close this pull request without merging.
But if you described the _'changes'_ nicely, in a better way, and optimized, then He might like to merge your pull request.

Even if your request gets rejected, don't worry - **Create a New Opencart Theme** with the latest assets.
Currently, there are very few or no _Opencart themes_ for _OC v4._
So you can sell your created theme in Opencart Marketplace.
It will eventually get more sales as you will have a first mover advantage.

**Pull request merged**
