### PR TITLE
Checkbox labels

### PR DESCRIPTION
**Pull request by stalker780**
Checkboxes should be linked to labels like other inputs in admin area

### CODE REVIEW

**Comment by TheCartpenter** [comment]
In OC 4.x releases, ```for=``` needs to go before ```class=``` .

**Comment by danielkerr** [comment]
should not as when u click on the label it clicks the slider

**Comment by stalker780** [comment]
> should not as when u click on the label it clicks the slider

That's the idea. This makes UI more convenient.

**Comment by danielkerr** [comment]
> > should not as when u click on the label it clicks the slider
> 
> That's the idea. This makes UI more convenient.

No it doesn't matter thats why I purposely removed the label.

**Pull request closed without merging**
