### PR TITLE
Custom field work done

### PR DESCRIPTION
**Pull request by engwalid1971**
This pull request will solve more custom field issues, i will explain in the comments.

### CODE REVIEW

**Comment by engwalid1971** [comment]
Issue 1:
1. Goto admin and add an enabled **affiliate** custom field
2. Goto the store and add a product to cart
3. Click the checkout
4. Continue as a new customer
5. Try to complete the 'Step 2: Account & Billing Details'
6. Nothing will be happens, you can't complete the order.
7. If you disable all the **affiliate** custom fields then you can complete the order

**Comment by engwalid1971** [comment]
**Issue 2:**
1. Goto admin and add an enabled **account** custom field with sort order 5
2.  Goto the 'sale/order/add' form
3. The custom field is hidden

**Issue 3:**
1. Goto admin and change the sort order of the **account** custom field to -1
2. Goto the store and view the register form 'account/register'
3. The custom field is hidden

**Notes:**
- 5 is the $('.form-group').length - 3
- We need a minus value to sort the custom fields in the admin side

**Comment by engwalid1971** [comment]
**Issue 4:**
1. Goto admin and view the customer form 'customer/customer/add'
2. You will see the **disabled** affiliate custom fields

**Comment by engwalid1971** [comment]
**Issue 5:**
1. Goto admin -> customer/customer/edit
2. If the customer not have any addresses add the new one
3. Save
4. Nothing will be happens, you can't edit the customer if he have any addresses

**Comment by engwalid1971** [comment]
The previous issues is an examples only, the custom fields have more issues.

**Comment by straightlight** [comment]
Are these issues found and modifications, both, for the master branch?

**Comment by engwalid1971** [comment]
> Are these issues found and modifications, both, for the master branch?

Yes, this issues and modifications for the master branch .

**Comment by engwalid1971** [comment]
The pull request need some modification ...

**Pull request closed without merging**
