### PR TITLE
[3.0.x.x] replaced wget with curl ecb controller

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
Why? There was no bug!

**Comment by AJenbo** [comment]
Not all serves include wget by default, but curl is part of the standard package set.

**Comment by condor2** [comment]
> Why? There was no bug!

You have tested currency update using hosting Cron?

**Comment by mhcwebdesign** [comment]
> > Why? There was no bug!
> 
> You have tested currency update using hosting Cron?

Yes, works fine on our webhost.

**Comment by condor2** [comment]
With?

`wget -q "website_url" >/dev/null 2>&1`

**Comment by AJenbo** [comment]
@condor2 try saying what error you get when you do that...

**Comment by condor2** [comment]
> @condor2 try saying what error you get when you do that...

Using wget will download a bunch of 0 kb files on server.

`index.php?route=extension%2Fcurrency%2Fecb%2Frefresh
index.php?route=extension%2Fcurrency%2Fecb%2Frefresh.1
index.php?route=extension%2Fcurrency%2Fecb%2Frefresh.2
`

**Comment by AJenbo** [comment]
So that is 2 good reasons to switch to curl in favor of wget.
- wget can leave clutter on the server
- wget is not available on all server configurations

**Comment by mhcwebdesign** [comment]
You are quick coming to the wrong conclusion. The original call was a simple

wget -q "https://www.your-domain.com/index.php?route=extension/currency/ecb/refresh"

for the CRON task, and it works perfectly fine. What webhost doesn't have **wget** ? This one of the most common Linux/Unix commands available on webhosts.

**Comment by condor2** [comment]
> You are quick coming to the wrong conclusion. The original call was a simple
> 
> wget -q "https://www.your-domain.com/index.php?route=extension/currency/ecb/refresh"
> 

I have tested before. On my server download/generate zero-bytes files. so thats why I have tried with **>/dev/null 2>&1**, but same.

So I use curl -s without zero-bytes files.

**Comment by mhcwebdesign** [comment]
According to **wget --help**:

```
GNU Wget 1.20.3, a non-interactive network retriever.
Usage: wget [OPTION]... [URL]...
....
-q,  --quiet                     quiet (no output)
....
```

So ask your webhost to fix your wget then, we have run this command on countless servers/webhosts, never had this issue.

**Comment by AJenbo** [comment]
> You are quick coming to the wrong conclusion. The original call was a simple

You are quick to dismiss a problem with out understanding it. The new call is more compatible.

> wget -q "https://www.your-domain.com/index.php?route=extension/currency/ecb/refresh"
> 
> for the CRON task, and it works perfectly fine, without generated zero-bytes files.

Which vendor is your wget from? It could be a different between for example the BusyBox and GNU implementation.

> What webhost doesn't have **wget** ? This one of the most common Linux/Unix commands available on webhosts.

Lots. curl is part of the ubuntu-server meta package, wget is not, minimalistic setups based on ubuntu-server would be setup like that.
 
> please do some proper testing first

What is it that wasn't tested here?

**Comment by AJenbo** [comment]
> According to **wget --help**:
> 
> ```
> GNU Wget 1.20.3, a non-interactive network retriever.
> Usage: wget [OPTION]... [URL]...
> ....
> -q,  --quiet                     quiet (no output)
> ....
> ```
> 
> So ask your webhost to fix your wget then, we have run this command on countless servers/webhosts, never had this issue.

You are miss understanding that description, "quiet (no output)" means nothing is printed on stdout, not that it will not generate a file. This is used to avoid clutter in the server logs, not to have it not save the downloaded file. I'm starting to think you are the one that didn't test this.

**Comment by mhcwebdesign** [comment]
@Alenjo: OK, you right, the wget should indeed use the **-q --no-check-certificate -O /dev/null** . I stand corrected here!

**Pull request merged**
