### PR TITLE
Config getter improvement

### PR DESCRIPTION
**Pull request by alexslipknot**
Allow to set default value when default setting does not exists

### CODE REVIEW

**Comment by zemguru** [comment]
+1

**Comment by alexslipknot** [comment]
Hello, @danielkerr. 
Could you please say something? Maybe it's duplicate or you just has another opinion? 
Thank you anyway. You're doing great work.

**Comment by danielkerr** [comment]
not required.

**Comment by zemguru** [comment]
Not required by who? This is great, simple peace of code, which greatly reduces unneeded if/else checks on variable existence. And does not brake anything already available in Opencart. 
Good practice by Convention over configuration.

**Comment by danielkerr** [comment]
im not wasting my time with every one whose issue i reject.

**Comment by alexslipknot** [comment]
I'ts ok, I don't blame you. It's your project and it's not community version. 
But anyway it would be nice if you can have a staff for requests like that. Sometimes it may contents useful features.

**Comment by danielkerr** [comment]
explain the difference!

if i added every bit of code that people push the system would be fucked.

I have more experience with running an open source project than you do!

**Comment by alexslipknot** [comment]
Indeed. I agree with your opinion about security issues. That's why I suggested a staff for reviewing requests.
And one more thing. Don't judge people by their labels. I don't think that you know about my experience at all. Listen, sir, I don't want to offend you or your knowledge. Please take my apologizes if I hurt you somehow. I just wanted you to know about the idea. Thanks.

**Pull request closed without merging**
