### PR TITLE
Emphasize security process.

### PR DESCRIPTION
**Pull request by paragonie-scott**
Scanning the README, it took me a few tries to spot where the security reporting process is mentioned.

[PSR-9](https://github.com/php-fig/fig-standards/blob/master/proposed/security-disclosure-publication.md) might be worth looking into, going forward.

### CODE REVIEW

**Comment by Rpent001** [comment]
Whether or not there is a process in place, it is just common sense that one would try to contact a project admin and not post security vulnerabilities publicly.

Say your neighbor sees you left your door open one morning.  Would you rather they call you and let you know or do you prefer to figure out from one of their Facebook posts that afternoon when plenty of people have had the opportunity to pillage your belongings.  

It's not only common sense but also common courtesy.

**Comment by paragonie-scott** [comment]
> it is just common sense that one would try to contact a project admin and not post security vulnerabilities publicly.

You might feel that way, but the reality is far more nuanced:

* https://adamcaudill.com/2015/11/19/responsible-disclosure-is-wrong/
* https://www.schneier.com/essays/archives/2007/01/schneier_full_disclo.html

**Comment by jamesallsup** [comment]
The point has got nothing to do with secrecy, no one is trying to hide vulnerabilities. It is Open Source, reports always have been, are and will be released - the code is open to the world to strip down to its bones and find any problems it has.

The problem is that the moron who reported the issue just came out with it, no heads up, no warning, nothing, that was irresponsible without question and after his last comments I retract any gratitude I had for the report at all. It doesn't matter if it takes 1 or 100 scans of a readme file to find the guidelines of reporting serious issues, all it takes is a message on the bug tracker to say hey I've found a possible security bug who can I contact - either Daniel or myself will reach out. You dont need to read any docs, just be courteous. If he spent the time to find the issue, document it and even upload to YouTube then he had time to send a message - seems evident that the point was to cause damage 

The impact is on the merchants, who by now have probably been scanned down by bots and on some shitlist for attack. @Rpent001 made a perfect example of it of how serious and stupid some people can be going about reporting issues.

The report was a good find and documented well, if that had been in our hands before being posted it could have had a resolution in the same post.

**Comment by paragonie-scott** [comment]
> It doesn't matter if it takes 1 or 100 scans of a readme file to find the guidelines of reporting serious issues, all it takes is a message on the bug tracker to say hey I've found a possible security bug who can I contact - either Daniel or myself will reach out.

As an experienced security researcher who has overlooked sections of project documentation that spelled out their process for handling security vulnerabilities before, every little bit helps. A lot of vulnerabilities are reported in the heat of the moment, especially if the person runs OpenCart on one of their systems and is panicking because they found something.

It *may* be worth considering making security its own section of the readme. Yes, it won't stop people who just post a 0day on the Internet with a YouTube demonstration from doing that, but people who legitimately want to help will be able to find the relevant section at a glance. Try it out and see if your signal:noise ratio goes up and frustration levels go down.

The purpose of this pull request was to help minimize mistakes and emphasize clear communication of the process. It wouldn't have stopped abusive behavior, but nothing can reliably do that.

Please do consider an update in the spirit of what I was proposing, even if you don't like the specific change that was made.

**Comment by jamesallsup** [comment]
@paragonie-scott I'll take a look over the PSR9 you mentioned, that does look interesting.

Just as you wrote the above I was saying: I will look at the readme and make the security section way more prominent :) We can all make changes to the docs though (I'm thinking 48 font, sans serif, bold, italic, underline and flashing pink to really grab the attention!) but if they don't read it then sadly this scenario happens.

> Please do consider an update in the spirit of what I was proposing, even if you don't like the specific change that was made.

Consider it now on my list of stuff to do asap [without the flashing pink. Orange, maybe]

**Comment by paragonie-scott** [comment]
Glad to hear it. :+1:

**Pull request closed without merging**
