### PR TITLE
Product design issue

### PR DESCRIPTION
**Pull request by smohamadabedy**
issue #11011

### CODE REVIEW

**Comment by smohamadabedy** [comment]
issue#11011

**Comment by smohamadabedy** [comment]
issue#11011

**Comment by condor2** [comment]
Test on mobile

**Comment by smohamadabedy** [comment]
RC

**Comment by smohamadabedy** [comment]
> Test on mobile

tested

**Comment by condor2** [comment]
And is not ugly? 3 product/row?

**Comment by smohamadabedy** [comment]
RS2

actually not bad for all viewports

**Comment by danielkerr** [comment]
i dont accepot commits with merges and reverts in. needs to be clean u need to have updated ur code base before commiting changes

**Pull request closed without merging**
