### PR TITLE
add slashes to escape javascript

### PR DESCRIPTION
**Pull request by veksen**
JS broke when language file (or db data) had quotes. Fixed what I've found.

### CODE REVIEW

**Comment by veksen** [comment]
Can be tested using the following vqmod :

    <?xml version="1.0" encoding="UTF-8"?>
    <modification>
        <id>Add quotes in front of every language variables to test javascript</id>
        <version>2.0.x</version>
        <author>veksen</author>

        <file name="admin/language/*/*.php,admin/language/*/*/*.php,catalog/language/*/*.php,catalog/language/*/*/*.php">
            <operation error="log">
                <search position="replace"><![CDATA[= ']]></search>
                <add><![CDATA[= '\'  ]]></add>
            </operation>
        </file>

    </modification>

Using a quote, you can see the JS breaking in in the admin, routes catalog/filter/add or catalog/option/add.

**Comment by danielkerr** [comment]
you need to clean up the commit as i can not see what is being changed

**Comment by veksen** [comment]
ok that is my mistake, I cleaned some whitespace at the same time, I will revert those to the original, and do another PR to fix whitespace/trailing.

**Comment by jamesallsup** [comment]
Veksen, I will close this PR as it can no longer be merged automatically. If you can submit a separate one with your js fix suggestions that would be appreciated. The whitespace pr has been merged now.

I can grant you access to our Jenkins build reviews if you like which gives you the line and files of where whitespace is and other issues - we are constantly working on these too!

**Pull request closed without merging**
