### PR TITLE
Check that PR has correct code style

### PR DESCRIPTION
**Pull request by AJenbo**
This adds a php-cs-fixer rule set, checks that PRs complies with the configured rules and corrects any left over violations in the code base (mostly left out because of conflicts).

The tool can also correct any violations, developers can have it do so by simply running `php system/storage/vendor/bin/php-cs-fixer fix`, or even better there IDE might support integration with the tool so that it happens when they save there code changes.

### CODE REVIEW

**Comment by AJenbo** [comment]
@mhcwebdesign the rules have now been applied hope that makes you a little less frustrated

**Comment by mhcwebdesign** [comment]
@AJenbo : Thank you for your hard work, much appreciated. Hopefully Daniel will do a public beta-release first of the upcoming 4.0.2.4, so more users will do extensive testing before a final release.

**Comment by TheCartpenter** [comment]
@AJenbo: The instance variables on top of each controllers do contain a new line before the next phpdoc comes in. This would have to be checked as well compared to the rest of the phpdocs down below each controllers so to ensure that the instance variables don't stick with the phpdocs at the top.

**Comment by AJenbo** [comment]
@TheCartpenter feel free to make any such adjustments to the rules, in the config you will find a link to a website that can help you generate the settings. Then you can run the tool an ser if you get the desired corrections to the code and submit a pr.

**Comment by TheCartpenter** [comment]
> @TheCartpenter feel free to make any such adjustments to the rules, in the config you will find a link to a website that can help you generate the settings. Then you can run the tool an ser if you get the desired corrections to the code and submit a pr.

The issue with this is there are no ways of distinction about ```return void``` phpdocs where no instance variables are declared at the top of the files compared to those that are declared with a spaced phpdoc block underneath. CS Fixer won't be able to track those parts.

**Comment by AJenbo** [comment]
@mhcwebdesign you mentioned that you didn't feel OC4 was production ready, so you have specific reasons for this, are there issues tracking it?

**Comment by mhcwebdesign** [comment]
Well, certainly OC 4.0.2.3 had too many issues, some of them were solved in the upcoming 4.0.2.4, others are still to be addressed. In addition to your many docs and formatting changes, there have also been a number of genuine bugfixes in recent weeks, and Daniel is still working on some features. Personally, I won't start testing OC 4 until at least the many daily formatting, docs, and cosmetic changes have been done.

I think it would make sense to do a public 4.0.2.4.beta first, so a wider range of users can test it and report any potential bugs. And only once they are really fixed, should the final 4.0.2.4 be released.

**Comment by AJenbo** [comment]
> In addition to your many docs and formatting changes

Should I understand that as a positive or a slight? I have also provided several bugfixes and I'm mostly doing the style changes as part of integrating a formatter tool based on your suggestion.

Regarding improvements to docs that is necessary in order to be able to use static analyzer tools to find and fix bugs in the code.

**Comment by AJenbo** [comment]
@mhcwebdesign I have now finished going over the php-cs-fixer rules to adjust the tool to match the project style and apply any corrections. But since you where not specific regarding what issues where remaining I can't really start working on "others are still to be addressed" as the next thing.

**Pull request merged**
