### PR TITLE
Backwards Compatibility Fix

### PR DESCRIPTION
**Pull request by OpenCartAddons**
- Added language directory fallback to compatibility event
- Added controllers to action_event in catalog config
- Added fallback to older extension directory for cart page module loading
- Fixed install/uninstall calls for older extensions (https://github.com/opencart/opencart/pull/4715)
- Fixed permissions for older extensions
- Changed default language directory object to public
- Removed unnecessary compatibility code in language library

### CODE REVIEW

**Comment by Dreamvention** [comment]
Really hope these fixes get added to the latest release. almost all our module rely on these simple fixes. 
the last changes to the folder structure have been a huge headache for us

**Comment by OpenCartAddons** [comment]
@jamesallsup I noticed there's now a 2.3.0.2 release, but these issues are still not corrected in the latest release.

**Comment by florinsith** [comment]
Please merge this for a 2.3.0.3 release. On the next big release we will have to create different versions of the extensions because of twig. And if we have to do it now too, that will leave us with 3 different versions of extension to maintain.

**Comment by OpenCartAddons** [comment]
At least with the twig implementation we can add conditional checks and load up a separate twig template file if needed. 

Not sure why this hasn't been pushed into the official release as I've already discussed these changes with Daniel before committing them.

**Comment by florinsith** [comment]
Thank you for the modification in user.php. Have a look at my comment from #4715, maybe you'll want to add that too.

**Comment by thekrotek** [comment]
Thank you for your fixes, but they only affect back-end. In front-end there's no backward compatibility. I'm using this piece of code in my OpenCart 2.3 Compatibility Fixes VQMod to fix this:

```xml
	<file name="catalog/controller/checkout/cart.php">
		<operation>
			<search position="before"><![CDATA[if ($files) {]]></search>
			<add><![CDATA[
			
			if (!$files) $files = glob(DIR_APPLICATION.'/controller/total/*.php');			
			
			]]></add>
		</operation>	
		<operation>
			<search position="before"><![CDATA[$result = $this->load->controller('extension/total/']]></search>
			<add><![CDATA[
			
			if (!file_exists(DIR_APPLICATION.'controller/extension/total/'.basename($file, '.php').'.php'))
				$result = $this->load->controller('total/'.basename($file, '.php'));
			else			
			
			]]></add>
		</operation>		
	</file>
	
	<file name="catalog/controller/checkout/confirm.php">
		<operation>
			<search position="before"><![CDATA[$data['payment'] = $this->load->controller('extension/payment/']]></search>
			<add><![CDATA[
			
			if (!file_exists(DIR_APPLICATION.'controller/extension/payment/'.$this->session->data['payment_method']['code'].'.php'))
				$data['payment'] = $this->load->controller('payment/'.$this->session->data['payment_method']['code']);
			else			
			
			]]></add>
		</operation>		
	</file>
```
The fix is very simple, only a few lines of code is required. I don't understand, why they don't come in default OpenCart package.

I hope this will help someone. Sorry for just a code instead of PR - GitHub is too geeky for me, I still can't understand, how all this branching and PR works.

**Comment by OpenCartAddons** [comment]
@thekrotek I've added compatibility for the cart modules and payment methods in checkout confirm.  Thanks for spotting these.

Cheers,
Joel.

**Comment by thekrotek** [comment]
@OpenCartAddons you're welcome, pal. I hope this will be added in OC source code.

**Comment by thekrotek** [comment]
By the way, there're other files in catalog, which require compatibility fixes. In my VQMod I've added a changes to these files:

catalog/controller/common/header.php - for analytics
catalog/controller/common/column_left.php (column_right.php, content_top.php, content_bottom.php) - for module data
catalog/controller/account/recurring.php - for recurring
catalog/controller/account/account.php - for credit card
catalog/controller/account/register.php (account/return.php, affiliate/register.php, checkout/guest.php, checkout/register.php, information/contact.php, product/product.php) - for captcha

Guess, just a list of files is enough for you, since you're pretty much aware, what to do further. Should you require a code instead - just send me a holler, I'll give you my VQMod, which contains all your fixes for admin and all my fixes for catalog.

**Comment by OpenCartAddons** [comment]
@thekrotek Update the catalog config file as per my latest commit.  The front end controller event was not registered in the config.

Cheers,
Joel.

**Comment by thekrotek** [comment]
@OpenCartAddons I assume, with the latest changes in catalog config fixes in catalog/controller files I mentioned above are not required?

Your latest removals from cart.php and confirm.php are a little confusing to me due to this as well. Can't figure out, how OC will load old modules on cart page without this:

```php
if (!$result) {
	$result = $this->load->controller('total/'.$module);
}
```

**Comment by OpenCartAddons** [comment]
@thekrotek The compatibility.php event file adds a fallback feature when loading controller files.  It checks to see if the controller is located in the new extension directory (extension/module/), and if no file is found it then checks the old extension directory (module/).

By updating the config file to register the controller event on the front end, the compatibility system will automatically look at total/$module even if extension/total/$module is called.

**Comment by thekrotek** [comment]
@OpenCartAddons oh, god! Of course! I somehow was looking on your code seeing include() instead of load->controller, sorry :-)

**Comment by OpenCartAddons** [comment]
@danielkerr @jamesallsup Is it possible to have this fix pushed into the next release?  

There are a lot of issues right now as most developers package a backwards compatibility mod with their products.  The problem is these mods are conflicting and causing issues for our customers.

Regards,
Joel.

**Comment by thekrotek** [comment]
I've just noticed, that even with all the compatibility fixes install/uninstall extension functions still don't work. OpenCart still looks in extension/extension_type/extension_name folder for controller and install/uninstall functions in it:

```php
$this->load->controller('extension/shipping/' . $this->request->get['extension'] . '/install');
```

So if on install extension creates some tables or adds fields, you'll end with MySQL error eventually. Same goes to uninstall functionality.

**Comment by OpenCartAddons** [comment]
I spoke with Daniel last week and he said backwards compatibility is being removed from the next version. 

You'll want to start updating your extensions. 

Cheers,
Joel.

**Comment by thekrotek** [comment]
@OpenCartAddons I already updated them and they all work with 2.3 with my OpenCart 2.3 Compatibility Fixes VQMod installed. Not a single customer refused to install it yet, everybody's happy.

As for removing backwards compatibility... well, I didn't expect the opposite, to be honest. Pretty typical response.

**Comment by OpenCartAddons** [comment]
It's unfortunate but I think I might have a solution that doesn't require vqmod. PM me on the forum. 

Joel.

**Comment by thekrotek** [comment]
@OpenCartAddons I don't use OpenCart forums much. Mind sharing your email/skype anyhow? I didn't find any on your site, just a contact form.

**Comment by OpenCartAddons** [comment]
Skype is joelreeds. I'll be on a little later.

**Pull request closed without merging**
