### PR TITLE
avoid adding duplicate geo zones

### PR DESCRIPTION
**Pull request by Jermim**

### CODE REVIEW

**Comment by pine3ree** [comment]
I believe that the same `country_id|zone_id` combination can belong to different geo_zones for different purposes. For example i can define a shipping geo_zone for Italy containing italy `country_id|0=all-zones` combination and e Europe EU VAT zone containing italy `country_i|0=all-zones`. I will use the first geo-zone for shipping methods and the second for tax-rates.

kind regards

**Comment by Jermim** [comment]
@pine3ree unique check is applied per geo_zone.

**Comment by pine3ree** [comment]
@Jermim 
oh yes, right, we are managing a single geo_zone...

**Comment by danielkerr** [comment]
not the best way of doing thngs

**Comment by danielkerr** [comment]
in future try using the same coding style.

**Comment by Jermim** [comment]
@danielkerr what coding style?

**Pull request merged**
