### PR TITLE
[3.0.x.x] incorrect case: googleshopping\exception\Connection.

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Fixed now. :)

**Comment by TheCartpenter** [comment]
> _ No description provided. _

------ --------------------------------------------------------------------- 
  Line   admin/controller/extension/advertise/google.php                      
 ------ --------------------------------------------------------------------- 
  13     Class ControllerExtensionAdvertiseGoogle uses unknown trait          
         googleshopping\traits\LibraryLoader.                                 
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  14     Class ControllerExtensionAdvertiseGoogle uses unknown trait          
         googleshopping\traits\StoreLoader.                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  29     Call to an undefined method                                          
         ControllerExtensionAdvertiseGoogle::loadStore().                     
  31     Call to an undefined method                                          
         ControllerExtensionAdvertiseGoogle::loadLibrary().                   
  86     Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  105    Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  247    Access to constant DEBUG_LOG_FILENAME on an unknown class            
         googleshopping\Googleshopping.                                       
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  407    Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  499    Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  512    Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  [67](https://github.com/opencart/opencart-3/actions/runs/7433986072/job/20227647264#step:6:68)1    Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  814    Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  930    Access to constant ROAS_WAIT_INTERVAL on an unknown class            
         googleshopping\Googleshopping.                                       
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  990    Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  1056   Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  1116   Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  1209   Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  12[69](https://github.com/opencart/opencart-3/actions/runs/7433986072/job/20227647264#step:6:70)   Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  1401   Access to constant API_URL on an unknown class                       
         googleshopping\Googleshopping.                                       
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  1442   Caught class ConnectionException not found.                          
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols

**Comment by TheCartpenter** [comment]
Issue remains.

**Comment by condor2** [comment]
On opencart-3 ?

**Comment by TheCartpenter** [comment]
> On opencart-3 ?

Yes

**Pull request merged**
