### PR TITLE
Added AUTO_INCREMENT in product_advertise table

### PR DESCRIPTION
**Pull request by Arthom**
Issue #7133 fix

### CODE REVIEW

**Comment by aironike** [comment]
Nice thanks!

**Comment by straightlight** [comment]
@danielkerr: This solution should be added in the system/helper/db_schema.php file on the master branch since the release OC v3.0.3.2 already in evaluation process.

**Comment by danielkerr** [comment]
there is no product_advertise table in the db_schema. its in the google shopping install code.

 this has already been fixed and should be in the latest stable release 3.0.3.2

**Comment by danielkerr** [comment]
ahh i see it in the 3.3.xxxbbranch. 

the fix has been added already 

`product_advertise_google_id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

**Comment by straightlight** [comment]
However, when going to the code tab: https://github.com/opencart/opencart/blob/master/upload/system/helper/db_schema.php , we type: advertise and the keyword does not come up as compared to the official release of OC v3.0.3.2 .

**Comment by straightlight** [comment]
From the official release, obviously, the advertise keywords do come up in the install/opencart.sql file.

**Comment by danielkerr** [comment]
the dev who created it will at some point add it to the master branch once its ready for release.

afew things left to do.

poroduct varaiants then fixing as many issues as i can. maybe the next few releases will soly be fix updates.

**Comment by straightlight** [comment]
Ok, no problem.

**Comment by kamleshwebtech** [comment]
Answer: run below solution to fix it 

Fixed the problem. Logged in to phpMyAdmin.
Remove: oc_product_advertise_google.
Go to -> SQL
Copy and paste the next lines:

DROP TABLE IF EXISTS `oc_product_advertise_google`;
CREATE TABLE `oc_product_advertise_google` (
`product_advertise_google_id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`product_id` int(11) DEFAULT NULL,
`store_id` int(11) NOT NULL DEFAULT '0',
`has_issues` tinyint(1) DEFAULT NULL,
`destination_status` enum('pending','approved','disapproved') NOT NULL DEFAULT 'pending',
`impressions` int(11) NOT NULL DEFAULT '0',
`clicks` int(11) NOT NULL DEFAULT '0',
`conversions` int(11) NOT NULL DEFAULT '0',
`cost` decimal(15,4) NOT NULL DEFAULT '0.0000',
`conversion_value` decimal(15,4) NOT NULL DEFAULT '0.0000',
`google_product_category` varchar(10) DEFAULT NULL,
`condition` enum('new','refurbished','used') DEFAULT NULL,
`adult` tinyint(1) DEFAULT NULL,
`multipack` int(11) DEFAULT NULL,
`is_bundle` tinyint(1) DEFAULT NULL,
`age_group` enum('newborn','infant','toddler','kids','adult') DEFAULT NULL,
`color` int(11) DEFAULT NULL,
`gender` enum('male','female','unisex') DEFAULT NULL,
`size_type` enum('regular','petite','plus','big and tall','maternity') DEFAULT NULL,
`size_system` enum('AU','BR','CN','DE','EU','FR','IT','JP','MEX','UK','US') DEFAULT NULL,
`size` int(11) DEFAULT NULL,
`is_modified` tinyint(1) NOT NULL DEFAULT '0',
PRIMARY KEY (`product_advertise_google_id`),
UNIQUE KEY `product_id_store_id` (`product_id`,`store_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

**Comment by dahmsh** [comment]
2020-10-01 5:36:59 - PHP Warning:  shell_exec() has been disabled for security reasons in /home/seejad/public_html/admin/controller/extension/module/abandonedcarts.php on line 267
2020-10-01 5:38:14 - PHP Warning:  shell_exec() has been disabled for security reasons in /home/seejad/public_html/admin/controller/extension/module/abandonedcarts.php on line 267
2020-10-01 5:39:00 - PHP Warning:  shell_exec() has been disabled for security reasons in /home/seejad/public_html/admin/controller/extension/module/abandonedcarts.php on line 267
2020-10-01 5:39:33 - PHP Warning:  shell_exec() has been disabled for security reasons in /home/seejad/public_html/admin/controller/extension/module/abandonedcarts.php on line 267
2020-10-01 8:23:38 - PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/seejad/public_html/catalog/controller/extension/captcha/google.php on line 27
2020-10-01 8:23:38 - PHP Warning:  file_get_contents(https://www.google.com/recaptcha/api/siteverify?secret=6Ld6D-MUAAAAAHfqndquh6WhrlrKZeN1mETV5BjT&response=03AGdBq254khmyRxNeRMCczmX35EYr2H0HaDBLrb5NYobq_4vTHGJKwT2omqBoNo1K3Qfp3rRnWAkINAuD0ghRMDVV-jYq_V_6VS6RXn2jptVixsdDnPJsksGierxHoigqDwt1IYWAJNTU0Sgg_UOJr0xRbElArAVGyKnbzFJZ-pKzr1W5E3eDFl7K1g3sKiPLivPBhgNVQG0udTjqgroFUzi7xMAN5A5YJOx7XAVTzYCzNP77shxQITvjJoXKhkIcU4qiTaoRhg-9SMxDVnCqHDzc0SQuEzpj0o0ndkHcHF88cl4Nn_z9BzG-4NCOvonuZu5WawukhD5AXppFhuf214Mp2fldhf0VuK4ZAJl4kC9lV8VMJ6_hhnSVIjupnokdLtsLCRrRlKby3jieRdCBx9CzcOJ5T8VLsL_5jRfZhRcHsXEqL2HxwEU&remoteip=95.185.203.91): failed to open stream: no suitable wrapper could be found in /home/seejad/public_html/catalog/controller/extension/captcha/google.php on line 27
2020-10-01 8:24:17 - PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/seejad/public_html/catalog/controller/extension/captcha/google.php on line 27
2020-10-01 8:24:17 - PHP Warning:  file_get_contents(https://www.google.com/recaptcha/api/siteverify?secret=6Ld6D-MUAAAAAHfqndquh6WhrlrKZeN1mETV5BjT&response=03AGdBq24JK_k3CKKN-JHnAJGZqHPZoQv2s5Ix5tWW7Ku6jwN1AddFU0n3XmhRVvs0QD7Z7S4Nt9gKpIoKv04JhIu56KOke0ZYQNKJ8J9Uyy1_lf9QWForTWoueoPeLpL8GWXT_Vglb6HQ0ZmAS3FO8yLeQ2pLDG1w5sJR-YSAhiIsIU26QhUwhAMxjmbpDA_pVxIDZ4_GR52YJp8N6X1XBm70v81PX6N3AuYEyQSRsbn6fkfrD_pyMoboRp7lKWNtqDn-FbtTIlcGSOmLWCg_1mUrIqcxnmkR9qFJ2pW_pedUyaBuvFMAyhMvpboRLDjLQqYf8R5om-T6OPC7y55ZVa-pw221TBcgwgI5QR7VGBNDcnJz9wcevYTHkyyZPjHoLKL2sae4LgStkjnFyuVAzFiIfBBgH4V_IeqJBfAyoUVpcvUlkhXUJdE&remoteip=95.185.203.91): failed to open stream: no suitable wrapper could be found in /home/seejad/public_html/catalog/controller/extension/captcha/google.php on line 27
2020-10-01 8:25:26 - PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/seejad/public_html/catalog/controller/extension/captcha/google.php on line 27
2020-10-01 8:25:26 - PHP Warning:  file_get_contents(https://www.google.com/recaptcha/api/siteverify?secret=6Ld6D-MUAAAAAHfqndquh6WhrlrKZeN1mETV5BjT&response=03AGdBq25p7_b740osbM10KebiUGFw1ZldfAme78u31jyseZUA52Vjz5e1rmy_HV_ms_0LHsH_umnVxzFrNYWC-Y0G2IPtgv1PxhGR0RYGf0ZecsSKU7SJGCbjARIL5Cj3V5ckpVr5fYsbupKb0Xg_G6nIJNyhBfx1wzZummCe4dd2vDS0vg2LBTM5MmkFC18Y7p7CnW8428WnRPvNuyYuFtQqwC-GVEd71bsPvne1FcnDpDhXCy4ljJYX2PMmZaERLdxBnRhWGtz4sf3HvfUAAyv8aj2y2hO39J_gOAzxXmkkKXkyT_NRMsiLVymYYskzymQ1iFDHWQKsXrLp8JH815AKt-hLMYifzF8nk4MQ-xufMkQOBc_xTk7Z2658pOlD8eFxncjFkapeFSDzEHtDWWJvQp_wkTQzUJsODbw9JS3xA8bPzfkZSlg&remoteip=95.185.203.91): failed to open stream: no suitable wrapper could be found in /home/seejad/public_html/catalog/controller/extension/captcha/google.php on line 27
2020-10-01 8:26:31 - PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/seejad/public_html/catalog/controller/extension/captcha/google.php on line 27
2020-10-01 8:26:31 - PHP Warning:  file_get_contents(https://www.google.com/recaptcha/api/siteverify?secret=6Ld6D-MUAAAAAHfqndquh6WhrlrKZeN1mETV5BjT&response=03AGdBq24bHDNEZ7d4pRLOJkSlggTjtM31hDh3dd8CZ5lAISN9PF_OYk58D3WrAhVwbdokUketk9Ms44Gf562MJIkib5h-0Wkve-_9zTKEJz0T1PfEt-AJEm3i0a76frDlnurk2BDa6hC2abadnoIDWHUniyPI3g2PT-YtcTNjt7MMRkV1Sr_zCAXG8ketZ2xuMRNc-VKR0a1s6kbNsrUMOHiCKhM6w-bFqpOcrx2pAnhy_mGR4rTqVqyJBEq7vke8DzC2Oh36tm5MNRDoL0PhibR0kcHcK3nhRj9xyopiYF8V_koRHZlyO_dN075hewn5rFk5iYHPH3p2mxDR_COd306x0wIHxY3G2VxLGH-BsgQyOHYFXr1KO_AyG1plvyVU2_UQHuVfzFxn81PntzdnlHs8g99jN8_HKbBa31KKEfCvtPLLaQamx5s&remoteip=95.185.203.91): failed to open stream: no suitable wrapper could be found in /home/seejad/public_html/catalog/controller/extension/captcha/google.php on line 27
2020-10-01 13:10:29 - PHP Notice:  Undefined index: route in /home/seejad/public_html/catalog/controller/extension/module/abandonedcartseventhandlers.php on line 175
2020-10-02 1:18:26 - PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/seejad/public_html/system/library/template/Twig/Extension/Core.php on line 1267
2020-10-02 1:31:47 - PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/seejad/public_html/system/library/template/Twig/Extension/Core.php on line 1267

**Comment by osworx** [comment]
@dahmsh wrong Platform!
1. you are using an Extension (abandonedcarts) which is not part of the core
2. some functions are disabled on your server
3. what do you want to say us - only copy & paste some code is not enough
4. use the OpenCart Forum for such: https://forum.opencart.com/

**Pull request closed without merging**
