### PR TITLE
Update twig.php

### PR DESCRIPTION
**Pull request by osysltd**

### CODE REVIEW

**Comment by straightlight** [comment]
This solution has already been integrated in the master branch.

**Comment by osysltd** [comment]
No, includes are not working with array loader

**Comment by straightlight** [comment]
Correct. However, it has been coded already in this commit solution: https://github.com/opencart/opencart/pull/7153/commits/0f32c158d4939d2829b3cc97d0695395125beda4 . See from this portion: `@@ -28,70 +25,19 @@ public function render($template, $cache = true) {` .

**Comment by osysltd** [comment]
Thanks, looking forward to have this merged

**Comment by danielkerr** [comment]
no issue

**Pull request closed without merging**
