### PR TITLE
Fix message "PHP7.4 Required"

### PR DESCRIPTION
**Pull request by opencartbot**

### CODE REVIEW

**Comment by batumibiz** [comment]
Can anyone explain why they started downgrading to an already old and officially [unsupported version](https://www.php.net/supported-versions.php) of PHP 7.4?
Who needs the old version, there is OpenCart 3.x.x
And it makes sense to develop version 4.x.x for current versions of PHP, I mean 8.x.x

**Comment by mhcwebdesign** [comment]
> Can anyone explain why they started downgrading to an already old and officially [unsupported version](https://www.php.net/supported-versions.php) of PHP 7.4? Who needs the old version, there is OpenCart 3.x.x And it makes sense to develop version 4.x.x for current versions of PHP, I mean 8.x.x

I agree. But unfortunately there are still too many webhosts and OpenCart users using PHP 7.4.

**Comment by batumibiz** [comment]
> I agree. But unfortunately there are still too many webhosts and OpenCart users using PHP 7.4.

Old hosting sites mostly use Opencart 3.
At least users always have a choice: either old versions of PHP + OpenCart 3, or OpenCart 4 and PHP 8+

**Comment by stalker780** [comment]
Imho, it would have more sense to release oc2 and oc3 updates with PHP 8.2 support :)

PHP 5.x/7.x are dead.

**Comment by mhcwebdesign** [comment]
> Imho, it would have more sense to release oc2 and oc3 updates with PHP 8.2 support :)
> 
> PHP 5.x/7.x are dead.

There already is an OpenCart 3.0.3.9 with full support for PHP 7.4, 8.0, 8.1 and 8.2.

**Comment by stalker780** [comment]
> There already is an OpenCart 3.0.3.9 with full support for PHP 7.4, 8.0, 8.1 and 8.2.

I know. I was using Maintenance branch for about 2 years. It should be released long time ago.

**Comment by danielkerr** [comment]
because more people setting up stores using the older version.

**Pull request merged**
