### PR TITLE
[3.0.x.x] Define private properties

### PR DESCRIPTION
**Pull request by AJenbo**
Resolves the last of the issues reported by PHPStan on level 0 for 3.0.x.x

### CODE REVIEW

**Comment by AJenbo** [comment]
@mhcwebdesign should we increase it to level 1 now?

**Comment by mhcwebdesign** [comment]
We still have to sort out this issue: https://github.com/opencart/opencart/issues/13518
Your solution here (https://github.com/opencart/opencart/pull/13556) is not the right approach.

And I think before increasing the PHPStan level, just a reminder the 3.0.x.x branch is mainly for bugfixes and having made it compatible with PHP 8.x versions, and with a goal of keeping it as much backward compatible for existing 3rd party extensions as possible, including the many OCmod-based extensions.

Once the wechatpay issue has been properly addressed, it might be a good idea then to do a 3.0.4.0 release first.

**Comment by AJenbo** [comment]
> just a reminder the 3.0.x.x branch is mainly for bugfixes and having made it compatible with PHP 8.x versions

Just, that's why PHPStan makes a lot of sens here since it is good at finding code that doesn't behave the same on all versions of PHP as well as general bugs.

**Comment by AJenbo** [comment]
Fixed here https://github.com/opencart/opencart/commit/725bd7a6563cee34d19af288e832ec4e700b4119

**Pull request closed without merging**
