### PR TITLE
[Master] - Added missing utf8_substr - admin/controller/common/filemanager.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
If that being the case, then what you're also implying is that utf8_substr that's been put into other similar IF statements are also wrong prior for me to add the last modification.

**Comment by ADDCreative** [comment]
Yes it looks like the other if statements are wrong in that file.

**Comment by danielkerr** [comment]
ok please do a pull request with it correct?

**Comment by ADDCreative** [comment]
> ok please do a pull request with it correct?

@danielkerr https://github.com/opencart/opencart/pull/11224

**Pull request merged**
