### PR TITLE
Add built-in plugin for NMI Collect.js inline

### PR DESCRIPTION
**Pull request by falconkirtaran**
Add built-in support for the USA merchant account platform NMI.  Support is done using their inline collect.js option, which uses iframes to gather card data, which should reduce the PCI compliance burden to something like SAQ A-EP rather than the SAQ-D required for authorize.net emulation with them.

### CODE REVIEW

**Comment by falconkirtaran** [comment]
Howdy @danielkerr.  Is this kind of PR of interest to the project?  I'm happy to keep contributing things I use to opencart as long as they're welcome.

We've been using this in production on our store cryoflesh.com for about a month now with no issues.

**Comment by danielkerr** [comment]
I'll look into it. I've been recently contacted by authorise.net

**Comment by falconkirtaran** [comment]
I was looking at making an updated integration for them too possibly, in 
case they wanted to avoid the SIM and AIM flows. This is kind of 
orthogonal to them, but useful for NMI; NMI used to emulate 
authorize.net's AIM protocol but the new iframe stuff differs between 
NMI and authorize.net.

**Comment by falconkirtaran** [comment]
I accidentally left TLS certificate checking off in my PR; that's fixed now.

I also sent one over for authorize.net (which was a lot more work; their API is a mess) in #7465 if you want to have a look, @danielkerr :)

**Comment by danielkerr** [comment]
im removing all 3rd party extensions. u need to post it into the marketplace.

**Pull request closed without merging**
