### PR TITLE
Update contact.php

### PR DESCRIPTION
**Pull request by alabamaster**
Fixed: setTo, setFrom and setReplyTo

### CODE REVIEW

**Comment by ADDCreative** [comment]
This is completely wrong. You don't want to send the email to the person filling in the contact form.

**Comment by alabamaster** [comment]
> This is completely wrong. You don't want to send the email to the person filling in the contact form.

I get this error `[Sat Feb 06 18:58:44.052202 2021] [php7:error] [pid 18806] [client 172.68.182.8:61454] PHP Fatal error:  Uncaught Exception: Error: DATA not accepted from server! in /var/www/html/system/library/mail/smtp.php:246\nStack trace:\n#0 /var/www/html/system/library/mail/smtp.php(214): Mail\\Smtp->handleReply(Resource id #18, 250, 'Error: DATA not...')\n#1 /var/www/html/system/library/mail.php(142): Mail\\Smtp->send()\n#2 /var/www/html/catalog/controller/information/contact.php(31): Mail->send()\n#3 /var/www/storage/modification/system/engine/action.php(79): ControllerInformationContact->index()\n#4 /var/www/html/catalog/controller/startup/router.php(25): Action->execute(Object(Registry))\n#5 /var/www/storage/modification/system/engine/action.php(79): ControllerStartupRouter->index()\n#6 /var/www/html/system/engine/router.php(67): Action->execute(Object(Registry))\n#7 /var/www/html/system/engine/router.php(56): Router->execute(Object(Action))\n#8 /var/www/html/system/framework.php(169): Router->dispatch(Object(Action), Object(Action))\n#9 /var/www/html/system/startup.php(104): require_once('/var/www/html/s...')\n#10 /var/www/html/in in /var/www/html/system/library/mail/smtp.php on line 246, referer: https://mysite/index.php?route=information/contact
`

if fixed, no errors and i get mail.

this code send mail to mail from config, need send mail to mail from request post. Or not?

**Comment by osworx** [comment]
`$mail->setTo($this->request->post['email']);`

Is wrong (as @ADDCreative already mentioned).
This is the contact form, where visitors want to contact YOU and not themself.

**Comment by alabamaster** [comment]
kekw

**Pull request closed without merging**
