### PR TITLE
[OC 4.0 Master] Admin Checkboxes Unchecked Values

### PR DESCRIPTION
**Pull request by nmpetkov**
Completion of the promised work in https://github.com/opencart/opencart/pull/11431

Description: Handle form 0/1 checkboxes, namely when the value is toggled between 0 and 1 with a checkbox, and the checkbox is unchecked, in the post is missing an entry with value 0.

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
So what exactly are you trying to accomplish? By its very nature, checkboxes, when unchecked, don't submit anything, see e.g. https://www.w3schools.com/tags/att_input_type_checkbox.asp

The controller needs to use something like this:

```
if (empty($this->request->post['my-checkbox'])) {
  // checkbox wasn't set
} else {
  // checkbox was set
}
```

**Comment by nmpetkov** [comment]
Using only checkboxes with value 1 and relaying on existent or not in POST is not compatible with previous Opencart versions, and in some cases is not enough, in cases you are adding new variables with default value not 0, but 1.
You are right is many cases there is no problem, but it is better to have consistent way to handle on/off variables in post forms.

**Comment by danielkerr** [comment]
its bootstrap that uses checkboxes as sliders so need to add default value

**Comment by danielkerr** [comment]
cheers

**Pull request merged**
