### PR TITLE
Alert mail settings in one place

### PR DESCRIPTION
**Pull request by p0v1n0m**
Now just add mail alert about new event.

c2cf854f58ab41ff86ab9cc5588d3cc8

### CODE REVIEW

**Comment by danielkerr** [comment]
i hope this is full tested.

**Comment by p0v1n0m** [comment]
Everything is tested before commit.

**Comment by danielkerr** [comment]
exept gettign errors like

text_alert 

Warning: in_array() expects parameter 2 to be array, string given in C:\xampp\htdocs\opencart\upload\admin\view\template\setting\setting.tpl on line 1150  text_account_mail

**Comment by p0v1n0m** [comment]
[This commit](https://github.com/opencart/opencart/commit/50de3802c6500b76d02c213b76eb96c418ac11fb#diff-5a0f5c4ba382e5e1f255313cf0e8023b) clearead my change in localisation. I will send new pull request with correction.

**Comment by justaraby** [comment]
4554

**Pull request merged**
