### PR TITLE
removes the overal page zooming on mobile and tablet

### PR DESCRIPTION
**Pull request by ThaFridge**
Some minor changes to the admin and default theme to remove mobile and tablet page zooming when insert/input box is hit

### CODE REVIEW

**Comment by pcmanik** [comment]
This no longer works on iOS and btw blocking user from zooming is bad practice.

**Comment by ThaFridge** [comment]
Your wrong sir, this still works on IOS and Android! Im still using it to make sure bootstrap use the right scalling on mobile devices since opencart doenst pratice it. And yes its even still working on my master branch fork

**Comment by pcmanik** [comment]
@ThaFridge Since iOS 10 user scalable attribute is ignored in Safari on iOS.

**Comment by ThaFridge** [comment]
@pcmanik it isnt, just test it your self on your IOS devices before we run into a endless discussion. Just remove both lines and just hit a input box. IOS will still do a page zoom around the input-box.

**Comment by danielkerr** [comment]
im sticking wit the bootstrap one.

**Pull request closed without merging**
