### PR TITLE
remove extra code to remove cart and recreate the cart with same value

### PR DESCRIPTION
**Pull request by WebkulOpencart**
Pull request for this issue [https://github.com/opencart/opencart/issues/7506](https://github.com/opencart/opencart/issues/7506)

### CODE REVIEW

**Comment by danijelGombac** [comment]
And if that the customer already has a product in the cart, this could creates duplicates of products in cart.

**Comment by WebkulOpencart** [comment]
@danijelGombac No, It will update the customer_id on the basis of session_id and customer_id = '0'
session_id always different for different customer.

**Comment by danijelGombac** [comment]
@WebkulOpencart 

You did not understand me.

Example:

I logged in yesterday and add product A in the cart and then logged out.

Today i add product A to the cart like guest and then logged in. Your code update only the customer_id.

Now i have duplicate product in the cart instead two pieces.

**Comment by MrPlow254** [comment]
@waqasjawed Your logic is flawed. The update query would have to be modified to update the quantity of the product id. If you are going to simplify code it needs to retain the original function. You need to test if this is even faster. I doubt it will be that much quicker since this only removes 1 select statement. The what $this-> add does is calls a select statement for the unique cart id and an insert/update statement for the same unique cart id.

```
$this->db->query("UPDATE " . DB_PREFIX . "cart C1
INNER JOIN (SELECT SUM(quantity) AS quantity, product_id FROM session_id = '" . $this->db->escape($this->session->getId()) . "' GROUP BY product_id) C2
ON C1.product_id = C2.product_id
SET customer_id = '" . (int)$this->customer->getId() . "', C1.quantity = C2.quantity, api_id = '" . (isset($this->session->data['api_id']) ? (int)$this->session->data['api_id'] : 0), `option` = '" . $this->db->escape(json_encode($option)) . "', recurring_id = '" . (int)true . "' WHERE session_id = '" . $this->db->escape($this->session->getId()) . "' AND customer_id='" . (int)$this->customer->getId() . "'");

$this->db->query("DELETE FROM " . DB_PREFIX . "cart WHERE api_id = '" . (isset($this->session->data['api_id']) ? (int)$this->session->data['api_id'] : 0) . "' AND customer_id = '" . (int)$this->customer->getId() . "' AND session_id = '" . $this->db->escape($this->session->getId()) . "'");
```

**Comment by WebkulOpencart** [comment]
@MrPlow254 Thanks for the suggestion.
@danijelGombac Yes, you are right, I am looking into this.

**Comment by straightlight** [comment]
Closure notes: Other technical opinions have been shared on the commit for better solutions. This commit will now be closed.

**Pull request closed without merging**
