### PR TITLE
Added integer on $page get request - admin/controller/localisation/geo_zone.php file.

### PR DESCRIPTION
**Pull request by straightlight**

### CODE REVIEW

**Comment by eka7a** [comment]
Wouldn't it be easier if you send a request with one commit for same changes? 😇

**Comment by straightlight** [comment]
> Wouldn't it be easier if you send a request with one commit for same changes? 😇

If I'd knew how, I'd do it. ;)

There are also different factors I have discovered. I am not done addressing the issues. Next batch is about sanitizing the integers GET and POST requests suggested by ADDCreative.

Thanks for merging all the requests, however. Still working on the next patches.

**Comment by eka7a** [comment]
You can download the repository to your computer and send all changes in one commit with Sublime Merge.
https://sublimemerge.com
https://m.youtube.com/results?search_query=SublimeMerge

**Comment by straightlight** [comment]
Thanks. I'll take a look at it after the next batch.

**Comment by straightlight** [comment]
Done with the sanitizing batch for the most obvious ones.

**Pull request merged**
