### PR TITLE
Removed extra </div> above the last closing - admin/view/template/tool/log.twig file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by eka7a** [comment]
The div you removed belongs to the content id.

**Comment by TheCartpenter** [comment]
Not sure why this commit was closed but if you compare both TWIG files, maintenance and master branch, you'll see there's an extra DIV.

**Comment by ADDCreative** [comment]
@eka7a is correct, you have removed the closing DIV for one with the ID of content.

**Comment by TheCartpenter** [comment]
On the master branch, all the DIVs fits.

**Comment by ADDCreative** [comment]
Why don't you just count them. You will find 10 opening <div> and 10 closing </div>. With your change you have 10 <div> and 9 </div>.

**Pull request closed without merging**
