### PR TITLE
Configurable admin image thumbnail size

### PR DESCRIPTION
**Pull request by stalker780**
Allow users to configure admin image thumbnail size.

Sometimes this may even save disk space avoiding 100x100 images which are almost never used in the frontend.

image

### CODE REVIEW

**Comment by danielkerr** [comment]
there should be a default width and height already

**Comment by danielkerr** [comment]
i prefer to use image_default_width, image_default_height

**Comment by stalker780** [comment]
> i prefer to use image_default_width, image_default_height

@danielkerr Sorry, I have missed your answer. Renamed variables now.

**Comment by danielkerr** [comment]
its not required

**Pull request closed without merging**
