### PR TITLE
Added control_structure_continuation_position on same line

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
This generated file also seem to fail with PHP 8.3 checks.

**Comment by TheCartpenter** [comment]
The original file also causes an error: expected ```]``` . I corrected it.

**Comment by TheCartpenter** [comment]
I think it's for all the submissions being submitted, not just this file...

PHP 8.1 now says canceled on recent PRs as well.

**Comment by AJenbo** [comment]
Other jobs are canceled when one fails. look at the failed, not the canceled

**Comment by TheCartpenter** [comment]
> Other jobs are canceled when one fails. look at the failed, not the canceled

Correct. The details shows the error that I described about the ```.php-cs-fixer``` file.

**Comment by TheCartpenter** [comment]
And also about the ```startup/seo_url``` void removal from this branch.

**Pull request closed without merging**
