### PR TITLE
Fix PHP 7.4 support

### PR DESCRIPTION
**Pull request by AJenbo**
I hear the code is suppose to be 7.4 compatible so here are some fixes for that to be true.

See https://github.com/opencart/opencart/pull/12896 for one issue not addressed by this PR.

### CODE REVIEW

**Comment by AJenbo** [comment]
Could you please provide a comment explaining the reason for the closure?

**Comment by AJenbo** [comment]
@danielkerr Could you please provide a comment explaining the reason for the closure?

**Comment by danielkerr** [comment]
i already acceoted ur other commit. i thought they were the same

**Comment by AJenbo** [comment]
... they didn't exist before you closed this one

**Pull request closed without merging**
