### PR TITLE
Fix table responsive in customer_list.twig

### PR DESCRIPTION
**Pull request by ManoelVidal**
Add in table:
`<div class="table-responsive"></div>`

### CODE REVIEW

**Comment by danijelGombac** [comment]
Table responsive and dropdown are not working together.

**Comment by ManoelVidal** [comment]
fix customer_list.twig and order_list.twig
https://github.com/opencart/opencart/pull/5675

Clean/update theme cache in developer setting

**Comment by danijelGombac** [comment]
No, this is bootstrap problem. Table responsive and dropdown are not working together. The dropdown is hidden.

**Comment by ManoelVidal** [comment]
Here it is working in chrome

**Comment by danijelGombac** [comment]
https://github.com/twbs/bootstrap/issues/11037
https://github.com/twbs/bootstrap/issues/15288
https://github.com/twbs/bootstrap/issues/15374

**Comment by ManoelVidal** [comment]
You might want to test?

**Comment by danijelGombac** [comment]
I try and it's ok, is not so fancy, but no need to scroll when dropdown is open. In bootstrap 4 works better. I was rewrite my admin to bootstrap 4 and there is not such problem.

**Pull request merged**
