### PR TITLE
Trimmed new lines - install/controller/upgrade/upgrade_5.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by Hkr32** [comment]
The work is still in progress, why create such a pr? Are You Normal?

**Comment by TheCartpenter** [comment]
Totally am. Line 73 also explains it.

**Comment by TheCartpenter** [comment]
File now looks different. Therefore, this commit will now be closed.

**Comment by Hkr32** [comment]
And I told you! Stop doing useless things, make at least one useful commit...

**Comment by TheCartpenter** [comment]
This commit had nothing to do with the many commits. It was a single commit with a simple file modification. nuance.

**Comment by Hkr32** [comment]
https://github.com/opencart/opencart/pull/9638
https://github.com/opencart/opencart/pull/9609

I can continue if you still have doubts about the usefulness of your work...

**Pull request closed without merging**
