### PR TITLE
Added whole DB field changes in upgrade/upgrade_8

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by danielkerr** [comment]
The upgrade system automatically adds any missing fields

Stop posting fucking rubbish. It makes me wonder what the fuck u are doing and if u actually know how stuff works. U actually caused more bugs with the 3.x versions

**Comment by danielkerr** [comment]
U wan tme to add company field to affiliate when it's already there on addresses

**Comment by TheCartpenter** [comment]
> The upgrade system automatically adds any missing fields
> 
> Stop posting fucking rubbish. It makes me wonder what the fuck u are doing and if u actually know how stuff works. U actually caused more bugs with the 3.x versions

If that'd be the case Daniel, then people wouldn't be encouraged to run fresh installs instead of the upgrade wizard. You want to talk about rubbish? Well, there's more that you can encounter on this release than you could expect since the issues that haven't been reported haven't come yet. That's the only reason why you believe that everything is working on 'your end'.



> U wan tme to add company field to affiliate when it's already there on addresses

The company field wasn't added, read the damn code - it says MODIFY, not ADD!

**Comment by TheCartpenter** [comment]
You're missing bunch of stuff.

**Pull request closed without merging**
