### PR TITLE
Bootstrap slider

### PR DESCRIPTION
**Pull request by trydalcoholic**
#8822
Swiperjs removed.
Moved banner / carousel / slideshow modules to work with carousel bootstrap.
By default, carousel bootstrap does not support multiple items. For this, I made a small modification in jquery. Unfortunately, nothing else occurred to me how to use css variables. For this reason, flipping through slides in the ie11 carousel does not look very neat.
I would be glad to receive any help in revision and comments.

### CODE REVIEW

**Comment by cgcmart** [comment]
manufacturer carousel is working.
home page slideshow doesn't slide.

**Comment by BuslikDrev** [comment]
https://codepen.io/SitePoint/pen/qiAyo
https://html5css.ru/howto/howto_js_slideshow.php
http://cssslider.com/responsive-slider-2.html
And don't use jquery

**Comment by trydalcoholic** [comment]
Hello!
Can you please explain in more detail what you want to pay attention to in these examples?
What are you suggesting not to use jquery here for? Opencart uses Bootstrap 4 (which depends on jquery) and also the js code of Opencart is based on jquery. Not using jquery seems to me to make the code less similar to the code style in Opencart.

**Comment by BuslikDrev** [comment]
> Привет!
> Не могли бы вы более подробно объяснить, на что вы хотите обратить внимание в этих примерах?
> Для чего вы предлагаете не использовать здесь jquery? Opencart использует Bootstrap 4 (который зависит от jquery), а также js-код Opencart основан на jquery. Мне кажется, что отказ от jquery делает код менее похожим на стиль кода в Opencart.

Ditch jquery to improve website loading speed, and cross-site scripting problems.

**Pull request closed without merging**
