### PR TITLE
Translation fr

### PR DESCRIPTION
**Pull request by ABroye**

### CODE REVIEW

**Comment by condor2** [comment]
Wrong place for this pull

**Comment by TheCartpenter** [comment]
Catalogue path also doesn't exist. It's like saying Kellogre instead of Kellogs.

**Comment by danielkerr** [comment]
i dont speak french and dont have time to update every change

**Comment by ABroye** [comment]
No problem, I translated opencart in its entirety for my personal use, I wanted to benefit the French community by releasing a full French version.
Good day to you

**Comment by condor2** [comment]
You can make a language pack. More easy to update

**Comment by ABroye** [comment]
Yes this is what I did for the following directories:

admin/language/fr-fr
catalog/language/fr-fr
extension/opencart/admin/language/fr-fr
extension/opencart/catalog/language/fr-fr
install/language/fr-fr

**Comment by condor2** [comment]
You can upload on Marketplace

https://www.opencart.com/index.php?route=marketplace/extension

**Pull request closed without merging**
