### PR TITLE
Fixed a bug where after config files were created in step 2 of installa…

### PR DESCRIPTION
**Pull request by Boorinio**
…tion, controller would always redirect to upgrade form.

### CODE REVIEW

**Comment by straightlight** [comment]
Perhaps utf-8 functions with substr should also be used above to see if that would replaced the alternative solution ...

**Comment by straightlight** [comment]
The closing brackets of methods don't need to contain extra spaces. As for the config pagination, it may still be questionable due to the limitations of the autocomplete results. As for the arrays, that would be right.

**Comment by Boorinio** [comment]
> Perhaps utf-8 functions with substr should also be used above to see if that would replaced the alternative solution ...

is there a reason for utf substr functions since the urls of installation are always English characters?

**Comment by straightlight** [comment]
While it is correct that only the en-gb is installed by default, there are also language packs where the install folder are implicit.

**Comment by osworx** [comment]
> is there a reason for utf substr functions since the urls of installation are always English characters?
Not correct!
For example German, can be used during the installation to install OpenCart in German. It is a second package and needed for German speaking people don't speaking English.
Note: the World exists of more not only English ..

**Comment by Boorinio** [comment]
Correct me if I am wrong but even at other languages the controller urls do not change. The folder remains "install" and the controller remains as step_1 etc. You only add more folders in language folder just like catalog or admin works.

**Pull request merged**
