### PR TITLE
Add customer comments to the Order Confirmation email

### PR DESCRIPTION
**Pull request by BryanT4212**
OC 4.0.2.2 master at e391de5fc8 (Just before blogs were added)

<s>Make sure to include the customer's comments/instructions when confirming the order.  

If no comment was specified when adding the order, check if an order comment exists and use it when mailing the order confirmation.</s>

See https://github.com/opencart/opencart/pull/12671#issuecomment-1716931811

### CODE REVIEW

**Comment by ADDCreative** [comment]
@BryanT4212 The customer's comment would need to be separate. It doesn't make sense to only include the customer's comment if there is no comment from the payment extension.

What happens if you use the cheque payment extension which sets the comment? You would never see the customer's comment in the email,

**Comment by BryanT4212** [comment]
@ADDCreative  OK, then I guess you must never see the customer's comment now?

So... add $data['instructions'] = $comment logic so the template has access to both instructions and comments?  Maybe even change the name of the argument to $instructions instead of $comment?

**Comment by ADDCreative** [comment]
@BryanT4212 No, currently there are no customer's comments in the email. This is by design apparently. See https://github.com/opencart/opencart/issues/93.

**Comment by BryanT4212** [comment]
@ADDCreative By design or by omission?

The issues and pull request seem to have been closed without any justification given.  In fact, they all seem to have been closed prior to any discussion taking place.  So where does that leave us?

**Comment by ADDCreative** [comment]
@BryanT4212 See the comment from the developer here https://github.com/opencart/opencart/issues/93#issuecomment-8200140.

You could try another pull request that correctly adds the customer's comments separately, but don't be surprised if it's rejected.

**Comment by BryanT4212** [comment]
@ADDCreative Well... it's difficult to see https://github.com/opencart/opencart/issues/93#issuecomment-8200140 as much of a resolution of the issue or justification for closure as it is just a question and occurred 8 days after the issue & PR were closed in any case.  I think I will try repurposing this request and try again by updating your PR #94 for v4.

**Comment by BryanT4212** [comment]
@ADDCreative What do you think?  Ready for review this time around?

**Comment by BuslikDrev** [comment]
You are doing nonsense by creating unnecessary load by adding arrays.

**Comment by BryanT4212** [comment]
OC 4.0.2.2

Proposed enhancement to include confirmation of the customer's order comments/instructions in the Order Confirmation email and clarify in the code that what is being passed in to the event handler are the payment details provided by the payment system and not the customer's order comments.  

Some housekeeping modifications:
- Place the payment details immediately after the total amount due for the order/invoice
- Move the formatting of newlines as HTML <BR> elements in the order comments and payment details from the controller into the view with the rest of the HTML generation
- Whitespace cleanup

**Comment by danielkerr** [comment]
for adding the order it should be fine.

**Comment by ADDCreative** [comment]
@danielkerr With the commit https://github.com/opencart/opencart/commit/b35daf7d47e3c3d36e6387f23b432b0df5db6ac7. Now the payment instruction don't appear in the email to the customer. If using cheque or bank transfer, the customer will need the payment instruction to pay.

Also now the customer comments appear under the heading "Instructions", where it should be comments. The order email needs to be like the route=account/order.info page, where is shows both the customer comments and the payment instructions.

**Comment by BryanT4212** [comment]
@danielkerr @ADDCreative Yeah, I'm afraid this is not a functionally compatible/accurate merge of the pull request and won't work as intended.  It turned out the original temp;late did not support customer comments at all so they had to be added separate and distinct from the payment instructions generated by the payment system which requires template as well as controller changes.

**Comment by danielkerr** [comment]
ok

**Pull request closed without merging**
