### PR TITLE
Removed commented out $data['balance'] - admin/controller/sale/subscription.php file

### PR DESCRIPTION
**Pull request by TheCartpenter**

### CODE REVIEW

**Comment by danielkerr** [comment]
stop workingon the subscription system im working in it.

**Comment by TheCartpenter** [comment]
Ok

**Comment by danielkerr** [comment]
u just dont want to overlap commits.

**Comment by TheCartpenter** [comment]
While one would put his priorities on the mount of commits due to those douzaines of people complaining about it, my priorities are rather focused on those hundreds of thousands of people waiting for the next release before the due date of the deprecation of previous PHP versions that's been set by the Industry in the next 3 months. Therefore, that's all we both got left.

**Comment by danielkerr** [comment]
I'm going to do a mini release today then will finish the subscription system

**Comment by TheCartpenter** [comment]
Great, now we're talking. I will await the next subscription updates before finishing the integration of the affiliates, by design.

**Pull request merged**
